name: {{project_name}}_{{platform}}_{{name}}
description: {{description}}
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  auto_route: ^7.7.1
  injectable: ^2.1.2
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_{{platform}}:
  {{project_name}}_{{platform}}_localization:
  {{project_name}}_{{platform}}_navigation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  alchemist: ^0.6.1
  bloc_test: ^9.1.3
  mocktail: ^0.3.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  auto_route_generator: ^7.2.0
  injectable_generator: ^2.1.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1
  {{project_name}}_{{platform}}_app:

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true


# The following section is specific to Flutter packages.
flutter:
{{^ios}}{{^macos}}  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
{{/macos}}{{/ios}}  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
