// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final diPackageBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": ".gitignore",
      "data":
          "IyBGaWxlcyBhbmQgZGlyZWN0b3JpZXMgY3JlYXRlZCBieSBwdWIuCi5kYXJ0X3Rvb2wvCi5wYWNrYWdlcwoKIyBDb252ZW50aW9uYWwgZGlyZWN0b3J5IGZvciBidWlsZCBvdXRwdXRzLgpidWlsZC8KCiMgQ29udmVudGlvbmFsIGRpcmVjdG9yeSBmb3IgY292ZXJhZ2Ugb3V0cHV0cy4KL2NvdmVyYWdlCg==",
      "type": "text"
    },
    {
      "path": "analysis_options.yaml",
      "data":
          "IyBUaGlzIGZpbGUgY29uZmlndXJlcyB0aGUgc3RhdGljIGFuYWx5c2lzIHJlc3VsdHMgZm9yIHlvdXIgcHJvamVjdCAoZXJyb3JzLAojIHdhcm5pbmdzLCBhbmQgbGludHMpLgojCiMgVGhpcyBlbmFibGVzIHRoZSAncmVjb21tZW5kZWQnIHNldCBvZiBsaW50cyBmcm9tIGBwYWNrYWdlOmxpbnRzYC4KIyBUaGlzIHNldCBoZWxwcyBpZGVudGlmeSBtYW55IGlzc3VlcyB0aGF0IG1heSBsZWFkIHRvIHByb2JsZW1zIHdoZW4gcnVubmluZwojIG9yIGNvbnN1bWluZyBEYXJ0IGNvZGUsIGFuZCBlbmZvcmNlcyB3cml0aW5nIERhcnQgdXNpbmcgYSBzaW5nbGUsIGlkaW9tYXRpYwojIHN0eWxlIGFuZCBmb3JtYXQuCiMKIyBJZiB5b3Ugd2FudCBhIHNtYWxsZXIgc2V0IG9mIGxpbnRzIHlvdSBjYW4gY2hhbmdlIHRoaXMgdG8gc3BlY2lmeQojICdwYWNrYWdlOmxpbnRzL2NvcmUueWFtbCcuIFRoZXNlIGFyZSBqdXN0IHRoZSBtb3N0IGNyaXRpY2FsIGxpbnRzCiMgKHRoZSByZWNvbW1lbmRlZCBzZXQgaW5jbHVkZXMgdGhlIGNvcmUgbGludHMpLgojIFRoZSBjb3JlIGxpbnRzIGFyZSBhbHNvIHdoYXQgaXMgdXNlZCBieSBwdWIuZGV2IGZvciBzY29yaW5nIHBhY2thZ2VzLgoKaW5jbHVkZTogcGFja2FnZTpsaW50cy9yZWNvbW1lbmRlZC55YW1sCgojIFVuY29tbWVudCB0aGUgZm9sbG93aW5nIHNlY3Rpb24gdG8gc3BlY2lmeSBhZGRpdGlvbmFsIHJ1bGVzLgoKIyBsaW50ZXI6CiMgICBydWxlczoKIyAgICAgLSBjYW1lbF9jYXNlX3R5cGVzCgojIGFuYWx5emVyOgojICAgZXhjbHVkZToKIyAgICAgLSBwYXRoL3RvL2V4Y2x1ZGVkL2ZpbGVzLyoqCgojIEZvciBtb3JlIGluZm9ybWF0aW9uIGFib3V0IHRoZSBjb3JlIGFuZCByZWNvbW1lbmRlZCBzZXQgb2YgbGludHMsIHNlZQojIGh0dHBzOi8vZGFydC5kZXYvZ28vY29yZS1saW50cwoKIyBGb3IgYWRkaXRpb25hbCBpbmZvcm1hdGlvbiBhYm91dCBjb25maWd1cmluZyB0aGlzIGZpbGUsIHNlZQojIGh0dHBzOi8vZGFydC5kZXYvZ3VpZGVzL2xhbmd1YWdlL2FuYWx5c2lzLW9wdGlvbnMK",
      "type": "text"
    },
    {
      "path": "CHANGELOG.md",
      "data": "IyMgMS4wLjAKCi0gSW5pdGlhbCB2ZXJzaW9uLgo=",
      "type": "text"
    },
    {
      "path": "lib/src/annotations.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmluamVjdGFibGUvaW5qZWN0YWJsZS5kYXJ0JzsKCi8vLyBVc2VkIHRvIGFubm90YXRlIGRlcGVuZGVuY2llcyB3aGljaCBhcmUgcmVnaXN0ZXJlZCB1bmRlciBjZXJ0YWluIHBsYXRmb3Jtcy4KYWJzdHJhY3QgY2xhc3MgUGxhdGZvcm0gewogIHN0YXRpYyBjb25zdCBhbmRyb2lkID0gJ2FuZHJvaWQnOwoKICBzdGF0aWMgY29uc3QgaW9zID0gJ2lvcyc7CgogIHN0YXRpYyBjb25zdCB3ZWIgPSAnd2ViJzsKCiAgc3RhdGljIGNvbnN0IGxpbnV4ID0gJ2xpbnV4JzsKCiAgc3RhdGljIGNvbnN0IG1hY29zID0gJ21hY29zJzsKCiAgc3RhdGljIGNvbnN0IHdpbmRvd3MgPSAnd2luZG93cyc7CgogIHN0YXRpYyBjb25zdCBtb2JpbGUgPSAnbW9iaWxlJzsKfQoKLy8vIFVzZSB0aGlzIHRvIGFubm90YXRlIEFuZHJvaWQgZGVwZW5kZW5jaWVzLgpjb25zdCBhbmRyb2lkID0gRW52aXJvbm1lbnQoUGxhdGZvcm0uYW5kcm9pZCk7CgovLy8gVXNlIHRoaXMgdG8gYW5ub3RhdGUgaU9TIGRlcGVuZGVuY2llcy4KY29uc3QgaW9zID0gRW52aXJvbm1lbnQoUGxhdGZvcm0uaW9zKTsKCi8vLyBVc2UgdGhpcyB0byBhbm5vdGF0ZSBXZWIgZGVwZW5kZW5jaWVzLgpjb25zdCB3ZWIgPSBFbnZpcm9ubWVudChQbGF0Zm9ybS53ZWIpOwoKLy8vIFVzZSB0aGlzIHRvIGFubm90YXRlIExpbnV4IGRlcGVuZGVuY2llcy4KY29uc3QgbGludXggPSBFbnZpcm9ubWVudChQbGF0Zm9ybS5saW51eCk7CgovLy8gVXNlIHRoaXMgdG8gYW5ub3RhdGUgbWFjT1MgZGVwZW5kZW5jaWVzLgpjb25zdCBtYWNvcyA9IEVudmlyb25tZW50KFBsYXRmb3JtLm1hY29zKTsKCi8vLyBVc2UgdGhpcyB0byBhbm5vdGF0ZSBXaW5kb3dzIGRlcGVuZGVuY2llcy4KY29uc3Qgd2luZG93cyA9IEVudmlyb25tZW50KFBsYXRmb3JtLndpbmRvd3MpOwoKLy8vIFVzZSB0aGlzIHRvIGFubm90YXRlIE1vYmlsZSBkZXBlbmRlbmNpZXMuCmNvbnN0IG1vYmlsZSA9IEVudmlyb25tZW50KFBsYXRmb3JtLm1vYmlsZSk7",
      "type": "text"
    },
    {
      "path": "lib/src/container.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmdldF9pdC9nZXRfaXQuZGFydCc7CgovLy8gVGhlIGRlcGVuZGVuY3kgaW5qZWN0aW9uIGNvbnRhaW5lci4KZmluYWwgZ2V0SXQgPSBHZXRJdC5pbnN0YW5jZTsK",
      "type": "text"
    },
    {
      "path": "lib/{{project_name}}_di.dart",
      "data":
          "Ly8vIERlcGVuZGVuY3kgSW5qZWN0aW9uIGZvciB7e3Byb2plY3RfbmFtZS50aXRsZUNhc2UoKX19LgovLy8KLy8vIFRoaXMgY29udGFpbnMgdGhlIGNvbnRhaW5lciBhbmQgYW5ub3RhdGlvbnMgcmVxdWlyZWQgZm9yIGRlcGVuZGVuY3kgaW5qZWN0aW9uLgovLy8KLy8vIFRvIHVzZSwgaW1wb3J0IGBwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fZGkve3twcm9qZWN0X25hbWV9fV9kaS5kYXJ0YC4KbGlicmFyeSB7e3Byb2plY3RfbmFtZX19X2RpOwoKZXhwb3J0ICdwYWNrYWdlOmluamVjdGFibGUvaW5qZWN0YWJsZS5kYXJ0JyBzaG93IEVudmlyb25tZW50OwoKZXhwb3J0ICdzcmMvYW5ub3RhdGlvbnMuZGFydCc7CmV4cG9ydCAnc3JjL2NvbnRhaW5lci5kYXJ0JzsKCg==",
      "type": "text"
    },
    {
      "path": "pubspec.yaml",
      "data":
          "bmFtZToge3sgcHJvamVjdF9uYW1lIH19X2RpCmRlc2NyaXB0aW9uOiBEZXBlbmRlbmN5IGluamVjdGlvbiBvZiB7e3Byb2plY3RfbmFtZS50aXRsZUNhc2UoKX19Lgp2ZXJzaW9uOiAwLjAuMQpwdWJsaXNoX3RvOiBub25lCgplbnZpcm9ubWVudDoKICBzZGs6ICI+PTMuMC4wIDw0LjAuMCIKCmRlcGVuZGVuY2llczoKICBnZXRfaXQ6IF43LjYuMAogIGluamVjdGFibGU6IF4yLjEuMQoKZGV2X2RlcGVuZGVuY2llczoKICBsaW50czogXjIuMS4wCiAgdGVzdDogXjEuMjQuMwo=",
      "type": "text"
    },
    {
      "path": "README.md",
      "data":
          "PCEtLSAKVGhpcyBSRUFETUUgZGVzY3JpYmVzIHRoZSBwYWNrYWdlLiBJZiB5b3UgcHVibGlzaCB0aGlzIHBhY2thZ2UgdG8gcHViLmRldiwKdGhpcyBSRUFETUUncyBjb250ZW50cyBhcHBlYXIgb24gdGhlIGxhbmRpbmcgcGFnZSBmb3IgeW91ciBwYWNrYWdlLgoKRm9yIGluZm9ybWF0aW9uIGFib3V0IGhvdyB0byB3cml0ZSBhIGdvb2QgcGFja2FnZSBSRUFETUUsIHNlZSB0aGUgZ3VpZGUgZm9yClt3cml0aW5nIHBhY2thZ2UgcGFnZXNdKGh0dHBzOi8vZGFydC5kZXYvZ3VpZGVzL2xpYnJhcmllcy93cml0aW5nLXBhY2thZ2UtcGFnZXMpLiAKCkZvciBnZW5lcmFsIGluZm9ybWF0aW9uIGFib3V0IGRldmVsb3BpbmcgcGFja2FnZXMsIHNlZSB0aGUgRGFydCBndWlkZSBmb3IKW2NyZWF0aW5nIHBhY2thZ2VzXShodHRwczovL2RhcnQuZGV2L2d1aWRlcy9saWJyYXJpZXMvY3JlYXRlLWxpYnJhcnktcGFja2FnZXMpCmFuZCB0aGUgRmx1dHRlciBndWlkZSBmb3IKW2RldmVsb3BpbmcgcGFja2FnZXMgYW5kIHBsdWdpbnNdKGh0dHBzOi8vZmx1dHRlci5kZXYvZGV2ZWxvcGluZy1wYWNrYWdlcykuIAotLT4KClRPRE86IFB1dCBhIHNob3J0IGRlc2NyaXB0aW9uIG9mIHRoZSBwYWNrYWdlIGhlcmUgdGhhdCBoZWxwcyBwb3RlbnRpYWwgdXNlcnMKa25vdyB3aGV0aGVyIHRoaXMgcGFja2FnZSBtaWdodCBiZSB1c2VmdWwgZm9yIHRoZW0uCgojIyBGZWF0dXJlcwoKVE9ETzogTGlzdCB3aGF0IHlvdXIgcGFja2FnZSBjYW4gZG8uIE1heWJlIGluY2x1ZGUgaW1hZ2VzLCBnaWZzLCBvciB2aWRlb3MuCgojIyBHZXR0aW5nIHN0YXJ0ZWQKClRPRE86IExpc3QgcHJlcmVxdWlzaXRlcyBhbmQgcHJvdmlkZSBvciBwb2ludCB0byBpbmZvcm1hdGlvbiBvbiBob3cgdG8Kc3RhcnQgdXNpbmcgdGhlIHBhY2thZ2UuCgojIyBVc2FnZQoKVE9ETzogSW5jbHVkZSBzaG9ydCBhbmQgdXNlZnVsIGV4YW1wbGVzIGZvciBwYWNrYWdlIHVzZXJzLiBBZGQgbG9uZ2VyIGV4YW1wbGVzCnRvIGAvZXhhbXBsZWAgZm9sZGVyLiAKCmBgYGRhcnQKY29uc3QgbGlrZSA9ICdzYW1wbGUnOwpgYGAKCiMjIEFkZGl0aW9uYWwgaW5mb3JtYXRpb24KClRPRE86IFRlbGwgdXNlcnMgbW9yZSBhYm91dCB0aGUgcGFja2FnZTogd2hlcmUgdG8gZmluZCBtb3JlIGluZm9ybWF0aW9uLCBob3cgdG8gCmNvbnRyaWJ1dGUgdG8gdGhlIHBhY2thZ2UsIGhvdyB0byBmaWxlIGlzc3Vlcywgd2hhdCByZXNwb25zZSB0aGV5IGNhbiBleHBlY3QgCmZyb20gdGhlIHBhY2thZ2UgYXV0aG9ycywgYW5kIG1vcmUuCg==",
      "type": "text"
    },
    {
      "path": "test/src/annotations_test.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmluamVjdGFibGUvaW5qZWN0YWJsZS5kYXJ0JyBzaG93IEVudmlyb25tZW50OwppbXBvcnQgJ3BhY2thZ2U6dGVzdC90ZXN0LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6e3twcm9qZWN0X25hbWV9fV9kaS9zcmMvYW5ub3RhdGlvbnMuZGFydCc7Cgp2b2lkIG1haW4oKSB7CiAgZ3JvdXAoJ1BsYXRmb3JtJywgKCkgewogICAgdGVzdCgnLmFuZHJvaWQnLCAoKSB7CiAgICAgIGV4cGVjdChQbGF0Zm9ybS5hbmRyb2lkLCAnYW5kcm9pZCcpOwogICAgfSk7CgogICAgdGVzdCgnLmlvcycsICgpIHsKICAgICAgZXhwZWN0KFBsYXRmb3JtLmlvcywgJ2lvcycpOwogICAgfSk7CgogICAgdGVzdCgnLmxpbnV4JywgKCkgewogICAgICBleHBlY3QoUGxhdGZvcm0ubGludXgsICdsaW51eCcpOwogICAgfSk7CgogICAgdGVzdCgnLm1hY29zJywgKCkgewogICAgICBleHBlY3QoUGxhdGZvcm0ubWFjb3MsICdtYWNvcycpOwogICAgfSk7CgogICAgdGVzdCgnLndlYicsICgpIHsKICAgICAgZXhwZWN0KFBsYXRmb3JtLndlYiwgJ3dlYicpOwogICAgfSk7CgogICAgdGVzdCgnLndpbmRvd3MnLCAoKSB7CiAgICAgIGV4cGVjdChQbGF0Zm9ybS53aW5kb3dzLCAnd2luZG93cycpOwogICAgfSk7CgogICAgdGVzdCgnLm1vYmlsZScsICgpIHsKICAgICAgZXhwZWN0KFBsYXRmb3JtLm1vYmlsZSwgJ21vYmlsZScpOwogICAgfSk7CiAgfSk7CgogIHRlc3QoJ2FuZHJvaWQnLCAoKSB7CiAgICBleHBlY3QoCiAgICAgIGFuZHJvaWQsCiAgICAgIGlzQTxFbnZpcm9ubWVudD4oKS5oYXZpbmcoKGUpID0+IGUubmFtZSwgJ25hbWUnLCAnYW5kcm9pZCcpLAogICAgKTsKICB9KTsKCiAgdGVzdCgnaW9zJywgKCkgewogICAgZXhwZWN0KGlvcywgaXNBPEVudmlyb25tZW50PigpLmhhdmluZygoZSkgPT4gZS5uYW1lLCAnbmFtZScsICdpb3MnKSk7CiAgfSk7CgogIHRlc3QoJ2xpbnV4JywgKCkgewogICAgZXhwZWN0KGxpbnV4LCBpc0E8RW52aXJvbm1lbnQ+KCkuaGF2aW5nKChlKSA9PiBlLm5hbWUsICduYW1lJywgJ2xpbnV4JykpOwogIH0pOwoKICB0ZXN0KCdtYWNvcycsICgpIHsKICAgIGV4cGVjdChtYWNvcywgaXNBPEVudmlyb25tZW50PigpLmhhdmluZygoZSkgPT4gZS5uYW1lLCAnbmFtZScsICdtYWNvcycpKTsKICB9KTsKCiAgdGVzdCgnd2ViJywgKCkgewogICAgZXhwZWN0KHdlYiwgaXNBPEVudmlyb25tZW50PigpLmhhdmluZygoZSkgPT4gZS5uYW1lLCAnbmFtZScsICd3ZWInKSk7CiAgfSk7CgogIHRlc3QoJ3dpbmRvd3MnLCAoKSB7CiAgICBleHBlY3QoCiAgICAgIHdpbmRvd3MsCiAgICAgIGlzQTxFbnZpcm9ubWVudD4oKS5oYXZpbmcoKGUpID0+IGUubmFtZSwgJ25hbWUnLCAnd2luZG93cycpLAogICAgKTsKICB9KTsKCiAgdGVzdCgnbW9iaWxlJywgKCkgewogICAgZXhwZWN0KAogICAgICBtb2JpbGUsCiAgICAgIGlzQTxFbnZpcm9ubWVudD4oKS5oYXZpbmcoKGUpID0+IGUubmFtZSwgJ25hbWUnLCAnbW9iaWxlJyksCiAgICApOwogIH0pOwp9Cg==",
      "type": "text"
    },
    {
      "path": "test/src/container_test.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnRlc3QvdGVzdC5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fZGkve3twcm9qZWN0X25hbWV9fV9kaS5kYXJ0JzsKCnZvaWQgbWFpbigpIHsKICB0ZXN0KCdnZXRJdCcsICgpIHsKICAgIGV4cGVjdChnZXRJdCwgaXNOb3ROdWxsKTsKICB9KTsKfQo=",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "di_package",
  "description": "A brick generating the di package of a Rapid project.",
  "version": "0.1.0",
  "environment": {"mason": ">=0.1.0-dev.47 <0.1.0"},
  "readme": {
    "path": "README.md",
    "data": "IyBkaV9wYWNrYWdlCgpUT0RPCg==",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMAoKLSBUT0RPOiBEZXNjcmliZSBpbml0aWFsIHJlbGVhc2UuCg==",
    "type": "text"
  },
  "vars": {
    "project_name": {"type": "string", "description": "The project name"}
  }
});
