Require rapid

Output create.gif

Set Shell zsh
Set FontSize 20
Set Width 1000
Set Height 700
Set Padding 30
Set BorderRadius 24
Set PlaybackSpeed 0.5
Set MarginFill "#222226"
Set Theme { "name": "Obsidian", "background": "#222226" }
Set WindowBar Colorful

# Type a command in the terminal.
Type "rapid create demo_app --ios"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 35s