Require rapid

Output pub_remove.gif

Set Shell zsh
Set FontSize 20
Set Width 1000
Set Height 300
Set Padding 30
Set BorderRadius 24
Set PlaybackSpeed 0.5
Set MarginFill "#222226"
Set Theme { "name": "Obsidian", "background": "#222226" }

Set WindowBar Colorful
Set WindowBarSize 60

# Type a command in the terminal.
Type "rapid pub remove collection"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 10s
