name: {{project_name}}

environment:
  sdk: ">=3.1.0 <4.0.0"

dev_dependencies:
  melos: ^3.1.1
  rapid_cli:
    git:
      url: https://github.com/jtdLab/rapid.git
      path: packages/rapid_cli

dependency_overrides:
  pub_updater: ^0.4.0
  file: ^7.0.0

rapid:
  name: {{project_name}}
