name: {{ project_name }}_di
description: Dependency injection of {{project_name.titleCase()}}.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
