name: {{project_name}}_infrastructure{{#has_name}}_{{name}}{{/has_name}}
description: TODO
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  injectable: ^2.3.0
  json_annotation: ^4.8.1
  {{project_name}}_logging:
  {{project_name}}_domain{{#has_name}}_{{name}}{{/has_name}}:

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  freezed: ^2.4.1
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6
