name: {{project_name}}_logging
description: Logging of {{project_name.titleCase()}}.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  injectable: ^2.3.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  mocktail: ^1.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  build_verify: ^3.1.0