name: {{project_name}}_logging
description: Logging of {{project_name.titleCase()}}.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  injectable: ^2.3.0
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  injectable_generator: ^2.4.0
  mocktail: ^1.0.0
  test: ^1.24.6
