version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/rapid_cli"
    target-branch: "dev"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/packages/rapid/rapid_domain"
    target-branch: "dev"
    schedule:
      interval: "weekly"
