arb-dir: lib/src/presentation/l10n/arb
output-class: ExampleWindowsAppLocalizations
output-dir: lib/src/presentation/l10n
template-arb-file: app_en.arb
output-localization-file: example_windows_app_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
