name: rapid_di
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
dependencies:
  injectable: ^2.1.0
