name: rapid_di
description: Dependency Injection for Rapid apps.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
