name: rapid

packages:
  - packages/rapid/rapid_domain
  - packages/rapid_cli

command:
  bootstrap:
    # https://github.com/dart-lang/pub/issues/3404)
    runPubGetInParallel: false
    hooks:
      post: melos run setup-pre-commit-hook
  clean:
    hooks:
      post: |
        rm -r node_modules && \
        rm commitlint.config.js && \
        rm package-lock.json && \
        rm package.json && \
        melos exec -c 3 -- "flutter clean"

ide:
  intellij: false

scripts:
  setup-pre-commit-hook:
    run: |
      npm install --save-dev @commitlint/{cli,config-conventional} && \
      echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js && \
      npm install husky --save-dev
      npx husky install
    description: |
      Set up pre commit hook to ensure Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0/) via commitlint (https://www.npmjs.com/package/commitlint).
       - Requires `node` (can be installed via Brew on macOS).

  format:
    run: |
      dart format packages/rapid --fix && \
      dart format packages/rapid_cli/bin --fix && \
      dart format packages/rapid_cli/lib --fix && \
      dart format packages/rapid_cli/test --fix
    description: Format the project

  analyze:
    run: |
      flutter analyze packages/rapid && \
      flutter analyze packages/rapid_cli/bin && \
      flutter analyze packages/rapid_cli/lib && \
      flutter analyze packages/apid_cli/test
    description: Analyze the project

  fix:
    exec: dart fix --apply
    description: Apply code fixes

  fix:dry:
    exec: dart fix --dry-run
    description: Code fixes in dry mode

  dev:activate:
    exec: dart pub global activate --source path .
    description: Locally activate rapid_cli for development.
    packageFilters:
      scope: "rapid_cli"

  dev:create:none:
    run: |
      melos dev:activate && \
      rm -r -f packages/rapid_cli/tmp && \
      rapid create foo_bar -o packages/rapid_cli/tmp
    description: Run rapid create for tinkering with no platform.

  dev:create:all:
    run: |
      melos dev:activate && \
      rm -r -f packages/rapid_cli/tmp && \
      rapid create foo_bar -o packages/rapid_cli/tmp --all
    description: Run rapid create for tinkering with all platforms.

  tool:bundles:
    exec: sh tool/bundles.sh
    description: Regenerate fresh bundles from templates.
    packageFilters:
      scope: "rapid_cli"

  git:bundles:into:dev:
    run: |
      git merge --ff-only origin/bundles && \
      git push origin dev
    description: Merge bundles branch into dev branch (This must be run from dev branch)

  git:dev:into:main:
    run: |
      git merge --ff-only origin/dev && \
      git push origin main
    description: Merge dev branch into main branch (This must be run from main branch)
