name: rapid

packages:
  - packages/rapid/rapid/rapid_domain
  - packages/rapid/rapid_test/rapid_test_domain
  - packages/rapid_cli

command:
  bootstrap:
    # https://github.com/dart-lang/pub/issues/3404)
    runPubGetInParallel: false

ide:
  intellij: false

# TODO update to melos 3.0.0 via https://melos.invertase.dev/guides/migrations
scripts:
  postbootstrap: melos run setup-pre-commit-hook
  postclean: |
    rm -r node_modules && \
    rm commitlint.config.js && \
    rm package-lock.json && \
    rm package.json && \
    melos exec -c 3 -- "flutter clean"

  setup-pre-commit-hook:
    run: |
      npm install --save-dev @commitlint/{cli,config-conventional} && \
      echo "module.exports = { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js && \
      npm install husky --save-dev
      npx husky install
    description: |
      Set up pre commit hook to ensure Conventional Commits (https://www.conventionalcommits.org/en/v1.0.0/) via commitlint (https://www.npmjs.com/package/commitlint).
       - Requires `node` (can be installed via Brew on macOS).

  format:
    run: melos exec -- "dart format . --fix"
    description: Format the project

  analyze:
    run: melos exec -- "flutter analyze"
    description: Analyze the project
