name: rapid_domain
description: Domain utils for Rapid apps.
version: 1.0.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dartz: ^0.10.1
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
