{{#android}}arb-dir: lib/src/presentation/l10n/arb
output-class: {{project_name.pascalCase()}}Android{{name.pascalCase()}}Localizations
output-dir: lib/src/presentation/l10n
template-arb-file: {{name}}_{{default_language}}.arb
output-localization-file: {{project_name}}_android_{{name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
{{/android}}{{#ios}}arb-dir: lib/src/presentation/l10n/arb
output-class: {{project_name.pascalCase()}}Ios{{name.pascalCase()}}Localizations
output-dir: lib/src/presentation/l10n
template-arb-file: {{name}}_{{default_language}}.arb
output-localization-file: {{project_name}}_ios_{{name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
{{/ios}}{{#linux}}arb-dir: lib/src/presentation/l10n/arb
output-class: {{project_name.pascalCase()}}Linux{{name.pascalCase()}}Localizations
output-dir: lib/src/presentation/l10n
template-arb-file: {{name}}_{{default_language}}.arb
output-localization-file: {{project_name}}_linux_{{name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
{{/linux}}{{#macos}}arb-dir: lib/src/presentation/l10n/arb
output-class: {{project_name.pascalCase()}}Macos{{name.pascalCase()}}Localizations
output-dir: lib/src/presentation/l10n
template-arb-file: {{name}}_{{default_language}}.arb
output-localization-file: {{project_name}}_macos_{{name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
{{/macos}}{{#web}}arb-dir: lib/src/presentation/l10n/arb
output-class: {{project_name.pascalCase()}}Web{{name.pascalCase()}}Localizations
output-dir: lib/src/presentation/l10n
template-arb-file: {{name}}_{{default_language}}.arb
output-localization-file: {{project_name}}_web_{{name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
{{/web}}{{#windows}}arb-dir: lib/src/presentation/l10n/arb
output-class: {{project_name.pascalCase()}}Windows{{name.pascalCase()}}Localizations
output-dir: lib/src/presentation/l10n
template-arb-file: {{name}}_{{default_language}}.arb
output-localization-file: {{project_name}}_windows_{{name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
{{/windows}}