arb-dir: lib/src/presentation/l10n/arb
output-class: ExampleAndroidHomePageLocalizations
output-dir: lib/src/presentation/l10n
template-arb-file: home_page_en.arb
output-localization-file: example_android_home_page_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
