arb-dir: lib/src/arb
output-class: {{project_name.pascalCase()}}Localizations
output-dir: lib/src/
template-arb-file: {{project_name}}_{{default_language_code}}{{#default_has_script_code}}_{{default_script_code}}{{/default_has_script_code}}{{#default_has_country_code}}_{{default_country_code}}{{/default_has_country_code}}.arb
output-localization-file: {{project_name}}_localizations.dart
nullable-getter: false
synthetic-package: false
header: |
  // coverage:ignore-file
  // ignore_for_file: type=lint