name: {{project_name}}_{{#android}}android{{/android}}{{#ios}}ios{{/ios}}{{#linux}}linux{{/linux}}{{#macos}}macos{{/macos}}{{#web}}web{{/web}}{{#windows}}windows{{/windows}}_navigation
description: Navigation of {{project_name.titleCase()}}.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^6.2.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
