// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final androidBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "packages/{{project_name}}/{{project_name}}/android/.gitignore",
      "data":
          "Z3JhZGxlLXdyYXBwZXIuamFyCi8uZ3JhZGxlCi9jYXB0dXJlcy8KL2dyYWRsZXcKL2dyYWRsZXcuYmF0Ci9sb2NhbC5wcm9wZXJ0aWVzCkdlbmVyYXRlZFBsdWdpblJlZ2lzdHJhbnQuamF2YQoKIyBSZW1lbWJlciB0byBuZXZlciBwdWJsaWNseSBzaGFyZSB5b3VyIGtleXN0b3JlLgojIFNlZSBodHRwczovL2ZsdXR0ZXIuZGV2L2RvY3MvZGVwbG95bWVudC9hbmRyb2lkI3JlZmVyZW5jZS10aGUta2V5c3RvcmUtZnJvbS10aGUtYXBwCmtleS5wcm9wZXJ0aWVzCioqLyoua2V5c3RvcmUKKiovKi5qa3MK",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/build.gradle",
      "data":
          "ZGVmIGxvY2FsUHJvcGVydGllcyA9IG5ldyBQcm9wZXJ0aWVzKCkKZGVmIGxvY2FsUHJvcGVydGllc0ZpbGUgPSByb290UHJvamVjdC5maWxlKCdsb2NhbC5wcm9wZXJ0aWVzJykKaWYgKGxvY2FsUHJvcGVydGllc0ZpbGUuZXhpc3RzKCkpIHsKICAgIGxvY2FsUHJvcGVydGllc0ZpbGUud2l0aFJlYWRlcignVVRGLTgnKSB7IHJlYWRlciAtPgogICAgICAgIGxvY2FsUHJvcGVydGllcy5sb2FkKHJlYWRlcikKICAgIH0KfQoKZGVmIGZsdXR0ZXJSb290ID0gbG9jYWxQcm9wZXJ0aWVzLmdldFByb3BlcnR5KCdmbHV0dGVyLnNkaycpCmlmIChmbHV0dGVyUm9vdCA9PSBudWxsKSB7CiAgICB0aHJvdyBuZXcgR3JhZGxlRXhjZXB0aW9uKCJGbHV0dGVyIFNESyBub3QgZm91bmQuIERlZmluZSBsb2NhdGlvbiB3aXRoIGZsdXR0ZXIuc2RrIGluIHRoZSBsb2NhbC5wcm9wZXJ0aWVzIGZpbGUuIikKfQoKZGVmIGZsdXR0ZXJWZXJzaW9uQ29kZSA9IGxvY2FsUHJvcGVydGllcy5nZXRQcm9wZXJ0eSgnZmx1dHRlci52ZXJzaW9uQ29kZScpCmlmIChmbHV0dGVyVmVyc2lvbkNvZGUgPT0gbnVsbCkgewogICAgZmx1dHRlclZlcnNpb25Db2RlID0gJzEnCn0KCmRlZiBmbHV0dGVyVmVyc2lvbk5hbWUgPSBsb2NhbFByb3BlcnRpZXMuZ2V0UHJvcGVydHkoJ2ZsdXR0ZXIudmVyc2lvbk5hbWUnKQppZiAoZmx1dHRlclZlcnNpb25OYW1lID09IG51bGwpIHsKICAgIGZsdXR0ZXJWZXJzaW9uTmFtZSA9ICcxLjAnCn0KCmFwcGx5IHBsdWdpbjogJ2NvbS5hbmRyb2lkLmFwcGxpY2F0aW9uJwphcHBseSBwbHVnaW46ICdrb3RsaW4tYW5kcm9pZCcKYXBwbHkgZnJvbTogIiRmbHV0dGVyUm9vdC9wYWNrYWdlcy9mbHV0dGVyX3Rvb2xzL2dyYWRsZS9mbHV0dGVyLmdyYWRsZSIKCmFuZHJvaWQgewogICAgY29tcGlsZVNka1ZlcnNpb24gZmx1dHRlci5jb21waWxlU2RrVmVyc2lvbgogICAgbmRrVmVyc2lvbiBmbHV0dGVyLm5ka1ZlcnNpb24KCiAgICBjb21waWxlT3B0aW9ucyB7CiAgICAgICAgc291cmNlQ29tcGF0aWJpbGl0eSBKYXZhVmVyc2lvbi5WRVJTSU9OXzFfOAogICAgICAgIHRhcmdldENvbXBhdGliaWxpdHkgSmF2YVZlcnNpb24uVkVSU0lPTl8xXzgKICAgIH0KCiAgICBrb3RsaW5PcHRpb25zIHsKICAgICAgICBqdm1UYXJnZXQgPSAnMS44JwogICAgfQoKICAgIHNvdXJjZVNldHMgewogICAgICAgIG1haW4uamF2YS5zcmNEaXJzICs9ICdzcmMvbWFpbi9rb3RsaW4nCiAgICB9CgogICAgZGVmYXVsdENvbmZpZyB7CiAgICAgICAgLy8gVE9ETzogU3BlY2lmeSB5b3VyIG93biB1bmlxdWUgQXBwbGljYXRpb24gSUQgKGh0dHBzOi8vZGV2ZWxvcGVyLmFuZHJvaWQuY29tL3N0dWRpby9idWlsZC9hcHBsaWNhdGlvbi1pZC5odG1sKS4KICAgICAgICBhcHBsaWNhdGlvbklkICJ7e29yZ19uYW1lfX0ue3twcm9qZWN0X25hbWV9fSIKICAgICAgICAvLyBZb3UgY2FuIHVwZGF0ZSB0aGUgZm9sbG93aW5nIHZhbHVlcyB0byBtYXRjaCB5b3VyIGFwcGxpY2F0aW9uIG5lZWRzLgogICAgICAgIC8vIEZvciBtb3JlIGluZm9ybWF0aW9uLCBzZWU6IGh0dHBzOi8vZG9jcy5mbHV0dGVyLmRldi9kZXBsb3ltZW50L2FuZHJvaWQjcmV2aWV3aW5nLXRoZS1idWlsZC1jb25maWd1cmF0aW9uLgogICAgICAgIG1pblNka1ZlcnNpb24gZmx1dHRlci5taW5TZGtWZXJzaW9uCiAgICAgICAgdGFyZ2V0U2RrVmVyc2lvbiBmbHV0dGVyLnRhcmdldFNka1ZlcnNpb24KICAgICAgICB2ZXJzaW9uQ29kZSBmbHV0dGVyVmVyc2lvbkNvZGUudG9JbnRlZ2VyKCkKICAgICAgICB2ZXJzaW9uTmFtZSBmbHV0dGVyVmVyc2lvbk5hbWUKICAgIH0KCiAgICBidWlsZFR5cGVzIHsKICAgICAgICByZWxlYXNlIHsKICAgICAgICAgICAgLy8gVE9ETzogQWRkIHlvdXIgb3duIHNpZ25pbmcgY29uZmlnIGZvciB0aGUgcmVsZWFzZSBidWlsZC4KICAgICAgICAgICAgLy8gU2lnbmluZyB3aXRoIHRoZSBkZWJ1ZyBrZXlzIGZvciBub3csIHNvIGBmbHV0dGVyIHJ1biAtLXJlbGVhc2VgIHdvcmtzLgogICAgICAgICAgICBzaWduaW5nQ29uZmlnIHNpZ25pbmdDb25maWdzLmRlYnVnCiAgICAgICAgfQogICAgfQp9CgpmbHV0dGVyIHsKICAgIHNvdXJjZSAnLi4vLi4nCn0KCmRlcGVuZGVuY2llcyB7CiAgICBpbXBsZW1lbnRhdGlvbiAib3JnLmpldGJyYWlucy5rb3RsaW46a290bGluLXN0ZGxpYi1qZGs3OiRrb3RsaW5fdmVyc2lvbiIKfQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/debug/AndroidManifest.xml",
      "data":
          "PG1hbmlmZXN0IHhtbG5zOmFuZHJvaWQ9Imh0dHA6Ly9zY2hlbWFzLmFuZHJvaWQuY29tL2Fway9yZXMvYW5kcm9pZCIKICAgIHBhY2thZ2U9Int7b3JnX25hbWV9fS57e3Byb2plY3RfbmFtZX19Ij4KICAgIDwhLS0gVGhlIElOVEVSTkVUIHBlcm1pc3Npb24gaXMgcmVxdWlyZWQgZm9yIGRldmVsb3BtZW50LiBTcGVjaWZpY2FsbHksCiAgICAgICAgIHRoZSBGbHV0dGVyIHRvb2wgbmVlZHMgaXQgdG8gY29tbXVuaWNhdGUgd2l0aCB0aGUgcnVubmluZyBhcHBsaWNhdGlvbgogICAgICAgICB0byBhbGxvdyBzZXR0aW5nIGJyZWFrcG9pbnRzLCB0byBwcm92aWRlIGhvdCByZWxvYWQsIGV0Yy4KICAgIC0tPgogICAgPHVzZXMtcGVybWlzc2lvbiBhbmRyb2lkOm5hbWU9ImFuZHJvaWQucGVybWlzc2lvbi5JTlRFUk5FVCIvPgo8L21hbmlmZXN0Pgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/AndroidManifest.xml",
      "data":
          "PG1hbmlmZXN0IHhtbG5zOmFuZHJvaWQ9Imh0dHA6Ly9zY2hlbWFzLmFuZHJvaWQuY29tL2Fway9yZXMvYW5kcm9pZCIKICAgIHBhY2thZ2U9Int7b3JnX25hbWV9fS57e3Byb2plY3RfbmFtZX19Ij4KICAgPGFwcGxpY2F0aW9uCiAgICAgICAgYW5kcm9pZDpsYWJlbD0ie3twcm9qZWN0X25hbWV9fSIKICAgICAgICBhbmRyb2lkOm5hbWU9IiR7YXBwbGljYXRpb25OYW1lfSIKICAgICAgICBhbmRyb2lkOmljb249IkBtaXBtYXAvaWNfbGF1bmNoZXIiPgogICAgICAgIDxhY3Rpdml0eQogICAgICAgICAgICBhbmRyb2lkOm5hbWU9Ii5NYWluQWN0aXZpdHkiCiAgICAgICAgICAgIGFuZHJvaWQ6ZXhwb3J0ZWQ9InRydWUiCiAgICAgICAgICAgIGFuZHJvaWQ6bGF1bmNoTW9kZT0ic2luZ2xlVG9wIgogICAgICAgICAgICBhbmRyb2lkOnRoZW1lPSJAc3R5bGUvTGF1bmNoVGhlbWUiCiAgICAgICAgICAgIGFuZHJvaWQ6Y29uZmlnQ2hhbmdlcz0ib3JpZW50YXRpb258a2V5Ym9hcmRIaWRkZW58a2V5Ym9hcmR8c2NyZWVuU2l6ZXxzbWFsbGVzdFNjcmVlblNpemV8bG9jYWxlfGxheW91dERpcmVjdGlvbnxmb250U2NhbGV8c2NyZWVuTGF5b3V0fGRlbnNpdHl8dWlNb2RlIgogICAgICAgICAgICBhbmRyb2lkOmhhcmR3YXJlQWNjZWxlcmF0ZWQ9InRydWUiCiAgICAgICAgICAgIGFuZHJvaWQ6d2luZG93U29mdElucHV0TW9kZT0iYWRqdXN0UmVzaXplIj4KICAgICAgICAgICAgPCEtLSBTcGVjaWZpZXMgYW4gQW5kcm9pZCB0aGVtZSB0byBhcHBseSB0byB0aGlzIEFjdGl2aXR5IGFzIHNvb24gYXMKICAgICAgICAgICAgICAgICB0aGUgQW5kcm9pZCBwcm9jZXNzIGhhcyBzdGFydGVkLiBUaGlzIHRoZW1lIGlzIHZpc2libGUgdG8gdGhlIHVzZXIKICAgICAgICAgICAgICAgICB3aGlsZSB0aGUgRmx1dHRlciBVSSBpbml0aWFsaXplcy4gQWZ0ZXIgdGhhdCwgdGhpcyB0aGVtZSBjb250aW51ZXMKICAgICAgICAgICAgICAgICB0byBkZXRlcm1pbmUgdGhlIFdpbmRvdyBiYWNrZ3JvdW5kIGJlaGluZCB0aGUgRmx1dHRlciBVSS4gLS0+CiAgICAgICAgICAgIDxtZXRhLWRhdGEKICAgICAgICAgICAgICBhbmRyb2lkOm5hbWU9ImlvLmZsdXR0ZXIuZW1iZWRkaW5nLmFuZHJvaWQuTm9ybWFsVGhlbWUiCiAgICAgICAgICAgICAgYW5kcm9pZDpyZXNvdXJjZT0iQHN0eWxlL05vcm1hbFRoZW1lIgogICAgICAgICAgICAgIC8+CiAgICAgICAgICAgIDxpbnRlbnQtZmlsdGVyPgogICAgICAgICAgICAgICAgPGFjdGlvbiBhbmRyb2lkOm5hbWU9ImFuZHJvaWQuaW50ZW50LmFjdGlvbi5NQUlOIi8+CiAgICAgICAgICAgICAgICA8Y2F0ZWdvcnkgYW5kcm9pZDpuYW1lPSJhbmRyb2lkLmludGVudC5jYXRlZ29yeS5MQVVOQ0hFUiIvPgogICAgICAgICAgICA8L2ludGVudC1maWx0ZXI+CiAgICAgICAgPC9hY3Rpdml0eT4KICAgICAgICA8IS0tIERvbid0IGRlbGV0ZSB0aGUgbWV0YS1kYXRhIGJlbG93LgogICAgICAgICAgICAgVGhpcyBpcyB1c2VkIGJ5IHRoZSBGbHV0dGVyIHRvb2wgdG8gZ2VuZXJhdGUgR2VuZXJhdGVkUGx1Z2luUmVnaXN0cmFudC5qYXZhIC0tPgogICAgICAgIDxtZXRhLWRhdGEKICAgICAgICAgICAgYW5kcm9pZDpuYW1lPSJmbHV0dGVyRW1iZWRkaW5nIgogICAgICAgICAgICBhbmRyb2lkOnZhbHVlPSIyIiAvPgogICAgPC9hcHBsaWNhdGlvbj4KPC9tYW5pZmVzdD4K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/kotlin/{{#pathCase}}{{org_name}}/{{project_name}}{{/pathCase}}/MainActivity.kt",
      "data":
          "cGFja2FnZSB7e29yZ19uYW1lfX0ue3twcm9qZWN0X25hbWV9fQoKaW1wb3J0IGlvLmZsdXR0ZXIuZW1iZWRkaW5nLmFuZHJvaWQuRmx1dHRlckFjdGl2aXR5CgpjbGFzcyBNYWluQWN0aXZpdHk6IEZsdXR0ZXJBY3Rpdml0eSgpIHsKfQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/drawable-v21/launch_background.xml",
      "data":
          "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBNb2RpZnkgdGhpcyBmaWxlIHRvIGN1c3RvbWl6ZSB5b3VyIGxhdW5jaCBzcGxhc2ggc2NyZWVuIC0tPgo8bGF5ZXItbGlzdCB4bWxuczphbmRyb2lkPSJodHRwOi8vc2NoZW1hcy5hbmRyb2lkLmNvbS9hcGsvcmVzL2FuZHJvaWQiPgogICAgPGl0ZW0gYW5kcm9pZDpkcmF3YWJsZT0iP2FuZHJvaWQ6Y29sb3JCYWNrZ3JvdW5kIiAvPgoKICAgIDwhLS0gWW91IGNhbiBpbnNlcnQgeW91ciBvd24gaW1hZ2UgYXNzZXRzIGhlcmUgLS0+CiAgICA8IS0tIDxpdGVtPgogICAgICAgIDxiaXRtYXAKICAgICAgICAgICAgYW5kcm9pZDpncmF2aXR5PSJjZW50ZXIiCiAgICAgICAgICAgIGFuZHJvaWQ6c3JjPSJAbWlwbWFwL2xhdW5jaF9pbWFnZSIgLz4KICAgIDwvaXRlbT4gLS0+CjwvbGF5ZXItbGlzdD4K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/drawable/launch_background.xml",
      "data":
          "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBNb2RpZnkgdGhpcyBmaWxlIHRvIGN1c3RvbWl6ZSB5b3VyIGxhdW5jaCBzcGxhc2ggc2NyZWVuIC0tPgo8bGF5ZXItbGlzdCB4bWxuczphbmRyb2lkPSJodHRwOi8vc2NoZW1hcy5hbmRyb2lkLmNvbS9hcGsvcmVzL2FuZHJvaWQiPgogICAgPGl0ZW0gYW5kcm9pZDpkcmF3YWJsZT0iQGFuZHJvaWQ6Y29sb3Ivd2hpdGUiIC8+CgogICAgPCEtLSBZb3UgY2FuIGluc2VydCB5b3VyIG93biBpbWFnZSBhc3NldHMgaGVyZSAtLT4KICAgIDwhLS0gPGl0ZW0+CiAgICAgICAgPGJpdG1hcAogICAgICAgICAgICBhbmRyb2lkOmdyYXZpdHk9ImNlbnRlciIKICAgICAgICAgICAgYW5kcm9pZDpzcmM9IkBtaXBtYXAvbGF1bmNoX2ltYWdlIiAvPgogICAgPC9pdGVtPiAtLT4KPC9sYXllci1saXN0Pgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/mipmap-hdpi/ic_launcher.png",
      "data":
          "iVBORw0KGgoAAAANSUhEUgAAAEgAAABICAMAAABiM0N1AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAK5QTFRFAAAAAU6KAVebKbb2VMX4Kbb2VMX4AVaaAVebKbb2RsD3VMX4VMX4AVaZAVebGHalKbb2VMX4Pa7jADJZADhkAStLATBTAT5uAT5vAUd/AUmCAUyHAU6KAU6LAU6MAVGRAVKSAVKTAVOUAVWXAVWYAVaYAVaaAVeaAVebAjtnAkBwAkN2AkmAA02GA0+KA1CLFmiQF2+ZGXimGn6wG4O2G4a6HIe8Kbb2RL/3VMX47aEaPQAAABN0Uk5TABAQEBBQUGBgYGBggM/Pz8/P3xkQ5PoAAADpSURBVFjD7czXDoJAEEBRVOy9YO+KjB0r+v8/ZoQIC0sizq4PxrmvNzmKQklMrd758uSQQw455JBDDjnvnFSBL4Vw8iGzqn7TCYUwTpiEc3gJ6wQlvOOXXCf3ucNKrpO1bp87nsQ4FidFcF6SzwlKkRxHCjh+KaLzlDiHlSI7TJ7jSaLOSxJ3HEmG85QwTtLiqyEcJVHhnOs+rciQLjsdMhKk83ZmgATptBnrCxCXjuvB1IYEpcOyM5zMbEhIMpvtTn+sAwhKplZv9aYGgKBkao3uHNhwUnk1gmAoKVYEkCPFSyT9qvSvPQCNJCMEO265wAAAAABJRU5ErkJggg==",
      "type": "binary"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/mipmap-mdpi/ic_launcher.png",
      "data":
          "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAIpQTFRFAAAAAVebVMX4Kbb2VMX4AVebKbb2VMX4VMX4Kbb2VMX4VMX4VMX4AVebB1ePVMX4AVebBENyKbb2UcT4VMX4ADxrAUJ1AU2KAU6LAVSVAVSWAVWXAVaZAVaaAVeaAVebAy1LAzFRBUJuBU2ABlOJHom6H43AIZXLIprSIpzVKbb2Mbn2UcT4VMX4UU+PBQAAABV0Uk5TABAQICAwMDCPn5+vv8/Pz+/v7+/vb7KPEwAAAKVJREFUSMft1MkSgjAQRdGIA86igoKirSIOiP//ew6J3WwMnYULU3nL1LnVuwhh9/zwTpt4zjvv/G99d0gbePW+X3kJfd0Bjq8WPE8F138K6Xu3stbLQvmiwOK7fxXosdB5IVrkVaH3csq/CyP/LOYM35xRcB03GJ92B4vLMR2ZFOcs2YJBcTrEqw3wi3y/WK4B2EW+i+IUgF9ME8CxinYAVhR/sgfbkVbaxFzJpwAAAABJRU5ErkJggg==",
      "type": "binary"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png",
      "data":
          "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAMAAADVRocKAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAPZQTFRFAAAAVMX4Kbb2AUiAAVebKbb2VMX4VMX4AVebVMX4DVmPVMX4VMX4Kbb2R8H3VMX4VMX4AVOUAVebFmyWKbb2VMX4AC1PAC5SAC9UADBUAD5uASlGASpKATZeATdiAThkATtpAT9wAUByAUF0AUV7AUZ9AUd+AUd/AUh/AUmDAUqEAUyHAUyIAU2IAU2JAU6KAU+OAVCPAVKRAVKTAVOTAVOUAVSVAVWXAVaYAVaZAVaaAVeaAVebAjNYAjplAj9uAkN2Akd7A0l+A0qBA0uCFmiPF2uUGHKeGXinGn2uGoGzG4O2G4W4G4a6HYrAKbb2RL/3VMX4cbCtoAAAABZ0Uk5TABAgMDAwMFBgYHBwgJ+fn8/v7+/v77sEZREAAAFPSURBVGje7dnXTsNAEIXhQCih92p6bwFMYoLjpWMSauD9XwbLRJbX3olkawYJOOd69X+a6y0UsN+6vplPcgPoo48++uijjz766KOPPvroo//f+kPD5Po5+mP0u/Guv9vvBLD0OwhMfVJg6xMCY98osPYNAnM/JWj9UYZ+QtD6I60Phr4mJPotSsjUjwmpPiFk7EeCoW8UMvfbgrFvEHL0Q4Hop4Rc/UAg+wkhZ1+f3tcEkX5MEOpHgli/LQj2Q0G0Hwgs/e5pEngfZPmK6KWEtwenJCm83lc8JSi83J25npITnm/tWj0ApISnmxPnIgRkhOb1ge18XyAiNK62ygHg1pWM8Hi5vntkVyOAW/CXVjZ3Dk8rNU8pCcG35lY3tstVV8XGKPjW7MLa/rlKjE3wrfnFY2UYkzC1vOcp83iE4gTV5xJ6JhUECBB+TMDY9gVhhwZ2u52HDgAAAABJRU5ErkJggg==",
      "type": "binary"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png",
      "data":
          "iVBORw0KGgoAAAANSUhEUgAAAJAAAACQCAMAAADQmBKKAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAVNQTFRFAAAAKbb2VMX4VMX4VMX4Kbb2AVKTAVebCUhwKbb2VMX4GXCiKbb2Orz3VMX4AChHACtNACxPAC5SAC9TAC9UADBWADNcADtoAD9vATFXATVfATZgATdiATpnATtpATxrATxsAT1sAT1tAT5uAT9xAUFzAUF0AUJ1AUN4AUR6AUV7AUZ8AUZ9AUZ+AUd+AUiAAUiBAUmBAUmCAUmDAUmEAUqDAUqEAUyHAUyIAU2IAU2JAU6LAU6MAU+MAU+NAVCOAVGPAVGQAVGRAVGSAVKRAVKSAVKTAVOTAVOUAVSVAVSWAVWXAVWYAVaYAVaZAVaaAVeaAVebBzZTCDtaCUFjCUZrCkpyCk54C1F9C1SBC1aEC1eHC1mJC1qKC1qMDFuMJKDZJKHZJaLcJaTeJaXgJqfhJqjjJqnkJqnlJqrmJqvmJqvnJ6vnJ6voKbb2Obz3VMX4m8WQNQAAAA90Uk5TABAQQGCAn5+fn5+/z8/PrpHT6gAAAi9JREFUeNrt0GdTU1EUheEoCghWFEVCs1AMGpQSQoSERMDATTuxgD3YaBL4/59IMZKEc+/dM1z2Pg7r/b5mnlk+H0IG1nFIrQMeeOCBBx544IEHHnjggQceeOCBBx544IEHHnjggQceeOCBBx544IEHHnj+M8/FFnI8nuvk+SV44Dl7Dx3E5CGL2DxEEaOHJGL1EETMHlcRu8dFJOBxFIl4HERCHluRmMdGpPNcuMbi0Yq0nqvFAxaPRmTjKRJFp/WcENl6aKLTe5pEDh6KyAtPg8jR4y7yxlMncvG4ibzy/BO5epxF3nn+iggeJ5GXnoqI5LEXeespiYgeO5HXHm1aj14k6dGJZD0nRdKeZpG8p1FkgqdeZIbnWGSKpyYyx1MVmeQpi1g8vstET3G/08fTFZrnz7dQq0miva/Ty+k2c0R7X6ZfpXPKGNHu58lEKqeUKaKdT88XrWzOGNH2x2B0NVMFmSDa+hB4uWJlstkKSF70e2MsHE9a6RpIWvRrfTgUXaoHyYp+vn8UnIstN4AkRT/e9Y/NRGJLybV05hgkJ/r+1v94PBSJJqogcdHmm/sDo09nItH461Wr/iEhUSF/s3dodHxqdqEESmVVQwKiQv7Gnb4HI4HJ2fnEWhNHQlTy3OruGxwOTMVSShezqOzp6vY/fBFXdrGKKp7bPWHlFKOo7Lk3YSmX2ESF/N0nSUWIS9T+bCWjlEmiVqKHT9SmIIIIIoggggii8yRC56kjnvQNYJm/1ucAAAAASUVORK5CYII=",
      "type": "binary"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png",
      "data":
          "iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAMAAABlApw1AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAdpQTFRFAAAAVMX4VMX4AUN3AVGRAVaaAVebKbb2VMX4FmOXVMX4VMX4Kbb2AUuGAUuHAVWXAVebFmyWKbb2LLf2VMX4AClIACxOACxPAC1QAC5RAC5SAC9TAC9UADBWADFWADFXADNaADVeADZgADdgADtpADxsASZCASZDASpJATFXATRbATRcATRdATVfATZgAThjAThkATlmATpnATpoATtpATxqAT1sAT1tAT5tAT5uAT5vAT9vAT9wAUByAUFzAUF0AUJ1AUJ2AUR5AUR6AUV6AUV7AUZ8AUd+AUd/AUiAAUiBAUmCAUmDAUqDAUqEAUqFAUuEAUuFAUuGAUuHAUyHAUyIAUyJAU2IAU2JAU2KAU6KAU6LAU6MAU+MAU+NAVCOAVCPAVCQAVGPAVGQAVGRAVKRAVKSAVOSAVOTAVOUAVOVAVSUAVSVAVSWAVWWAVWXAVWYAVWZAVaYAVaZAVaaAVeaAVebAi5PAjFWAjRbAjdgAjpkAjxoAj5rAkBuAkFxAkJzAkN1AkR2AkV4AkZ5AkZ6Akd6FmiPFmmQF22WF3CbGHOfGXajGXmnGXuqGn2tGn+wGoCyG4K0G4O2G4S3G4W4G4W5G4a6HIa7H4vAKbb2LLf2TML4VMX4KQGaCAAAABV0Uk5TABAgMDAwMDAwQEDP3+/v7+/v7+/v7Yl3rQAAAz5JREFUeNrt1AdTE1EUhmFEQKygYi9YsTewYcOAEBBRg6KIkASBmKhhkazXLnbsvUb8r2bNMASy2b33zmzmnJnv+wF7nnd2dgsKMAzL60or/uqtohR++OGHH3744Ycffvjhhx9++OGHH3744Ycffvjhhx9++OGHH3744Ycffvjhhx9++OGHH3744Ycffvjhhx9++OGHH3744Ycffvjhhx9++Gn7C2dprpCGX/uhs6fBDz/88HPxa9+i4te9Rsevd4+SX+ciLb/6TWp+1av0/Gp3KfpVLtP0y9+m6pe9Ttcvd5+yX0ZA2+9uoO53U9D3Ozuc/DMWjpHwOxU4+hck/4yR8OcucPEntQo88OcqcPXrFHjity+Q8KsXeOS3K5DyqxZ45s8ukPSrFXjon1og7Vcp8NQ/uUDBL1/gsT+zQMkvW+C5f6JA0S9XkAf/eIGyX6YgL/50gYbfvSBPfqtAy+9WkDd/qkDP71yQR7/THP1OBTz8uQu4+HMV8PHbF3Dy2xXw8mcXcPNPLeDnn1zA0Z9ZwNM/UcDVP17A158u4Oy3Coj4C+Yk9fZ7Jg2/7hv49XJuEeeCny/a+8qK+RZY/kGzvIRrwY/n7b3xhBBcC74/O5vy3xJcC749bQvFb5pWAMuCr09ag9eHzHQAw4Ivj1u6o0YiFcCz4POIv6s/PjwRwKzg06OmjiuxwcwAVgUfH9YHgpGYYWQGMCr48MDX2hWOxuLGsDn+FXMqeH//qP9cT+/VrAAmBe/uHWw4dSHYF8kOYFHw9u5eX/OZzmA4ErthTPqKeRS8ubPrSENLoLMnPGAXQL7g9e3t++oaTwY6u8MDUbsA4gWvNm/ZXetrbDl9sTvUH72W/o8KwaZgdNOSbdWHrICOy6E+6z9qiuzRLRitWrRyR83h4yea285bAUZC2I5qQcq/ePXOmtq6Bn8qIDIkco5mgeVfVrmu+sCxen9X1BROo1jw37+8cu2e/c2hhHAbvYK0f8WqDW1DQmbUCtL+9U0RITtaBZZ/jU9eT61gtGrpxkumUBydgvlbG/sNZT+hgunztPyECorKtPyECorLBfOCEhSgAAUoQAEKUIACFKAABShAAZkCDKO1f/OiyBBYvwCtAAAAAElFTkSuQmCC",
      "type": "binary"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/values-night/styles.xml",
      "data":
          "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPHJlc291cmNlcz4KICAgIDwhLS0gVGhlbWUgYXBwbGllZCB0byB0aGUgQW5kcm9pZCBXaW5kb3cgd2hpbGUgdGhlIHByb2Nlc3MgaXMgc3RhcnRpbmcgd2hlbiB0aGUgT1MncyBEYXJrIE1vZGUgc2V0dGluZyBpcyBvbiAtLT4KICAgIDxzdHlsZSBuYW1lPSJMYXVuY2hUaGVtZSIgcGFyZW50PSJAYW5kcm9pZDpzdHlsZS9UaGVtZS5CbGFjay5Ob1RpdGxlQmFyIj4KICAgICAgICA8IS0tIFNob3cgYSBzcGxhc2ggc2NyZWVuIG9uIHRoZSBhY3Rpdml0eS4gQXV0b21hdGljYWxseSByZW1vdmVkIHdoZW4KICAgICAgICAgICAgIHRoZSBGbHV0dGVyIGVuZ2luZSBkcmF3cyBpdHMgZmlyc3QgZnJhbWUgLS0+CiAgICAgICAgPGl0ZW0gbmFtZT0iYW5kcm9pZDp3aW5kb3dCYWNrZ3JvdW5kIj5AZHJhd2FibGUvbGF1bmNoX2JhY2tncm91bmQ8L2l0ZW0+CiAgICA8L3N0eWxlPgogICAgPCEtLSBUaGVtZSBhcHBsaWVkIHRvIHRoZSBBbmRyb2lkIFdpbmRvdyBhcyBzb29uIGFzIHRoZSBwcm9jZXNzIGhhcyBzdGFydGVkLgogICAgICAgICBUaGlzIHRoZW1lIGRldGVybWluZXMgdGhlIGNvbG9yIG9mIHRoZSBBbmRyb2lkIFdpbmRvdyB3aGlsZSB5b3VyCiAgICAgICAgIEZsdXR0ZXIgVUkgaW5pdGlhbGl6ZXMsIGFzIHdlbGwgYXMgYmVoaW5kIHlvdXIgRmx1dHRlciBVSSB3aGlsZSBpdHMKICAgICAgICAgcnVubmluZy4KCiAgICAgICAgIFRoaXMgVGhlbWUgaXMgb25seSB1c2VkIHN0YXJ0aW5nIHdpdGggVjIgb2YgRmx1dHRlcidzIEFuZHJvaWQgZW1iZWRkaW5nLiAtLT4KICAgIDxzdHlsZSBuYW1lPSJOb3JtYWxUaGVtZSIgcGFyZW50PSJAYW5kcm9pZDpzdHlsZS9UaGVtZS5CbGFjay5Ob1RpdGxlQmFyIj4KICAgICAgICA8aXRlbSBuYW1lPSJhbmRyb2lkOndpbmRvd0JhY2tncm91bmQiPj9hbmRyb2lkOmNvbG9yQmFja2dyb3VuZDwvaXRlbT4KICAgIDwvc3R5bGU+CjwvcmVzb3VyY2VzPgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/main/res/values/styles.xml",
      "data":
          "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPHJlc291cmNlcz4KICAgIDwhLS0gVGhlbWUgYXBwbGllZCB0byB0aGUgQW5kcm9pZCBXaW5kb3cgd2hpbGUgdGhlIHByb2Nlc3MgaXMgc3RhcnRpbmcgd2hlbiB0aGUgT1MncyBEYXJrIE1vZGUgc2V0dGluZyBpcyBvZmYgLS0+CiAgICA8c3R5bGUgbmFtZT0iTGF1bmNoVGhlbWUiIHBhcmVudD0iQGFuZHJvaWQ6c3R5bGUvVGhlbWUuTGlnaHQuTm9UaXRsZUJhciI+CiAgICAgICAgPCEtLSBTaG93IGEgc3BsYXNoIHNjcmVlbiBvbiB0aGUgYWN0aXZpdHkuIEF1dG9tYXRpY2FsbHkgcmVtb3ZlZCB3aGVuCiAgICAgICAgICAgICB0aGUgRmx1dHRlciBlbmdpbmUgZHJhd3MgaXRzIGZpcnN0IGZyYW1lIC0tPgogICAgICAgIDxpdGVtIG5hbWU9ImFuZHJvaWQ6d2luZG93QmFja2dyb3VuZCI+QGRyYXdhYmxlL2xhdW5jaF9iYWNrZ3JvdW5kPC9pdGVtPgogICAgPC9zdHlsZT4KICAgIDwhLS0gVGhlbWUgYXBwbGllZCB0byB0aGUgQW5kcm9pZCBXaW5kb3cgYXMgc29vbiBhcyB0aGUgcHJvY2VzcyBoYXMgc3RhcnRlZC4KICAgICAgICAgVGhpcyB0aGVtZSBkZXRlcm1pbmVzIHRoZSBjb2xvciBvZiB0aGUgQW5kcm9pZCBXaW5kb3cgd2hpbGUgeW91cgogICAgICAgICBGbHV0dGVyIFVJIGluaXRpYWxpemVzLCBhcyB3ZWxsIGFzIGJlaGluZCB5b3VyIEZsdXR0ZXIgVUkgd2hpbGUgaXRzCiAgICAgICAgIHJ1bm5pbmcuCgogICAgICAgICBUaGlzIFRoZW1lIGlzIG9ubHkgdXNlZCBzdGFydGluZyB3aXRoIFYyIG9mIEZsdXR0ZXIncyBBbmRyb2lkIGVtYmVkZGluZy4gLS0+CiAgICA8c3R5bGUgbmFtZT0iTm9ybWFsVGhlbWUiIHBhcmVudD0iQGFuZHJvaWQ6c3R5bGUvVGhlbWUuTGlnaHQuTm9UaXRsZUJhciI+CiAgICAgICAgPGl0ZW0gbmFtZT0iYW5kcm9pZDp3aW5kb3dCYWNrZ3JvdW5kIj4/YW5kcm9pZDpjb2xvckJhY2tncm91bmQ8L2l0ZW0+CiAgICA8L3N0eWxlPgo8L3Jlc291cmNlcz4K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/app/src/profile/AndroidManifest.xml",
      "data":
          "PG1hbmlmZXN0IHhtbG5zOmFuZHJvaWQ9Imh0dHA6Ly9zY2hlbWFzLmFuZHJvaWQuY29tL2Fway9yZXMvYW5kcm9pZCIKICAgIHBhY2thZ2U9Int7b3JnX25hbWV9fS57e3Byb2plY3RfbmFtZX19Ij4KICAgIDwhLS0gVGhlIElOVEVSTkVUIHBlcm1pc3Npb24gaXMgcmVxdWlyZWQgZm9yIGRldmVsb3BtZW50LiBTcGVjaWZpY2FsbHksCiAgICAgICAgIHRoZSBGbHV0dGVyIHRvb2wgbmVlZHMgaXQgdG8gY29tbXVuaWNhdGUgd2l0aCB0aGUgcnVubmluZyBhcHBsaWNhdGlvbgogICAgICAgICB0byBhbGxvdyBzZXR0aW5nIGJyZWFrcG9pbnRzLCB0byBwcm92aWRlIGhvdCByZWxvYWQsIGV0Yy4KICAgIC0tPgogICAgPHVzZXMtcGVybWlzc2lvbiBhbmRyb2lkOm5hbWU9ImFuZHJvaWQucGVybWlzc2lvbi5JTlRFUk5FVCIvPgo8L21hbmlmZXN0Pgo=",
      "type": "text"
    },
    {
      "path": "packages/{{project_name}}/{{project_name}}/android/build.gradle",
      "data":
          "YnVpbGRzY3JpcHQgewogICAgZXh0LmtvdGxpbl92ZXJzaW9uID0gJzEuNi4xMCcKICAgIHJlcG9zaXRvcmllcyB7CiAgICAgICAgZ29vZ2xlKCkKICAgICAgICBtYXZlbkNlbnRyYWwoKQogICAgfQoKICAgIGRlcGVuZGVuY2llcyB7CiAgICAgICAgY2xhc3NwYXRoICdjb20uYW5kcm9pZC50b29scy5idWlsZDpncmFkbGU6Ny4xLjInCiAgICAgICAgY2xhc3NwYXRoICJvcmcuamV0YnJhaW5zLmtvdGxpbjprb3RsaW4tZ3JhZGxlLXBsdWdpbjoka290bGluX3ZlcnNpb24iCiAgICB9Cn0KCmFsbHByb2plY3RzIHsKICAgIHJlcG9zaXRvcmllcyB7CiAgICAgICAgZ29vZ2xlKCkKICAgICAgICBtYXZlbkNlbnRyYWwoKQogICAgfQp9Cgpyb290UHJvamVjdC5idWlsZERpciA9ICcuLi9idWlsZCcKc3VicHJvamVjdHMgewogICAgcHJvamVjdC5idWlsZERpciA9ICIke3Jvb3RQcm9qZWN0LmJ1aWxkRGlyfS8ke3Byb2plY3QubmFtZX0iCn0Kc3VicHJvamVjdHMgewogICAgcHJvamVjdC5ldmFsdWF0aW9uRGVwZW5kc09uKCc6YXBwJykKfQoKdGFzayBjbGVhbih0eXBlOiBEZWxldGUpIHsKICAgIGRlbGV0ZSByb290UHJvamVjdC5idWlsZERpcgp9Cg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/gradle.properties",
      "data":
          "b3JnLmdyYWRsZS5qdm1hcmdzPS1YbXgxNTM2TQphbmRyb2lkLnVzZUFuZHJvaWRYPXRydWUKYW5kcm9pZC5lbmFibGVKZXRpZmllcj10cnVlCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/gradle/wrapper/gradle-wrapper.properties",
      "data":
          "ZGlzdHJpYnV0aW9uQmFzZT1HUkFETEVfVVNFUl9IT01FCmRpc3RyaWJ1dGlvblBhdGg9d3JhcHBlci9kaXN0cwp6aXBTdG9yZUJhc2U9R1JBRExFX1VTRVJfSE9NRQp6aXBTdG9yZVBhdGg9d3JhcHBlci9kaXN0cwpkaXN0cmlidXRpb25Vcmw9aHR0cHNcOi8vc2VydmljZXMuZ3JhZGxlLm9yZy9kaXN0cmlidXRpb25zL2dyYWRsZS03LjQtYWxsLnppcAo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}/android/settings.gradle",
      "data":
          "aW5jbHVkZSAnOmFwcCcKCmRlZiBsb2NhbFByb3BlcnRpZXNGaWxlID0gbmV3IEZpbGUocm9vdFByb2plY3QucHJvamVjdERpciwgImxvY2FsLnByb3BlcnRpZXMiKQpkZWYgcHJvcGVydGllcyA9IG5ldyBQcm9wZXJ0aWVzKCkKCmFzc2VydCBsb2NhbFByb3BlcnRpZXNGaWxlLmV4aXN0cygpCmxvY2FsUHJvcGVydGllc0ZpbGUud2l0aFJlYWRlcigiVVRGLTgiKSB7IHJlYWRlciAtPiBwcm9wZXJ0aWVzLmxvYWQocmVhZGVyKSB9CgpkZWYgZmx1dHRlclNka1BhdGggPSBwcm9wZXJ0aWVzLmdldFByb3BlcnR5KCJmbHV0dGVyLnNkayIpCmFzc2VydCBmbHV0dGVyU2RrUGF0aCAhPSBudWxsLCAiZmx1dHRlci5zZGsgbm90IHNldCBpbiBsb2NhbC5wcm9wZXJ0aWVzIgphcHBseSBmcm9tOiAiJGZsdXR0ZXJTZGtQYXRoL3BhY2thZ2VzL2ZsdXR0ZXJfdG9vbHMvZ3JhZGxlL2FwcF9wbHVnaW5fbG9hZGVyLmdyYWRsZSIK",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/.gitignore",
      "data":
          "IyBNaXNjZWxsYW5lb3VzCiouY2xhc3MKKi5sb2cKKi5weWMKKi5zd3AKLkRTX1N0b3JlCi5hdG9tLwouYnVpbGRsb2cvCi5oaXN0b3J5Ci5zdm4vCm1pZ3JhdGVfd29ya2luZ19kaXIvCgojIEludGVsbGlKIHJlbGF0ZWQKKi5pbWwKKi5pcHIKKi5pd3MKLmlkZWEvCgojIFRoZSAudnNjb2RlIGZvbGRlciBjb250YWlucyBsYXVuY2ggY29uZmlndXJhdGlvbiBhbmQgdGFza3MgeW91IGNvbmZpZ3VyZSBpbgojIFZTIENvZGUgd2hpY2ggeW91IG1heSB3aXNoIHRvIGJlIGluY2x1ZGVkIGluIHZlcnNpb24gY29udHJvbCwgc28gdGhpcyBsaW5lCiMgaXMgY29tbWVudGVkIG91dCBieSBkZWZhdWx0LgojLnZzY29kZS8KCiMgRmx1dHRlci9EYXJ0L1B1YiByZWxhdGVkCiMgTGlicmFyaWVzIHNob3VsZCBub3QgaW5jbHVkZSBwdWJzcGVjLmxvY2ssIHBlciBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9saWJyYXJpZXMvcHJpdmF0ZS1maWxlcyNwdWJzcGVjbG9jay4KL3B1YnNwZWMubG9jawoqKi9kb2MvYXBpLwouZGFydF90b29sLwoucGFja2FnZXMKYnVpbGQvCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/analysis_options.yaml",
      "data":
          "aW5jbHVkZTogcGFja2FnZTpmbHV0dGVyX2xpbnRzL2ZsdXR0ZXIueWFtbAoKIyBBZGRpdGlvbmFsIGluZm9ybWF0aW9uIGFib3V0IHRoaXMgZmlsZSBjYW4gYmUgZm91bmQgYXQKIyBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9sYW5ndWFnZS9hbmFseXNpcy1vcHRpb25zCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/CHANGELOG.md",
      "data": "IyMgMC4wLjEKCiogVE9ETzogRGVzY3JpYmUgaW5pdGlhbCByZWxlYXNlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/lib/src/presentation/app.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9ob21lX3BhZ2Uve3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZS5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9yb3V0aW5nL3t7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9yb3V0aW5nLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6e3twcm9qZWN0X25hbWV9fV91aV9hbmRyb2lkL3t7cHJvamVjdF9uYW1lfX1fdWlfYW5kcm9pZC5kYXJ0JzsKCmNsYXNzIEFwcCBleHRlbmRzIFN0YXRlbGVzc1dpZGdldCB7CiAgZmluYWwgTGlzdDxOYXZpZ2F0b3JPYnNlcnZlcj4gRnVuY3Rpb24oKT8gbmF2aWdhdG9yT2JzZXJ2ZXJCdWlsZGVyOwoKICBjb25zdCBBcHAoewogICAgc3VwZXIua2V5LAogICAgdGhpcy5uYXZpZ2F0b3JPYnNlcnZlckJ1aWxkZXIsCiAgfSk7CgogIEBvdmVycmlkZQogIFdpZGdldCBidWlsZChCdWlsZENvbnRleHQgY29udGV4dCkgewogICAgZmluYWwgcm91dGVyID0gUm91dGVyKCk7CgogICAgcmV0dXJuIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QXBwKAogICAgICBsb2NhbGl6YXRpb25zRGVsZWdhdGVzOiBjb25zdCB7CiAgICAgICAge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zLmRlbGVnYXRlLAogICAgICB9LAogICAgICBzdXBwb3J0ZWRMb2NhbGVzOiBjb25zdCBbCiAgICAgICAgTG9jYWxlKCdlbicpLAogICAgICBdLAogICAgICByb3V0ZUluZm9ybWF0aW9uUGFyc2VyOiByb3V0ZXIuZGVmYXVsdFJvdXRlUGFyc2VyKCksCiAgICAgIHJvdXRlckRlbGVnYXRlOiByb3V0ZXIuZGVsZWdhdGUoCiAgICAgICAgbmF2aWdhdG9yT2JzZXJ2ZXJzOiBuYXZpZ2F0b3JPYnNlcnZlckJ1aWxkZXIgPz8gKCkgPT4gW10sCiAgICAgICksCiAgICApOwogIH0KfQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/lib/{{project_name}}_android_app.dart",
      "data":
          "Ly8gVE9ETzogZG9jCmxpYnJhcnkge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2FwcDsKCmV4cG9ydCAnc3JjL3ByZXNlbnRhdGlvbi9hcHAuZGFydCc7Cg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/LICENSE",
      "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/pubspec.yaml",
      "data":
          "bmFtZToge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2FwcApkZXNjcmlwdGlvbjogQSBuZXcgRmx1dHRlciBwYWNrYWdlIHByb2plY3QuCnZlcnNpb246IDAuMC4xCgplbnZpcm9ubWVudDoKICBzZGs6ICI+PTIuMTguNiA8My4wLjAiCiAgZmx1dHRlcjogIj49MS4xNy4wIgoKZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXI6CiAgICBzZGs6IGZsdXR0ZXIKICB7e3Byb2plY3RfbmFtZX19X3VpX2FuZHJvaWQ6CiAge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX3JvdXRpbmc6CiAge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZToKCmRldl9kZXBlbmRlbmNpZXM6CiAgZmx1dHRlcl90ZXN0OgogICAgc2RrOiBmbHV0dGVyCiAgZmx1dHRlcl9saW50czogXjIuMC4xCgojIEZvciBpbmZvcm1hdGlvbiBvbiB0aGUgZ2VuZXJpYyBEYXJ0IHBhcnQgb2YgdGhpcyBmaWxlLCBzZWUgdGhlCiMgZm9sbG93aW5nIHBhZ2U6IGh0dHBzOi8vZGFydC5kZXYvdG9vbHMvcHViL3B1YnNwZWMKCiMgVGhlIGZvbGxvd2luZyBzZWN0aW9uIGlzIHNwZWNpZmljIHRvIEZsdXR0ZXIgcGFja2FnZXMuCmZsdXR0ZXI6CgogICMgVG8gYWRkIGFzc2V0cyB0byB5b3VyIHBhY2thZ2UsIGFkZCBhbiBhc3NldHMgc2VjdGlvbiwgbGlrZSB0aGlzOgogICMgYXNzZXRzOgogICMgICAtIGltYWdlcy9hX2RvdF9idXJyLmpwZWcKICAjICAgLSBpbWFnZXMvYV9kb3RfaGFtLmpwZWcKICAjCiAgIyBGb3IgZGV0YWlscyByZWdhcmRpbmcgYXNzZXRzIGluIHBhY2thZ2VzLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvYXNzZXRzLWFuZC1pbWFnZXMvI2Zyb20tcGFja2FnZXMKICAjCiAgIyBBbiBpbWFnZSBhc3NldCBjYW4gcmVmZXIgdG8gb25lIG9yIG1vcmUgcmVzb2x1dGlvbi1zcGVjaWZpYyAidmFyaWFudHMiLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvYXNzZXRzLWFuZC1pbWFnZXMvI3Jlc29sdXRpb24tYXdhcmUKCiAgIyBUbyBhZGQgY3VzdG9tIGZvbnRzIHRvIHlvdXIgcGFja2FnZSwgYWRkIGEgZm9udHMgc2VjdGlvbiBoZXJlLAogICMgaW4gdGhpcyAiZmx1dHRlciIgc2VjdGlvbi4gRWFjaCBlbnRyeSBpbiB0aGlzIGxpc3Qgc2hvdWxkIGhhdmUgYQogICMgImZhbWlseSIga2V5IHdpdGggdGhlIGZvbnQgZmFtaWx5IG5hbWUsIGFuZCBhICJmb250cyIga2V5IHdpdGggYQogICMgbGlzdCBnaXZpbmcgdGhlIGFzc2V0IGFuZCBvdGhlciBkZXNjcmlwdG9ycyBmb3IgdGhlIGZvbnQuIEZvcgogICMgZXhhbXBsZToKICAjIGZvbnRzOgogICMgICAtIGZhbWlseTogU2NoeWxlcgogICMgICAgIGZvbnRzOgogICMgICAgICAgLSBhc3NldDogZm9udHMvU2NoeWxlci1SZWd1bGFyLnR0ZgogICMgICAgICAgLSBhc3NldDogZm9udHMvU2NoeWxlci1JdGFsaWMudHRmCiAgIyAgICAgICAgIHN0eWxlOiBpdGFsaWMKICAjICAgLSBmYW1pbHk6IFRyYWphbiBQcm8KICAjICAgICBmb250czoKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1RyYWphblByby50dGYKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1RyYWphblByb19Cb2xkLnR0ZgogICMgICAgICAgICB3ZWlnaHQ6IDcwMAogICMKICAjIEZvciBkZXRhaWxzIHJlZ2FyZGluZyBmb250cyBpbiBwYWNrYWdlcywgc2VlCiAgIyBodHRwczovL2ZsdXR0ZXIuZGV2L2N1c3RvbS1mb250cy8jZnJvbS1wYWNrYWdlcwo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_app/README.md",
      "data":
          "PCEtLQpUaGlzIFJFQURNRSBkZXNjcmliZXMgdGhlIHBhY2thZ2UuIElmIHlvdSBwdWJsaXNoIHRoaXMgcGFja2FnZSB0byBwdWIuZGV2LAp0aGlzIFJFQURNRSdzIGNvbnRlbnRzIGFwcGVhciBvbiB0aGUgbGFuZGluZyBwYWdlIGZvciB5b3VyIHBhY2thZ2UuCgpGb3IgaW5mb3JtYXRpb24gYWJvdXQgaG93IHRvIHdyaXRlIGEgZ29vZCBwYWNrYWdlIFJFQURNRSwgc2VlIHRoZSBndWlkZSBmb3IKW3dyaXRpbmcgcGFja2FnZSBwYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL3dyaXRpbmctcGFja2FnZS1wYWdlcykuCgpGb3IgZ2VuZXJhbCBpbmZvcm1hdGlvbiBhYm91dCBkZXZlbG9waW5nIHBhY2thZ2VzLCBzZWUgdGhlIERhcnQgZ3VpZGUgZm9yCltjcmVhdGluZyBwYWNrYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL2NyZWF0ZS1saWJyYXJ5LXBhY2thZ2VzKQphbmQgdGhlIEZsdXR0ZXIgZ3VpZGUgZm9yCltkZXZlbG9waW5nIHBhY2thZ2VzIGFuZCBwbHVnaW5zXShodHRwczovL2ZsdXR0ZXIuZGV2L2RldmVsb3BpbmctcGFja2FnZXMpLgotLT4KClRPRE86IFB1dCBhIHNob3J0IGRlc2NyaXB0aW9uIG9mIHRoZSBwYWNrYWdlIGhlcmUgdGhhdCBoZWxwcyBwb3RlbnRpYWwgdXNlcnMKa25vdyB3aGV0aGVyIHRoaXMgcGFja2FnZSBtaWdodCBiZSB1c2VmdWwgZm9yIHRoZW0uCgojIyBGZWF0dXJlcwoKVE9ETzogTGlzdCB3aGF0IHlvdXIgcGFja2FnZSBjYW4gZG8uIE1heWJlIGluY2x1ZGUgaW1hZ2VzLCBnaWZzLCBvciB2aWRlb3MuCgojIyBHZXR0aW5nIHN0YXJ0ZWQKClRPRE86IExpc3QgcHJlcmVxdWlzaXRlcyBhbmQgcHJvdmlkZSBvciBwb2ludCB0byBpbmZvcm1hdGlvbiBvbiBob3cgdG8Kc3RhcnQgdXNpbmcgdGhlIHBhY2thZ2UuCgojIyBVc2FnZQoKVE9ETzogSW5jbHVkZSBzaG9ydCBhbmQgdXNlZnVsIGV4YW1wbGVzIGZvciBwYWNrYWdlIHVzZXJzLiBBZGQgbG9uZ2VyIGV4YW1wbGVzCnRvIGAvZXhhbXBsZWAgZm9sZGVyLgoKYGBgZGFydApjb25zdCBsaWtlID0gJ3NhbXBsZSc7CmBgYAoKIyMgQWRkaXRpb25hbCBpbmZvcm1hdGlvbgoKVE9ETzogVGVsbCB1c2VycyBtb3JlIGFib3V0IHRoZSBwYWNrYWdlOiB3aGVyZSB0byBmaW5kIG1vcmUgaW5mb3JtYXRpb24sIGhvdyB0bwpjb250cmlidXRlIHRvIHRoZSBwYWNrYWdlLCBob3cgdG8gZmlsZSBpc3N1ZXMsIHdoYXQgcmVzcG9uc2UgdGhleSBjYW4gZXhwZWN0CmZyb20gdGhlIHBhY2thZ2UgYXV0aG9ycywgYW5kIG1vcmUuCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/.gitignore",
      "data":
          "IyBNaXNjZWxsYW5lb3VzCiouY2xhc3MKKi5sb2cKKi5weWMKKi5zd3AKLkRTX1N0b3JlCi5hdG9tLwouYnVpbGRsb2cvCi5oaXN0b3J5Ci5zdm4vCm1pZ3JhdGVfd29ya2luZ19kaXIvCgojIEludGVsbGlKIHJlbGF0ZWQKKi5pbWwKKi5pcHIKKi5pd3MKLmlkZWEvCgojIFRoZSAudnNjb2RlIGZvbGRlciBjb250YWlucyBsYXVuY2ggY29uZmlndXJhdGlvbiBhbmQgdGFza3MgeW91IGNvbmZpZ3VyZSBpbgojIFZTIENvZGUgd2hpY2ggeW91IG1heSB3aXNoIHRvIGJlIGluY2x1ZGVkIGluIHZlcnNpb24gY29udHJvbCwgc28gdGhpcyBsaW5lCiMgaXMgY29tbWVudGVkIG91dCBieSBkZWZhdWx0LgojLnZzY29kZS8KCiMgRmx1dHRlci9EYXJ0L1B1YiByZWxhdGVkCiMgTGlicmFyaWVzIHNob3VsZCBub3QgaW5jbHVkZSBwdWJzcGVjLmxvY2ssIHBlciBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9saWJyYXJpZXMvcHJpdmF0ZS1maWxlcyNwdWJzcGVjbG9jay4KL3B1YnNwZWMubG9jawoqKi9kb2MvYXBpLwouZGFydF90b29sLwoucGFja2FnZXMKYnVpbGQvCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/analysis_options.yaml",
      "data":
          "aW5jbHVkZTogcGFja2FnZTpmbHV0dGVyX2xpbnRzL2ZsdXR0ZXIueWFtbAoKIyBBZGRpdGlvbmFsIGluZm9ybWF0aW9uIGFib3V0IHRoaXMgZmlsZSBjYW4gYmUgZm91bmQgYXQKIyBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9sYW5ndWFnZS9hbmFseXNpcy1vcHRpb25zCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/CHANGELOG.md",
      "data": "IyMgMC4wLjEKCiogVE9ETzogRGVzY3JpYmUgaW5pdGlhbCByZWxlYXNlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/l10n.yaml",
      "data":
          "YXJiLWRpcjogbGliL3NyYy9wcmVzZW50YXRpb24vbDEwbi9hcmIKb3V0cHV0LWNsYXNzOiB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMKb3V0cHV0LWRpcjogbGliL3NyYy9wcmVzZW50YXRpb24vbDEwbgp0ZW1wbGF0ZS1hcmItZmlsZTogaG9tZV9wYWdlX2VuLmFyYgpvdXRwdXQtbG9jYWxpemF0aW9uLWZpbGU6IHt7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9ob21lX3BhZ2VfbG9jYWxpemF0aW9ucy5kYXJ0Cm51bGxhYmxlLWdldHRlcjogZmFsc2UKc3ludGhldGljLXBhY2thZ2U6IGZhbHNlCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/injection.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmluamVjdGFibGUvaW5qZWN0YWJsZS5kYXJ0JzsKCi8vLyBTZXR1cCBpbmplY3RhYmxlIHBhY2thZ2Ugd2hpY2ggZ2VuZXJhdGVzIGRlcGVuZGVuY3kgaW5qZWN0aW9uIGNvZGUuCi8vLwovLy8gRm9yIG1vcmUgaW5mbyBzZWU6IGh0dHBzOi8vcHViLmRldi9wYWNrYWdlcy9pbmplY3RhYmxlCkBJbmplY3RhYmxlSW5pdC5taWNyb1BhY2thZ2UoKQppbml0TWljcm9QYWNrYWdlKCkge30K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/injection.module.dart",
      "data":
          "Ly9AR2VuZXJhdGVkTWljcm9Nb2R1bGU7e3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VQYWNrYWdlTW9kdWxlO3BhY2thZ2U6am9uYXNfZGF2aWRfYW5kcm9pZF9ob21lX3BhZ2Uvc3JjL2luamVjdGlvbi5tb2R1bGUuZGFydAovLyBHRU5FUkFURUQgQ09ERSAtIERPIE5PVCBNT0RJRlkgQlkgSEFORAovLyBpZ25vcmVfZm9yX2ZpbGU6IG5vX2xlYWRpbmdfdW5kZXJzY29yZXNfZm9yX2xpYnJhcnlfcHJlZml4ZXMKaW1wb3J0ICdkYXJ0OmFzeW5jJyBhcyBfaTI7CgppbXBvcnQgJ3BhY2thZ2U6aW5qZWN0YWJsZS9pbmplY3RhYmxlLmRhcnQnIGFzIF9pMTsKCi8vLyBpZ25vcmVfZm9yX2ZpbGU6IHVubmVjZXNzYXJ5X2xhbWJkYXMKLy8vIGlnbm9yZV9mb3JfZmlsZTogbGluZXNfbG9uZ2VyX3RoYW5fODBfY2hhcnMKY2xhc3Mge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VQYWNrYWdlTW9kdWxlIGV4dGVuZHMgX2kxLk1pY3JvUGFja2FnZU1vZHVsZSB7CiAgLy8vIGluaXRpYWxpemVzIHRoZSByZWdpc3RyYXRpb24gb2YgbWFpbi1zY29wZSBkZXBlbmRlbmNpZXMgaW5zaWRlIG9mIFtHZXRJdF0KICBAb3ZlcnJpZGUKICBfaTIuRnV0dXJlT3I8dm9pZD4gaW5pdChfaTEuR2V0SXRIZWxwZXIgZ2gpIHt9Cn0K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/presentation/home_page.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fdWlfYW5kcm9pZC97e3Byb2plY3RfbmFtZX19X3VpX2FuZHJvaWQuZGFydCc7CgpjbGFzcyBIb21lUGFnZSBleHRlbmRzIFN0YXRlbGVzc1dpZGdldCB7CiAgY29uc3QgSG9tZVBhZ2Uoe3N1cGVyLmtleX0pOwoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpIHsKICAgIGNvbnN0IGJhY2tncm91bmRDb2xvciA9IHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JzLnByaW1hcnk7CgogICAgcmV0dXJuIFNjYWZmb2xkKAogICAgICBiYWNrZ3JvdW5kQ29sb3I6IGJhY2tncm91bmRDb2xvciwKICAgICAgYm9keTogQ2VudGVyKAogICAgICAgIGNoaWxkOiBUZXh0KHRvU3RyaW5nKCkpLAogICAgICApLAogICAgKTsKICB9Cn0K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/presentation/l10n/arb/home_page_en.arb",
      "data":
          "ewogICJAQGxvY2FsZSI6ICJlbiIsCiAgInRpdGxlIjogIlRoZSBsYW5ndWFnZSBpcyBlbmdsaXNoIiwKICAiQHRpdGxlIjogewogICAgImRlc2NyaXB0aW9uIjogIlRpdGxlIHRleHQgc2hvd24gaW4gdGhlIEhvbWUgUGFnZSIKICB9Cn0=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/presentation/l10n/l10n.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvd2lkZ2V0cy5kYXJ0JzsKCmltcG9ydCAne3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZV9sb2NhbGl6YXRpb25zLmRhcnQnOwoKZXh0ZW5zaW9uIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9uc1ggb24gQnVpbGRDb250ZXh0IHsKICAvLy8gVGhlIGwxMG4gb2JqZWN0IHdoaWNoIGhvbGRzIGFsbCBsb2NhbGl6ZWQgc3RyaW5ncy4KICB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMgZ2V0IGwxMG4gPT4KICAgICAge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zLm9mKHRoaXMpOwp9Cg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/presentation/l10n/{{project_name}}_android_home_page_localizations.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmFzeW5jJzsKCmltcG9ydCAncGFja2FnZTpmbHV0dGVyL2ZvdW5kYXRpb24uZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyL3dpZGdldHMuZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyX2xvY2FsaXphdGlvbnMvZmx1dHRlcl9sb2NhbGl6YXRpb25zLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6aW50bC9pbnRsLmRhcnQnIGFzIGludGw7CgppbXBvcnQgJ3t7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9ob21lX3BhZ2VfbG9jYWxpemF0aW9uc19lbi5kYXJ0JzsKCi8vLyBDYWxsZXJzIGNhbiBsb29rdXAgbG9jYWxpemVkIHN0cmluZ3Mgd2l0aCBhbiBpbnN0YW5jZSBvZiB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMKLy8vIHJldHVybmVkIGJ5IGB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMub2YoY29udGV4dClgLgovLy8KLy8vIEFwcGxpY2F0aW9ucyBuZWVkIHRvIGluY2x1ZGUgYHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9ucy5kZWxlZ2F0ZSgpYCBpbiB0aGVpciBhcHAncwovLy8gYGxvY2FsaXphdGlvbkRlbGVnYXRlc2AgbGlzdCwgYW5kIHRoZSBsb2NhbGVzIHRoZXkgc3VwcG9ydCBpbiB0aGUgYXBwJ3MKLy8vIGBzdXBwb3J0ZWRMb2NhbGVzYCBsaXN0LiBGb3IgZXhhbXBsZToKLy8vCi8vLyBgYGBkYXJ0Ci8vLyBpbXBvcnQgJ2wxMG4ve3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZV9sb2NhbGl6YXRpb25zLmRhcnQnOwovLy8KLy8vIHJldHVybiBNYXRlcmlhbEFwcCgKLy8vICAgbG9jYWxpemF0aW9uc0RlbGVnYXRlczoge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zLmxvY2FsaXphdGlvbnNEZWxlZ2F0ZXMsCi8vLyAgIHN1cHBvcnRlZExvY2FsZXM6IHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9ucy5zdXBwb3J0ZWRMb2NhbGVzLAovLy8gICBob21lOiBNeUFwcGxpY2F0aW9uSG9tZSgpLAovLy8gKTsKLy8vIGBgYAovLy8KLy8vICMjIFVwZGF0ZSBwdWJzcGVjLnlhbWwKLy8vCi8vLyBQbGVhc2UgbWFrZSBzdXJlIHRvIHVwZGF0ZSB5b3VyIHB1YnNwZWMueWFtbCB0byBpbmNsdWRlIHRoZSBmb2xsb3dpbmcKLy8vIHBhY2thZ2VzOgovLy8KLy8vIGBgYHlhbWwKLy8vIGRlcGVuZGVuY2llczoKLy8vICAgIyBJbnRlcm5hdGlvbmFsaXphdGlvbiBzdXBwb3J0LgovLy8gICBmbHV0dGVyX2xvY2FsaXphdGlvbnM6Ci8vLyAgICAgc2RrOiBmbHV0dGVyCi8vLyAgIGludGw6IGFueSAjIFVzZSB0aGUgcGlubmVkIHZlcnNpb24gZnJvbSBmbHV0dGVyX2xvY2FsaXphdGlvbnMKLy8vCi8vLyAgICMgUmVzdCBvZiBkZXBlbmRlbmNpZXMKLy8vIGBgYAovLy8KLy8vICMjIGlPUyBBcHBsaWNhdGlvbnMKLy8vCi8vLyBpT1MgYXBwbGljYXRpb25zIGRlZmluZSBrZXkgYXBwbGljYXRpb24gbWV0YWRhdGEsIGluY2x1ZGluZyBzdXBwb3J0ZWQKLy8vIGxvY2FsZXMsIGluIGFuIEluZm8ucGxpc3QgZmlsZSB0aGF0IGlzIGJ1aWx0IGludG8gdGhlIGFwcGxpY2F0aW9uIGJ1bmRsZS4KLy8vIFRvIGNvbmZpZ3VyZSB0aGUgbG9jYWxlcyBzdXBwb3J0ZWQgYnkgeW91ciBhcHAsIHlvdeKAmWxsIG5lZWQgdG8gZWRpdCB0aGlzCi8vLyBmaWxlLgovLy8KLy8vIEZpcnN0LCBvcGVuIHlvdXIgcHJvamVjdOKAmXMgaW9zL1J1bm5lci54Y3dvcmtzcGFjZSBYY29kZSB3b3Jrc3BhY2UgZmlsZS4KLy8vIFRoZW4sIGluIHRoZSBQcm9qZWN0IE5hdmlnYXRvciwgb3BlbiB0aGUgSW5mby5wbGlzdCBmaWxlIHVuZGVyIHRoZSBSdW5uZXIKLy8vIHByb2plY3TigJlzIFJ1bm5lciBmb2xkZXIuCi8vLwovLy8gTmV4dCwgc2VsZWN0IHRoZSBJbmZvcm1hdGlvbiBQcm9wZXJ0eSBMaXN0IGl0ZW0sIHNlbGVjdCBBZGQgSXRlbSBmcm9tIHRoZQovLy8gRWRpdG9yIG1lbnUsIHRoZW4gc2VsZWN0IExvY2FsaXphdGlvbnMgZnJvbSB0aGUgcG9wLXVwIG1lbnUuCi8vLwovLy8gU2VsZWN0IGFuZCBleHBhbmQgdGhlIG5ld2x5LWNyZWF0ZWQgTG9jYWxpemF0aW9ucyBpdGVtIHRoZW4sIGZvciBlYWNoCi8vLyBsb2NhbGUgeW91ciBhcHBsaWNhdGlvbiBzdXBwb3J0cywgYWRkIGEgbmV3IGl0ZW0gYW5kIHNlbGVjdCB0aGUgbG9jYWxlCi8vLyB5b3Ugd2lzaCB0byBhZGQgZnJvbSB0aGUgcG9wLXVwIG1lbnUgaW4gdGhlIFZhbHVlIGZpZWxkLiBUaGlzIGxpc3Qgc2hvdWxkCi8vLyBiZSBjb25zaXN0ZW50IHdpdGggdGhlIGxhbmd1YWdlcyBsaXN0ZWQgaW4gdGhlIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9ucy5zdXBwb3J0ZWRMb2NhbGVzCi8vLyBwcm9wZXJ0eS4KYWJzdHJhY3QgY2xhc3Mge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zIHsKICB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMoU3RyaW5nIGxvY2FsZSkgOiBsb2NhbGVOYW1lID0gaW50bC5JbnRsLmNhbm9uaWNhbGl6ZWRMb2NhbGUobG9jYWxlLnRvU3RyaW5nKCkpOwoKICBmaW5hbCBTdHJpbmcgbG9jYWxlTmFtZTsKCiAgc3RhdGljIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9ucyBvZihCdWlsZENvbnRleHQgY29udGV4dCkgewogICAgcmV0dXJuIExvY2FsaXphdGlvbnMub2Y8e3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zPihjb250ZXh0LCB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMpITsKICB9CgogIHN0YXRpYyBjb25zdCBMb2NhbGl6YXRpb25zRGVsZWdhdGU8e3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zPiBkZWxlZ2F0ZSA9IF97e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnNEZWxlZ2F0ZSgpOwoKICAvLy8gQSBsaXN0IG9mIHRoaXMgbG9jYWxpemF0aW9ucyBkZWxlZ2F0ZSBhbG9uZyB3aXRoIHRoZSBkZWZhdWx0IGxvY2FsaXphdGlvbnMKICAvLy8gZGVsZWdhdGVzLgogIC8vLwogIC8vLyBSZXR1cm5zIGEgbGlzdCBvZiBsb2NhbGl6YXRpb25zIGRlbGVnYXRlcyBjb250YWluaW5nIHRoaXMgZGVsZWdhdGUgYWxvbmcgd2l0aAogIC8vLyBHbG9iYWxNYXRlcmlhbExvY2FsaXphdGlvbnMuZGVsZWdhdGUsIEdsb2JhbEN1cGVydGlub0xvY2FsaXphdGlvbnMuZGVsZWdhdGUsCiAgLy8vIGFuZCBHbG9iYWxXaWRnZXRzTG9jYWxpemF0aW9ucy5kZWxlZ2F0ZS4KICAvLy8KICAvLy8gQWRkaXRpb25hbCBkZWxlZ2F0ZXMgY2FuIGJlIGFkZGVkIGJ5IGFwcGVuZGluZyB0byB0aGlzIGxpc3QgaW4KICAvLy8gTWF0ZXJpYWxBcHAuIFRoaXMgbGlzdCBkb2VzIG5vdCBoYXZlIHRvIGJlIHVzZWQgYXQgYWxsIGlmIGEgY3VzdG9tIGxpc3QKICAvLy8gb2YgZGVsZWdhdGVzIGlzIHByZWZlcnJlZCBvciByZXF1aXJlZC4KICBzdGF0aWMgY29uc3QgTGlzdDxMb2NhbGl6YXRpb25zRGVsZWdhdGU8ZHluYW1pYz4+IGxvY2FsaXphdGlvbnNEZWxlZ2F0ZXMgPSA8TG9jYWxpemF0aW9uc0RlbGVnYXRlPGR5bmFtaWM+PlsKICAgIGRlbGVnYXRlLAogICAgR2xvYmFsTWF0ZXJpYWxMb2NhbGl6YXRpb25zLmRlbGVnYXRlLAogICAgR2xvYmFsQ3VwZXJ0aW5vTG9jYWxpemF0aW9ucy5kZWxlZ2F0ZSwKICAgIEdsb2JhbFdpZGdldHNMb2NhbGl6YXRpb25zLmRlbGVnYXRlLAogIF07CgogIC8vLyBBIGxpc3Qgb2YgdGhpcyBsb2NhbGl6YXRpb25zIGRlbGVnYXRlJ3Mgc3VwcG9ydGVkIGxvY2FsZXMuCiAgc3RhdGljIGNvbnN0IExpc3Q8TG9jYWxlPiBzdXBwb3J0ZWRMb2NhbGVzID0gPExvY2FsZT5bCiAgICBMb2NhbGUoJ2VuJykKICBdOwoKICAvLy8gVGl0bGUgdGV4dCBzaG93biBpbiB0aGUgSG9tZSBQYWdlCiAgLy8vCiAgLy8vIEluIGVuLCB0aGlzIG1lc3NhZ2UgdHJhbnNsYXRlcyB0bzoKICAvLy8gKionVGhlIGxhbmd1YWdlIGlzIGVuZ2xpc2gnKioKICBTdHJpbmcgZ2V0IHRpdGxlOwp9CgpjbGFzcyBfe3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zRGVsZWdhdGUgZXh0ZW5kcyBMb2NhbGl6YXRpb25zRGVsZWdhdGU8e3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zPiB7CiAgY29uc3QgX3t7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9uc0RlbGVnYXRlKCk7CgogIEBvdmVycmlkZQogIEZ1dHVyZTx7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnM+IGxvYWQoTG9jYWxlIGxvY2FsZSkgewogICAgcmV0dXJuIFN5bmNocm9ub3VzRnV0dXJlPHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9ucz4obG9va3Vwe3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zKGxvY2FsZSkpOwogIH0KCiAgQG92ZXJyaWRlCiAgYm9vbCBpc1N1cHBvcnRlZChMb2NhbGUgbG9jYWxlKSA9PiA8U3RyaW5nPlsnZW4nXS5jb250YWlucyhsb2NhbGUubGFuZ3VhZ2VDb2RlKTsKCiAgQG92ZXJyaWRlCiAgYm9vbCBzaG91bGRSZWxvYWQoX3t7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9uc0RlbGVnYXRlIG9sZCkgPT4gZmFsc2U7Cn0KCnt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9ucyBsb29rdXB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnMoTG9jYWxlIGxvY2FsZSkgewoKCiAgLy8gTG9va3VwIGxvZ2ljIHdoZW4gb25seSBsYW5ndWFnZSBjb2RlIGlzIHNwZWNpZmllZC4KICBzd2l0Y2ggKGxvY2FsZS5sYW5ndWFnZUNvZGUpIHsKICAgIGNhc2UgJ2VuJzogcmV0dXJuIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9uc0VuKCk7CiAgfQoKICB0aHJvdyBGbHV0dGVyRXJyb3IoCiAgICAne3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zLmRlbGVnYXRlIGZhaWxlZCB0byBsb2FkIHVuc3VwcG9ydGVkIGxvY2FsZSAiJGxvY2FsZSIuIFRoaXMgaXMgbGlrZWx5ICcKICAgICdhbiBpc3N1ZSB3aXRoIHRoZSBsb2NhbGl6YXRpb25zIGdlbmVyYXRpb24gdG9vbC4gUGxlYXNlIGZpbGUgYW4gaXNzdWUgJwogICAgJ29uIEdpdEh1YiB3aXRoIGEgcmVwcm9kdWNpYmxlIHNhbXBsZSBhcHAgYW5kIHRoZSBnZW4tbDEwbiBjb25maWd1cmF0aW9uICcKICAgICd0aGF0IHdhcyB1c2VkLicKICApOwp9Cg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/presentation/l10n/{{project_name}}_android_home_page_localizations_en.dart",
      "data":
          "aW1wb3J0ICd7e3Byb2plY3RfbmFtZX19X2FuZHJvaWRfaG9tZV9wYWdlX2xvY2FsaXphdGlvbnMuZGFydCc7CgovLy8gVGhlIHRyYW5zbGF0aW9ucyBmb3IgRW5nbGlzaCAoYGVuYCkuCmNsYXNzIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19QW5kcm9pZEhvbWVQYWdlTG9jYWxpemF0aW9uc0VuIGV4dGVuZHMge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkSG9tZVBhZ2VMb2NhbGl6YXRpb25zIHsKICB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUFuZHJvaWRIb21lUGFnZUxvY2FsaXphdGlvbnNFbihbU3RyaW5nIGxvY2FsZSA9ICdlbiddKSA6IHN1cGVyKGxvY2FsZSk7CgogIEBvdmVycmlkZQogIFN0cmluZyBnZXQgdGl0bGUgPT4gJ1RoZSBsYW5ndWFnZSBpcyBlbmdsaXNoJzsKfQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/src/presentation/presentation.dart",
      "data":
          "ZXhwb3J0ICdob21lX3BhZ2UuZGFydCc7CmV4cG9ydCAnbDEwbi97e3Byb2plY3RfbmFtZX19X2FuZHJvaWRfaG9tZV9wYWdlX2xvY2FsaXphdGlvbnMuZGFydCc7Cg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/lib/{{project_name}}_android_home_page.dart",
      "data":
          "Ly8gVE9ETzogZG9jCmxpYnJhcnkge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZTsKCmV4cG9ydCAnc3JjL2luamVjdGlvbi5tb2R1bGUuZGFydCc7CmV4cG9ydCAnc3JjL3ByZXNlbnRhdGlvbi9wcmVzZW50YXRpb24uZGFydCc7Cg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/LICENSE",
      "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/pubspec.yaml",
      "data":
          "bmFtZToge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZQpkZXNjcmlwdGlvbjogQSBuZXcgRmx1dHRlciBwYWNrYWdlIHByb2plY3QuCnZlcnNpb246IDAuMC4xCgplbnZpcm9ubWVudDoKICBzZGs6ICc+PTIuMTguNiA8My4wLjAnCiAgZmx1dHRlcjogIj49MS4xNy4wIgoKZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXI6CiAgICBzZGs6IGZsdXR0ZXIKICBibG9jOiBeOC4xLjAKICBmcmVlemVkX2Fubm90YXRpb246IF4yLjIuMAogIGZsdXR0ZXJfYmxvYzogXjguMS4xCiAgaW5qZWN0YWJsZTogXjIuMS4wCiAge3twcm9qZWN0X25hbWV9fV9kaToKICB7e3Byb2plY3RfbmFtZX19X2RvbWFpbjoKICB7e3Byb2plY3RfbmFtZX19X3VpX2FuZHJvaWQ6CiAge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX3JvdXRpbmc6CgpkZXZfZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXJfdGVzdDoKICAgIHNkazogZmx1dHRlcgogIGZsdXR0ZXJfbGludHM6IF4yLjAuMQogIGJ1aWxkX3J1bm5lcjogXjIuMy4yCiAgZnJlZXplZDogXjIuMy4xCiAgaW5qZWN0YWJsZV9nZW5lcmF0b3I6IF4yLjEuMwoKIyBGb3IgaW5mb3JtYXRpb24gb24gdGhlIGdlbmVyaWMgRGFydCBwYXJ0IG9mIHRoaXMgZmlsZSwgc2VlIHRoZQojIGZvbGxvd2luZyBwYWdlOiBodHRwczovL2RhcnQuZGV2L3Rvb2xzL3B1Yi9wdWJzcGVjCgojIFRoZSBmb2xsb3dpbmcgc2VjdGlvbiBpcyBzcGVjaWZpYyB0byBGbHV0dGVyIHBhY2thZ2VzLgpmbHV0dGVyOgoKICAjIFRvIGFkZCBhc3NldHMgdG8geW91ciBwYWNrYWdlLCBhZGQgYW4gYXNzZXRzIHNlY3Rpb24sIGxpa2UgdGhpczoKICAjIGFzc2V0czoKICAjICAgLSBpbWFnZXMvYV9kb3RfYnVyci5qcGVnCiAgIyAgIC0gaW1hZ2VzL2FfZG90X2hhbS5qcGVnCiAgIwogICMgRm9yIGRldGFpbHMgcmVnYXJkaW5nIGFzc2V0cyBpbiBwYWNrYWdlcywgc2VlCiAgIyBodHRwczovL2ZsdXR0ZXIuZGV2L2Fzc2V0cy1hbmQtaW1hZ2VzLyNmcm9tLXBhY2thZ2VzCiAgIwogICMgQW4gaW1hZ2UgYXNzZXQgY2FuIHJlZmVyIHRvIG9uZSBvciBtb3JlIHJlc29sdXRpb24tc3BlY2lmaWMgInZhcmlhbnRzIiwgc2VlCiAgIyBodHRwczovL2ZsdXR0ZXIuZGV2L2Fzc2V0cy1hbmQtaW1hZ2VzLyNyZXNvbHV0aW9uLWF3YXJlCgogICMgVG8gYWRkIGN1c3RvbSBmb250cyB0byB5b3VyIHBhY2thZ2UsIGFkZCBhIGZvbnRzIHNlY3Rpb24gaGVyZSwKICAjIGluIHRoaXMgImZsdXR0ZXIiIHNlY3Rpb24uIEVhY2ggZW50cnkgaW4gdGhpcyBsaXN0IHNob3VsZCBoYXZlIGEKICAjICJmYW1pbHkiIGtleSB3aXRoIHRoZSBmb250IGZhbWlseSBuYW1lLCBhbmQgYSAiZm9udHMiIGtleSB3aXRoIGEKICAjIGxpc3QgZ2l2aW5nIHRoZSBhc3NldCBhbmQgb3RoZXIgZGVzY3JpcHRvcnMgZm9yIHRoZSBmb250LiBGb3IKICAjIGV4YW1wbGU6CiAgIyBmb250czoKICAjICAgLSBmYW1pbHk6IFNjaHlsZXIKICAjICAgICBmb250czoKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1NjaHlsZXItUmVndWxhci50dGYKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1NjaHlsZXItSXRhbGljLnR0ZgogICMgICAgICAgICBzdHlsZTogaXRhbGljCiAgIyAgIC0gZmFtaWx5OiBUcmFqYW4gUHJvCiAgIyAgICAgZm9udHM6CiAgIyAgICAgICAtIGFzc2V0OiBmb250cy9UcmFqYW5Qcm8udHRmCiAgIyAgICAgICAtIGFzc2V0OiBmb250cy9UcmFqYW5Qcm9fQm9sZC50dGYKICAjICAgICAgICAgd2VpZ2h0OiA3MDAKICAjCiAgIyBGb3IgZGV0YWlscyByZWdhcmRpbmcgZm9udHMgaW4gcGFja2FnZXMsIHNlZQogICMgaHR0cHM6Ly9mbHV0dGVyLmRldi9jdXN0b20tZm9udHMvI2Zyb20tcGFja2FnZXMK",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_home_page/README.md",
      "data":
          "PCEtLQpUaGlzIFJFQURNRSBkZXNjcmliZXMgdGhlIHBhY2thZ2UuIElmIHlvdSBwdWJsaXNoIHRoaXMgcGFja2FnZSB0byBwdWIuZGV2LAp0aGlzIFJFQURNRSdzIGNvbnRlbnRzIGFwcGVhciBvbiB0aGUgbGFuZGluZyBwYWdlIGZvciB5b3VyIHBhY2thZ2UuCgpGb3IgaW5mb3JtYXRpb24gYWJvdXQgaG93IHRvIHdyaXRlIGEgZ29vZCBwYWNrYWdlIFJFQURNRSwgc2VlIHRoZSBndWlkZSBmb3IKW3dyaXRpbmcgcGFja2FnZSBwYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL3dyaXRpbmctcGFja2FnZS1wYWdlcykuCgpGb3IgZ2VuZXJhbCBpbmZvcm1hdGlvbiBhYm91dCBkZXZlbG9waW5nIHBhY2thZ2VzLCBzZWUgdGhlIERhcnQgZ3VpZGUgZm9yCltjcmVhdGluZyBwYWNrYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL2NyZWF0ZS1saWJyYXJ5LXBhY2thZ2VzKQphbmQgdGhlIEZsdXR0ZXIgZ3VpZGUgZm9yCltkZXZlbG9waW5nIHBhY2thZ2VzIGFuZCBwbHVnaW5zXShodHRwczovL2ZsdXR0ZXIuZGV2L2RldmVsb3BpbmctcGFja2FnZXMpLgotLT4KClRPRE86IFB1dCBhIHNob3J0IGRlc2NyaXB0aW9uIG9mIHRoZSBwYWNrYWdlIGhlcmUgdGhhdCBoZWxwcyBwb3RlbnRpYWwgdXNlcnMKa25vdyB3aGV0aGVyIHRoaXMgcGFja2FnZSBtaWdodCBiZSB1c2VmdWwgZm9yIHRoZW0uCgojIyBGZWF0dXJlcwoKVE9ETzogTGlzdCB3aGF0IHlvdXIgcGFja2FnZSBjYW4gZG8uIE1heWJlIGluY2x1ZGUgaW1hZ2VzLCBnaWZzLCBvciB2aWRlb3MuCgojIyBHZXR0aW5nIHN0YXJ0ZWQKClRPRE86IExpc3QgcHJlcmVxdWlzaXRlcyBhbmQgcHJvdmlkZSBvciBwb2ludCB0byBpbmZvcm1hdGlvbiBvbiBob3cgdG8Kc3RhcnQgdXNpbmcgdGhlIHBhY2thZ2UuCgojIyBVc2FnZQoKVE9ETzogSW5jbHVkZSBzaG9ydCBhbmQgdXNlZnVsIGV4YW1wbGVzIGZvciBwYWNrYWdlIHVzZXJzLiBBZGQgbG9uZ2VyIGV4YW1wbGVzCnRvIGAvZXhhbXBsZWAgZm9sZGVyLgoKYGBgZGFydApjb25zdCBsaWtlID0gJ3NhbXBsZSc7CmBgYAoKIyMgQWRkaXRpb25hbCBpbmZvcm1hdGlvbgoKVE9ETzogVGVsbCB1c2VycyBtb3JlIGFib3V0IHRoZSBwYWNrYWdlOiB3aGVyZSB0byBmaW5kIG1vcmUgaW5mb3JtYXRpb24sIGhvdyB0bwpjb250cmlidXRlIHRvIHRoZSBwYWNrYWdlLCBob3cgdG8gZmlsZSBpc3N1ZXMsIHdoYXQgcmVzcG9uc2UgdGhleSBjYW4gZXhwZWN0CmZyb20gdGhlIHBhY2thZ2UgYXV0aG9ycywgYW5kIG1vcmUuCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/.gitignore",
      "data":
          "IyBNaXNjZWxsYW5lb3VzCiouY2xhc3MKKi5sb2cKKi5weWMKKi5zd3AKLkRTX1N0b3JlCi5hdG9tLwouYnVpbGRsb2cvCi5oaXN0b3J5Ci5zdm4vCm1pZ3JhdGVfd29ya2luZ19kaXIvCgojIEludGVsbGlKIHJlbGF0ZWQKKi5pbWwKKi5pcHIKKi5pd3MKLmlkZWEvCgojIFRoZSAudnNjb2RlIGZvbGRlciBjb250YWlucyBsYXVuY2ggY29uZmlndXJhdGlvbiBhbmQgdGFza3MgeW91IGNvbmZpZ3VyZSBpbgojIFZTIENvZGUgd2hpY2ggeW91IG1heSB3aXNoIHRvIGJlIGluY2x1ZGVkIGluIHZlcnNpb24gY29udHJvbCwgc28gdGhpcyBsaW5lCiMgaXMgY29tbWVudGVkIG91dCBieSBkZWZhdWx0LgojLnZzY29kZS8KCiMgRmx1dHRlci9EYXJ0L1B1YiByZWxhdGVkCiMgTGlicmFyaWVzIHNob3VsZCBub3QgaW5jbHVkZSBwdWJzcGVjLmxvY2ssIHBlciBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9saWJyYXJpZXMvcHJpdmF0ZS1maWxlcyNwdWJzcGVjbG9jay4KL3B1YnNwZWMubG9jawoqKi9kb2MvYXBpLwouZGFydF90b29sLwoucGFja2FnZXMKYnVpbGQvCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/analysis_options.yaml",
      "data":
          "aW5jbHVkZTogcGFja2FnZTpmbHV0dGVyX2xpbnRzL2ZsdXR0ZXIueWFtbAoKIyBBZGRpdGlvbmFsIGluZm9ybWF0aW9uIGFib3V0IHRoaXMgZmlsZSBjYW4gYmUgZm91bmQgYXQKIyBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9sYW5ndWFnZS9hbmFseXNpcy1vcHRpb25zCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/CHANGELOG.md",
      "data": "IyMgMC4wLjEKCiogVE9ETzogRGVzY3JpYmUgaW5pdGlhbCByZWxlYXNlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/lib/src/injection.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmluamVjdGFibGUvaW5qZWN0YWJsZS5kYXJ0JzsKCi8vLyBTZXR1cCBpbmplY3RhYmxlIHBhY2thZ2Ugd2hpY2ggZ2VuZXJhdGVzIGRlcGVuZGVuY3kgaW5qZWN0aW9uIGNvZGUuCi8vLwovLy8gRm9yIG1vcmUgaW5mbyBzZWU6IGh0dHBzOi8vcHViLmRldi9wYWNrYWdlcy9pbmplY3RhYmxlCkBJbmplY3RhYmxlSW5pdC5taWNyb1BhY2thZ2UoKQppbml0TWljcm9QYWNrYWdlKCkge30K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/lib/src/injection.module.dart",
      "data":
          "Ly9AR2VuZXJhdGVkTWljcm9Nb2R1bGU7e3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkUm91dGluZ1BhY2thZ2VNb2R1bGU7cGFja2FnZTpqb25hc19kYXZpZF9hbmRyb2lkX3JvdXRpbmcvc3JjL2luamVjdGlvbi5tb2R1bGUuZGFydAovLyBHRU5FUkFURUQgQ09ERSAtIERPIE5PVCBNT0RJRlkgQlkgSEFORAovLyBpZ25vcmVfZm9yX2ZpbGU6IG5vX2xlYWRpbmdfdW5kZXJzY29yZXNfZm9yX2xpYnJhcnlfcHJlZml4ZXMKaW1wb3J0ICdkYXJ0OmFzeW5jJyBhcyBfaTI7CgppbXBvcnQgJ3BhY2thZ2U6aW5qZWN0YWJsZS9pbmplY3RhYmxlLmRhcnQnIGFzIF9pMTsKCi8vLyBpZ25vcmVfZm9yX2ZpbGU6IHVubmVjZXNzYXJ5X2xhbWJkYXMKLy8vIGlnbm9yZV9mb3JfZmlsZTogbGluZXNfbG9uZ2VyX3RoYW5fODBfY2hhcnMKY2xhc3Mge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BbmRyb2lkUm91dGluZ1BhY2thZ2VNb2R1bGUgZXh0ZW5kcyBfaTEuTWljcm9QYWNrYWdlTW9kdWxlIHsKICAvLy8gaW5pdGlhbGl6ZXMgdGhlIHJlZ2lzdHJhdGlvbiBvZiBtYWluLXNjb3BlIGRlcGVuZGVuY2llcyBpbnNpZGUgb2YgW0dldEl0XQogIEBvdmVycmlkZQogIF9pMi5GdXR1cmVPcjx2b2lkPiBpbml0KF9pMS5HZXRJdEhlbHBlciBnaCkge30KfQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/lib/src/router.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmF1dG9fcm91dGUvYXV0b19yb3V0ZS5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvd2lkZ2V0cy5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9ob21lX3BhZ2Uve3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX2hvbWVfcGFnZS5kYXJ0JzsKCnBhcnQgJ3JvdXRlci5nci5kYXJ0JzsKCi8vLyBTZXR1cCBhdXRvIHJvdXRlIHdoaWNoIGdlbmVyYXRlcyByb3V0aW5nIGNvZGUuCi8vLwovLy8gRm9yIG1vcmUgaW5mbyBzZWU6IGh0dHBzOi8vcHViLmRldi9wYWNrYWdlcy9hdXRvX3JvdXRlCkBNYXRlcmlhbEF1dG9Sb3V0ZXIoCiAgcm91dGVzOiBbCiAgICBNYXRlcmlhbFJvdXRlKAogICAgICBpbml0aWFsOiB0cnVlLAogICAgICBwYWdlOiBIb21lUGFnZSwKICAgICksCiAgXSwKKQpjbGFzcyBSb3V0ZXIgZXh0ZW5kcyBfJFJvdXRlciB7fQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/lib/src/router.gr.dart",
      "data":
          "Ly8gKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioKLy8gQXV0b1JvdXRlR2VuZXJhdG9yCi8vICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqCgovLyBHRU5FUkFURUQgQ09ERSAtIERPIE5PVCBNT0RJRlkgQlkgSEFORAoKLy8gKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioKLy8gQXV0b1JvdXRlR2VuZXJhdG9yCi8vICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqCi8vCi8vIGlnbm9yZV9mb3JfZmlsZTogdHlwZT1saW50CgpwYXJ0IG9mICdyb3V0ZXIuZGFydCc7CgpjbGFzcyBfJFJvdXRlciBleHRlbmRzIFJvb3RTdGFja1JvdXRlciB7CiAgXyRSb3V0ZXIoW0dsb2JhbEtleTxOYXZpZ2F0b3JTdGF0ZT4/IG5hdmlnYXRvcktleV0pIDogc3VwZXIobmF2aWdhdG9yS2V5KTsKCiAgQG92ZXJyaWRlCiAgZmluYWwgTWFwPFN0cmluZywgUGFnZUZhY3Rvcnk+IHBhZ2VzTWFwID0gewogICAgSG9tZVBhZ2VSb3V0ZS5uYW1lOiAocm91dGVEYXRhKSB7CiAgICAgIHJldHVybiBNYXRlcmlhbFBhZ2VYPGR5bmFtaWM+KAogICAgICAgIHJvdXRlRGF0YTogcm91dGVEYXRhLAogICAgICAgIGNoaWxkOiBjb25zdCBIb21lUGFnZSgpLAogICAgICApOwogICAgfQogIH07CgogIEBvdmVycmlkZQogIExpc3Q8Um91dGVDb25maWc+IGdldCByb3V0ZXMgPT4gWwogICAgICAgIFJvdXRlQ29uZmlnKAogICAgICAgICAgSG9tZVBhZ2VSb3V0ZS5uYW1lLAogICAgICAgICAgcGF0aDogJy8nLAogICAgICAgICkKICAgICAgXTsKfQoKLy8vIGdlbmVyYXRlZCByb3V0ZSBmb3IKLy8vIFtIb21lUGFnZV0KY2xhc3MgSG9tZVBhZ2VSb3V0ZSBleHRlbmRzIFBhZ2VSb3V0ZUluZm88dm9pZD4gewogIGNvbnN0IEhvbWVQYWdlUm91dGUoKQogICAgICA6IHN1cGVyKAogICAgICAgICAgSG9tZVBhZ2VSb3V0ZS5uYW1lLAogICAgICAgICAgcGF0aDogJy8nLAogICAgICAgICk7CgogIHN0YXRpYyBjb25zdCBTdHJpbmcgbmFtZSA9ICdIb21lUGFnZVJvdXRlJzsKfQo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/lib/{{project_name}}_android_routing.dart",
      "data":
          "Ly8gVE9ETyBkb2M6CmxpYnJhcnkge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX3JvdXRpbmc7CgpleHBvcnQgJ3NyYy9pbmplY3Rpb24uZGFydCc7CmV4cG9ydCAnc3JjL2luamVjdGlvbi5tb2R1bGUuZGFydCc7CmV4cG9ydCAnc3JjL3JvdXRlci5kYXJ0JzsKZXhwb3J0ICdwYWNrYWdlOmF1dG9fcm91dGUvYXV0b19yb3V0ZS5kYXJ0JyBzaG93IEF1dG9Sb3V0ZXJYOwo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/LICENSE",
      "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/pubspec.yaml",
      "data":
          "bmFtZToge3twcm9qZWN0X25hbWV9fV9hbmRyb2lkX3JvdXRpbmcKZGVzY3JpcHRpb246IEEgbmV3IEZsdXR0ZXIgcGFja2FnZSBwcm9qZWN0Lgp2ZXJzaW9uOiAwLjAuMQpwdWJsaXNoX3RvOiBub25lCgplbnZpcm9ubWVudDoKICBzZGs6ICI+PTIuMTguNiA8My4wLjAiCiAgZmx1dHRlcjogIj49MS4xNy4wIgoKZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXI6CiAgICBzZGs6IGZsdXR0ZXIKICBhdXRvX3JvdXRlOiBeNS4wLjQKICBpbmplY3RhYmxlOiBeMi4xLjAKICB7e3Byb2plY3RfbmFtZX19X2RvbWFpbjoKICB7e3Byb2plY3RfbmFtZX19X2RpOgogIHt7cHJvamVjdF9uYW1lfX1fYW5kcm9pZF9ob21lX3BhZ2U6CgpkZXZfZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXJfdGVzdDoKICAgIHNkazogZmx1dHRlcgogIGZsdXR0ZXJfbGludHM6IF4yLjAuMQogIGJ1aWxkX3J1bm5lcjogXjIuMy4yCiAgYXV0b19yb3V0ZV9nZW5lcmF0b3I6IF41LjAuMwogIGluamVjdGFibGVfZ2VuZXJhdG9yOiBeMi4xLjMKCiMgRm9yIGluZm9ybWF0aW9uIG9uIHRoZSBnZW5lcmljIERhcnQgcGFydCBvZiB0aGlzIGZpbGUsIHNlZSB0aGUKIyBmb2xsb3dpbmcgcGFnZTogaHR0cHM6Ly9kYXJ0LmRldi90b29scy9wdWIvcHVic3BlYwoKIyBUaGUgZm9sbG93aW5nIHNlY3Rpb24gaXMgc3BlY2lmaWMgdG8gRmx1dHRlciBwYWNrYWdlcy4KZmx1dHRlcjoKCiAgIyBUbyBhZGQgYXNzZXRzIHRvIHlvdXIgcGFja2FnZSwgYWRkIGFuIGFzc2V0cyBzZWN0aW9uLCBsaWtlIHRoaXM6CiAgIyBhc3NldHM6CiAgIyAgIC0gaW1hZ2VzL2FfZG90X2J1cnIuanBlZwogICMgICAtIGltYWdlcy9hX2RvdF9oYW0uanBlZwogICMKICAjIEZvciBkZXRhaWxzIHJlZ2FyZGluZyBhc3NldHMgaW4gcGFja2FnZXMsIHNlZQogICMgaHR0cHM6Ly9mbHV0dGVyLmRldi9hc3NldHMtYW5kLWltYWdlcy8jZnJvbS1wYWNrYWdlcwogICMKICAjIEFuIGltYWdlIGFzc2V0IGNhbiByZWZlciB0byBvbmUgb3IgbW9yZSByZXNvbHV0aW9uLXNwZWNpZmljICJ2YXJpYW50cyIsIHNlZQogICMgaHR0cHM6Ly9mbHV0dGVyLmRldi9hc3NldHMtYW5kLWltYWdlcy8jcmVzb2x1dGlvbi1hd2FyZQoKICAjIFRvIGFkZCBjdXN0b20gZm9udHMgdG8geW91ciBwYWNrYWdlLCBhZGQgYSBmb250cyBzZWN0aW9uIGhlcmUsCiAgIyBpbiB0aGlzICJmbHV0dGVyIiBzZWN0aW9uLiBFYWNoIGVudHJ5IGluIHRoaXMgbGlzdCBzaG91bGQgaGF2ZSBhCiAgIyAiZmFtaWx5IiBrZXkgd2l0aCB0aGUgZm9udCBmYW1pbHkgbmFtZSwgYW5kIGEgImZvbnRzIiBrZXkgd2l0aCBhCiAgIyBsaXN0IGdpdmluZyB0aGUgYXNzZXQgYW5kIG90aGVyIGRlc2NyaXB0b3JzIGZvciB0aGUgZm9udC4gRm9yCiAgIyBleGFtcGxlOgogICMgZm9udHM6CiAgIyAgIC0gZmFtaWx5OiBTY2h5bGVyCiAgIyAgICAgZm9udHM6CiAgIyAgICAgICAtIGFzc2V0OiBmb250cy9TY2h5bGVyLVJlZ3VsYXIudHRmCiAgIyAgICAgICAtIGFzc2V0OiBmb250cy9TY2h5bGVyLUl0YWxpYy50dGYKICAjICAgICAgICAgc3R5bGU6IGl0YWxpYwogICMgICAtIGZhbWlseTogVHJhamFuIFBybwogICMgICAgIGZvbnRzOgogICMgICAgICAgLSBhc3NldDogZm9udHMvVHJhamFuUHJvLnR0ZgogICMgICAgICAgLSBhc3NldDogZm9udHMvVHJhamFuUHJvX0JvbGQudHRmCiAgIyAgICAgICAgIHdlaWdodDogNzAwCiAgIwogICMgRm9yIGRldGFpbHMgcmVnYXJkaW5nIGZvbnRzIGluIHBhY2thZ2VzLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvY3VzdG9tLWZvbnRzLyNmcm9tLXBhY2thZ2VzCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_android/{{project_name}}_android_routing/README.md",
      "data":
          "PCEtLQpUaGlzIFJFQURNRSBkZXNjcmliZXMgdGhlIHBhY2thZ2UuIElmIHlvdSBwdWJsaXNoIHRoaXMgcGFja2FnZSB0byBwdWIuZGV2LAp0aGlzIFJFQURNRSdzIGNvbnRlbnRzIGFwcGVhciBvbiB0aGUgbGFuZGluZyBwYWdlIGZvciB5b3VyIHBhY2thZ2UuCgpGb3IgaW5mb3JtYXRpb24gYWJvdXQgaG93IHRvIHdyaXRlIGEgZ29vZCBwYWNrYWdlIFJFQURNRSwgc2VlIHRoZSBndWlkZSBmb3IKW3dyaXRpbmcgcGFja2FnZSBwYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL3dyaXRpbmctcGFja2FnZS1wYWdlcykuCgpGb3IgZ2VuZXJhbCBpbmZvcm1hdGlvbiBhYm91dCBkZXZlbG9waW5nIHBhY2thZ2VzLCBzZWUgdGhlIERhcnQgZ3VpZGUgZm9yCltjcmVhdGluZyBwYWNrYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL2NyZWF0ZS1saWJyYXJ5LXBhY2thZ2VzKQphbmQgdGhlIEZsdXR0ZXIgZ3VpZGUgZm9yCltkZXZlbG9waW5nIHBhY2thZ2VzIGFuZCBwbHVnaW5zXShodHRwczovL2ZsdXR0ZXIuZGV2L2RldmVsb3BpbmctcGFja2FnZXMpLgotLT4KClRPRE86IFB1dCBhIHNob3J0IGRlc2NyaXB0aW9uIG9mIHRoZSBwYWNrYWdlIGhlcmUgdGhhdCBoZWxwcyBwb3RlbnRpYWwgdXNlcnMKa25vdyB3aGV0aGVyIHRoaXMgcGFja2FnZSBtaWdodCBiZSB1c2VmdWwgZm9yIHRoZW0uCgojIyBGZWF0dXJlcwoKVE9ETzogTGlzdCB3aGF0IHlvdXIgcGFja2FnZSBjYW4gZG8uIE1heWJlIGluY2x1ZGUgaW1hZ2VzLCBnaWZzLCBvciB2aWRlb3MuCgojIyBHZXR0aW5nIHN0YXJ0ZWQKClRPRE86IExpc3QgcHJlcmVxdWlzaXRlcyBhbmQgcHJvdmlkZSBvciBwb2ludCB0byBpbmZvcm1hdGlvbiBvbiBob3cgdG8Kc3RhcnQgdXNpbmcgdGhlIHBhY2thZ2UuCgojIyBVc2FnZQoKVE9ETzogSW5jbHVkZSBzaG9ydCBhbmQgdXNlZnVsIGV4YW1wbGVzIGZvciBwYWNrYWdlIHVzZXJzLiBBZGQgbG9uZ2VyIGV4YW1wbGVzCnRvIGAvZXhhbXBsZWAgZm9sZGVyLgoKYGBgZGFydApjb25zdCBsaWtlID0gJ3NhbXBsZSc7CmBgYAoKIyMgQWRkaXRpb25hbCBpbmZvcm1hdGlvbgoKVE9ETzogVGVsbCB1c2VycyBtb3JlIGFib3V0IHRoZSBwYWNrYWdlOiB3aGVyZSB0byBmaW5kIG1vcmUgaW5mb3JtYXRpb24sIGhvdyB0bwpjb250cmlidXRlIHRvIHRoZSBwYWNrYWdlLCBob3cgdG8gZmlsZSBpc3N1ZXMsIHdoYXQgcmVzcG9uc2UgdGhleSBjYW4gZXhwZWN0CmZyb20gdGhlIHBhY2thZ2UgYXV0aG9ycywgYW5kIG1vcmUuCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/.gitignore",
      "data":
          "IyBNaXNjZWxsYW5lb3VzCiouY2xhc3MKKi5sb2cKKi5weWMKKi5zd3AKLkRTX1N0b3JlCi5hdG9tLwouYnVpbGRsb2cvCi5oaXN0b3J5Ci5zdm4vCm1pZ3JhdGVfd29ya2luZ19kaXIvCgojIEludGVsbGlKIHJlbGF0ZWQKKi5pbWwKKi5pcHIKKi5pd3MKLmlkZWEvCgojIFRoZSAudnNjb2RlIGZvbGRlciBjb250YWlucyBsYXVuY2ggY29uZmlndXJhdGlvbiBhbmQgdGFza3MgeW91IGNvbmZpZ3VyZSBpbgojIFZTIENvZGUgd2hpY2ggeW91IG1heSB3aXNoIHRvIGJlIGluY2x1ZGVkIGluIHZlcnNpb24gY29udHJvbCwgc28gdGhpcyBsaW5lCiMgaXMgY29tbWVudGVkIG91dCBieSBkZWZhdWx0LgojLnZzY29kZS8KCiMgRmx1dHRlci9EYXJ0L1B1YiByZWxhdGVkCiMgTGlicmFyaWVzIHNob3VsZCBub3QgaW5jbHVkZSBwdWJzcGVjLmxvY2ssIHBlciBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9saWJyYXJpZXMvcHJpdmF0ZS1maWxlcyNwdWJzcGVjbG9jay4KL3B1YnNwZWMubG9jawoqKi9kb2MvYXBpLwouZGFydF90b29sLwoucGFja2FnZXMKYnVpbGQvCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/analysis_options.yaml",
      "data":
          "aW5jbHVkZTogcGFja2FnZTpmbHV0dGVyX2xpbnRzL2ZsdXR0ZXIueWFtbAoKIyBBZGRpdGlvbmFsIGluZm9ybWF0aW9uIGFib3V0IHRoaXMgZmlsZSBjYW4gYmUgZm91bmQgYXQKIyBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9sYW5ndWFnZS9hbmFseXNpcy1vcHRpb25zCg==",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/CHANGELOG.md",
      "data": "IyMgMC4wLjEKCiogVE9ETzogRGVzY3JpYmUgaW5pdGlhbCByZWxlYXNlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/lib/src/app.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyX2xvY2FsaXphdGlvbnMvZmx1dHRlcl9sb2NhbGl6YXRpb25zLmRhcnQnOwoKY2xhc3Mge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BcHAgZXh0ZW5kcyBTdGF0ZWxlc3NXaWRnZXQgewogIGZpbmFsIExvY2FsZT8gbG9jYWxlOwogIGZpbmFsIEl0ZXJhYmxlPExvY2FsaXphdGlvbnNEZWxlZ2F0ZTxkeW5hbWljPj4/IGxvY2FsaXphdGlvbnNEZWxlZ2F0ZXM7CiAgZmluYWwgSXRlcmFibGU8TG9jYWxlPiBzdXBwb3J0ZWRMb2NhbGVzOwogIGZpbmFsIFJvdXRlSW5mb3JtYXRpb25QYXJzZXI8T2JqZWN0Pj8gcm91dGVJbmZvcm1hdGlvblBhcnNlcjsKICBmaW5hbCBSb3V0ZXJEZWxlZ2F0ZTxPYmplY3Q+PyByb3V0ZXJEZWxlZ2F0ZTsKCiAgY29uc3Qge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1BcHAoewogICAgc3VwZXIua2V5LAogICAgdGhpcy5sb2NhbGUsCiAgICB0aGlzLmxvY2FsaXphdGlvbnNEZWxlZ2F0ZXMsCiAgICByZXF1aXJlZCB0aGlzLnN1cHBvcnRlZExvY2FsZXMsCiAgICB0aGlzLnJvdXRlSW5mb3JtYXRpb25QYXJzZXIsCiAgICB0aGlzLnJvdXRlckRlbGVnYXRlLAogIH0pOwoKICBAb3ZlcnJpZGUKICBXaWRnZXQgYnVpbGQoQnVpbGRDb250ZXh0IGNvbnRleHQpIHsKICAgIHJldHVybiBNYXRlcmlhbEFwcC5yb3V0ZXIoCiAgICAgIGxvY2FsZTogbG9jYWxlLAogICAgICBsb2NhbGl6YXRpb25zRGVsZWdhdGVzOiBbCiAgICAgICAgLi4uR2xvYmFsTWF0ZXJpYWxMb2NhbGl6YXRpb25zLmRlbGVnYXRlcywKICAgICAgICAuLi4/bG9jYWxpemF0aW9uc0RlbGVnYXRlcywKICAgICAgXSwKICAgICAgc3VwcG9ydGVkTG9jYWxlczogc3VwcG9ydGVkTG9jYWxlcywKICAgICAgcm91dGVJbmZvcm1hdGlvblBhcnNlcjogcm91dGVJbmZvcm1hdGlvblBhcnNlciwKICAgICAgcm91dGVyRGVsZWdhdGU6IHJvdXRlckRlbGVnYXRlLAogICAgKTsKICB9Cn0K",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/lib/{{project_name}}_ui_android.dart",
      "data":
          "Ly8vIFdpZGdldHMgYW5kIHRoZW1lcyBpbXBsZW1lbnRpbmcgdC1vZmZsaW5lIGRlc2lnbiBsYW5ndWFnZSBmb3IgQW5kcm9pZC4KLy8vCi8vLyBUbyB1c2UsIGltcG9ydCBgcGFja2FnZTp7e3Byb2plY3RfbmFtZX19X3VpX2FuZHJvaWQve3twcm9qZWN0X25hbWV9fV91aV9hbmRyb2lkLmRhcnRgLgpsaWJyYXJ5IHt7cHJvamVjdF9uYW1lfX1fdWlfYW5kcm9pZDsKCmV4cG9ydCAnc3JjL2FwcC5kYXJ0JzsKCmV4cG9ydCAncGFja2FnZTp7e3Byb2plY3RfbmFtZX19X3VpL3t7cHJvamVjdF9uYW1lfX1fdWkuZGFydCc7CmV4cG9ydCAncGFja2FnZTpmbHV0dGVyL21hdGVyaWFsLmRhcnQnIGhpZGUgUm91dGVyOwo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/LICENSE",
      "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/pubspec.yaml",
      "data":
          "bmFtZToge3twcm9qZWN0X25hbWV9fV91aV9hbmRyb2lkCmRlc2NyaXB0aW9uOiBXaWRnZXRzIGFuZCB0aGVtZXMgaW1wbGVtZW50aW5nIHQtb2ZmbGluZSBkZXNpZ24gbGFuZ3VhZ2UgZm9yIEFuZHJvaWQuCnZlcnNpb246IDAuMC4xCnB1Ymxpc2hfdG86IG5vbmUKCmVudmlyb25tZW50OgogIHNkazogJz49Mi4xOC42IDwzLjAuMCcKICBmbHV0dGVyOiAiPj0zLjMuOSIKCmRlcGVuZGVuY2llczoKICBmbHV0dGVyOgogICAgc2RrOiBmbHV0dGVyCiAgZmx1dHRlcl9sb2NhbGl6YXRpb25zOgogICAgc2RrOiBmbHV0dGVyCiAge3twcm9qZWN0X25hbWV9fV91aToKCmRldl9kZXBlbmRlbmNpZXM6CiAgZmx1dHRlcl90ZXN0OgogICAgc2RrOiBmbHV0dGVyCiAgZmx1dHRlcl9saW50czogXjIuMC4xCgojIEZvciBpbmZvcm1hdGlvbiBvbiB0aGUgZ2VuZXJpYyBEYXJ0IHBhcnQgb2YgdGhpcyBmaWxlLCBzZWUgdGhlCiMgZm9sbG93aW5nIHBhZ2U6IGh0dHBzOi8vZGFydC5kZXYvdG9vbHMvcHViL3B1YnNwZWMKCiMgVGhlIGZvbGxvd2luZyBzZWN0aW9uIGlzIHNwZWNpZmljIHRvIEZsdXR0ZXIgcGFja2FnZXMuCmZsdXR0ZXI6CgogICMgVG8gYWRkIGFzc2V0cyB0byB5b3VyIHBhY2thZ2UsIGFkZCBhbiBhc3NldHMgc2VjdGlvbiwgbGlrZSB0aGlzOgogICMgYXNzZXRzOgogICMgICAtIGltYWdlcy9hX2RvdF9idXJyLmpwZWcKICAjICAgLSBpbWFnZXMvYV9kb3RfaGFtLmpwZWcKICAjCiAgIyBGb3IgZGV0YWlscyByZWdhcmRpbmcgYXNzZXRzIGluIHBhY2thZ2VzLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvYXNzZXRzLWFuZC1pbWFnZXMvI2Zyb20tcGFja2FnZXMKICAjCiAgIyBBbiBpbWFnZSBhc3NldCBjYW4gcmVmZXIgdG8gb25lIG9yIG1vcmUgcmVzb2x1dGlvbi1zcGVjaWZpYyAidmFyaWFudHMiLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvYXNzZXRzLWFuZC1pbWFnZXMvI3Jlc29sdXRpb24tYXdhcmUKCiAgIyBUbyBhZGQgY3VzdG9tIGZvbnRzIHRvIHlvdXIgcGFja2FnZSwgYWRkIGEgZm9udHMgc2VjdGlvbiBoZXJlLAogICMgaW4gdGhpcyAiZmx1dHRlciIgc2VjdGlvbi4gRWFjaCBlbnRyeSBpbiB0aGlzIGxpc3Qgc2hvdWxkIGhhdmUgYQogICMgImZhbWlseSIga2V5IHdpdGggdGhlIGZvbnQgZmFtaWx5IG5hbWUsIGFuZCBhICJmb250cyIga2V5IHdpdGggYQogICMgbGlzdCBnaXZpbmcgdGhlIGFzc2V0IGFuZCBvdGhlciBkZXNjcmlwdG9ycyBmb3IgdGhlIGZvbnQuIEZvcgogICMgZXhhbXBsZToKICAjIGZvbnRzOgogICMgICAtIGZhbWlseTogU2NoeWxlcgogICMgICAgIGZvbnRzOgogICMgICAgICAgLSBhc3NldDogZm9udHMvU2NoeWxlci1SZWd1bGFyLnR0ZgogICMgICAgICAgLSBhc3NldDogZm9udHMvU2NoeWxlci1JdGFsaWMudHRmCiAgIyAgICAgICAgIHN0eWxlOiBpdGFsaWMKICAjICAgLSBmYW1pbHk6IFRyYWphbiBQcm8KICAjICAgICBmb250czoKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1RyYWphblByby50dGYKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1RyYWphblByb19Cb2xkLnR0ZgogICMgICAgICAgICB3ZWlnaHQ6IDcwMAogICMKICAjIEZvciBkZXRhaWxzIHJlZ2FyZGluZyBmb250cyBpbiBwYWNrYWdlcywgc2VlCiAgIyBodHRwczovL2ZsdXR0ZXIuZGV2L2N1c3RvbS1mb250cy8jZnJvbS1wYWNrYWdlcwo=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}_ui/{{project_name}}_ui_android/README.md",
      "data":
          "PCEtLQpUaGlzIFJFQURNRSBkZXNjcmliZXMgdGhlIHBhY2thZ2UuIElmIHlvdSBwdWJsaXNoIHRoaXMgcGFja2FnZSB0byBwdWIuZGV2LAp0aGlzIFJFQURNRSdzIGNvbnRlbnRzIGFwcGVhciBvbiB0aGUgbGFuZGluZyBwYWdlIGZvciB5b3VyIHBhY2thZ2UuCgpGb3IgaW5mb3JtYXRpb24gYWJvdXQgaG93IHRvIHdyaXRlIGEgZ29vZCBwYWNrYWdlIFJFQURNRSwgc2VlIHRoZSBndWlkZSBmb3IKW3dyaXRpbmcgcGFja2FnZSBwYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL3dyaXRpbmctcGFja2FnZS1wYWdlcykuCgpGb3IgZ2VuZXJhbCBpbmZvcm1hdGlvbiBhYm91dCBkZXZlbG9waW5nIHBhY2thZ2VzLCBzZWUgdGhlIERhcnQgZ3VpZGUgZm9yCltjcmVhdGluZyBwYWNrYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL2NyZWF0ZS1saWJyYXJ5LXBhY2thZ2VzKQphbmQgdGhlIEZsdXR0ZXIgZ3VpZGUgZm9yCltkZXZlbG9waW5nIHBhY2thZ2VzIGFuZCBwbHVnaW5zXShodHRwczovL2ZsdXR0ZXIuZGV2L2RldmVsb3BpbmctcGFja2FnZXMpLgotLT4KClRPRE86IFB1dCBhIHNob3J0IGRlc2NyaXB0aW9uIG9mIHRoZSBwYWNrYWdlIGhlcmUgdGhhdCBoZWxwcyBwb3RlbnRpYWwgdXNlcnMKa25vdyB3aGV0aGVyIHRoaXMgcGFja2FnZSBtaWdodCBiZSB1c2VmdWwgZm9yIHRoZW0uCgojIyBGZWF0dXJlcwoKVE9ETzogTGlzdCB3aGF0IHlvdXIgcGFja2FnZSBjYW4gZG8uIE1heWJlIGluY2x1ZGUgaW1hZ2VzLCBnaWZzLCBvciB2aWRlb3MuCgojIyBHZXR0aW5nIHN0YXJ0ZWQKClRPRE86IExpc3QgcHJlcmVxdWlzaXRlcyBhbmQgcHJvdmlkZSBvciBwb2ludCB0byBpbmZvcm1hdGlvbiBvbiBob3cgdG8Kc3RhcnQgdXNpbmcgdGhlIHBhY2thZ2UuCgojIyBVc2FnZQoKVE9ETzogSW5jbHVkZSBzaG9ydCBhbmQgdXNlZnVsIGV4YW1wbGVzIGZvciBwYWNrYWdlIHVzZXJzLiBBZGQgbG9uZ2VyIGV4YW1wbGVzCnRvIGAvZXhhbXBsZWAgZm9sZGVyLgoKYGBgZGFydApjb25zdCBsaWtlID0gJ3NhbXBsZSc7CmBgYAoKIyMgQWRkaXRpb25hbCBpbmZvcm1hdGlvbgoKVE9ETzogVGVsbCB1c2VycyBtb3JlIGFib3V0IHRoZSBwYWNrYWdlOiB3aGVyZSB0byBmaW5kIG1vcmUgaW5mb3JtYXRpb24sIGhvdyB0bwpjb250cmlidXRlIHRvIHRoZSBwYWNrYWdlLCBob3cgdG8gZmlsZSBpc3N1ZXMsIHdoYXQgcmVzcG9uc2UgdGhleSBjYW4gZXhwZWN0CmZyb20gdGhlIHBhY2thZ2UgYXV0aG9ycywgYW5kIG1vcmUuCg==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "android",
  "description": "A new brick created with the Mason CLI.",
  "version": "0.0.1",
  "environment": {"mason": ">=0.1.0-dev.39 <0.1.0"},
  "readme": {
    "path": "README.md",
    "data":
        "IyBhbmRyb2lkCgpbIVtQb3dlcmVkIGJ5IE1hc29uXShodHRwczovL2ltZy5zaGllbGRzLmlvL2VuZHBvaW50P3VybD1odHRwcyUzQSUyRiUyRnRpbnl1cmwuY29tJTJGbWFzb24tYmFkZ2UpXShodHRwczovL2dpdGh1Yi5jb20vZmVsYW5nZWwvbWFzb24pCgpBIG5ldyBicmljayBjcmVhdGVkIHdpdGggdGhlIE1hc29uIENMSS4KCl9HZW5lcmF0ZWQgYnkgW21hc29uXVsxXSDwn6exXwoKIyMgR2V0dGluZyBTdGFydGVkIPCfmoAKClRoaXMgaXMgYSBzdGFydGluZyBwb2ludCBmb3IgYSBuZXcgYnJpY2suCkEgZmV3IHJlc291cmNlcyB0byBnZXQgeW91IHN0YXJ0ZWQgaWYgdGhpcyBpcyB5b3VyIGZpcnN0IGJyaWNrIHRlbXBsYXRlOgoKLSBbT2ZmaWNpYWwgTWFzb24gRG9jdW1lbnRhdGlvbl1bMl0KLSBbQ29kZSBnZW5lcmF0aW9uIHdpdGggTWFzb24gQmxvZ11bM10KLSBbVmVyeSBHb29kIExpdmVzdHJlYW06IEZlbGl4IEFuZ2Vsb3YgRGVtb3MgTWFzb25dWzRdCgpbMV06IGh0dHBzOi8vZ2l0aHViLmNvbS9mZWxhbmdlbC9tYXNvbgpbMl06IGh0dHBzOi8vZ2l0aHViLmNvbS9mZWxhbmdlbC9tYXNvbi90cmVlL21hc3Rlci9wYWNrYWdlcy9tYXNvbl9jbGkjcmVhZG1lClszXTogaHR0cHM6Ly92ZXJ5Z29vZC52ZW50dXJlcy9ibG9nL2NvZGUtZ2VuZXJhdGlvbi13aXRoLW1hc29uCls0XTogaHR0cHM6Ly95b3V0dS5iZS9HNFBUakE2dHBUVQo=",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjAuMQoKLSBUT0RPOiBEZXNjcmliZSBpbml0aWFsIHJlbGVhc2UuCg==",
    "type": "text"
  },
  "license": {
    "path": "LICENSE",
    "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
    "type": "text"
  },
  "vars": {
    "project_name": {
      "type": "string",
      "description": "The project name",
      "default": "my_app",
      "prompt": "What is the project name?"
    },
    "org_name": {
      "type": "string",
      "description": "The organization name",
      "default": "com.example",
      "prompt": "What is the organization name?"
    }
  }
});
