name: rapid_test_domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  dartz: ^0.10.1
  test: ^1.16.0
  rapid_domain:
    git:
      url: https://github.com/jtdLab/rapid.git
      path: packages/rapid/rapid/rapid_domain

dev_dependencies:
  lints: ^2.0.0

