name: rapid_test_domain
description: Contains domain test utility.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  rapid_domain:
    git:
      url: https://github.com/jtdLab/rapid.git
      path: packages/rapid/rapid/rapid_domain
  dartz: ^0.10.1
  test: ^1.22.2

dev_dependencies:
  lints: ^2.0.1
