name: {{project_name}}_domain{{#has_name}}_{{name}}{{/has_name}}
description: TODO
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  faker: ^2.1.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
  build_runner: ^2.4.6
  freezed: ^2.4.1
  build_verify: ^3.1.0
