name: {{project_name}}_infrastructure{{#has_name}}_{{name}}{{/has_name}}
description: TODO
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  injectable: ^2.1.1
  {{project_name}}_logging:
  {{project_name}}_domain{{#has_name}}_{{name}}{{/has_name}}:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  mocktail: ^0.3.0
  build_runner: ^2.4.4
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
