name: rapid_cli
description: Rapid is an architecture and corresponding CLI to develop Flutter apps fast.
version: 0.0.1-dev.1
repository: https://github.com/jtdLab/rapid/tree/main/packages/rapid_cli
issue_tracker: https://github.com/jtdLab/rapid/issues
homepage: https://docs.page/jtdlab/rapid
documentation: https://docs.page/jtdlab/rapid

executables:
  rapid:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  args: ^2.4.2
  mason: ^0.1.0-dev.50
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  dart_style: ^2.3.2
  code_builder: ^4.5.0
  collection: ^1.18.0
  analyzer: ^6.0.0
  io: ^1.0.4
  tabular: ^0.6.3+1
  propertylistserialization: ^1.3.0
  xml: ^6.3.0
  cli_launcher: ^0.3.1
  pub_updater: ^0.3.1
  ansi_styles: ^0.3.2+1
  platform: ^3.1.0
  cli_util: ^0.4.0
  file: ^6.1.4
  process: ^4.2.4
  pubspec: ^2.3.0
  pub_semver: ^2.1.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.5
  mocktail: ^1.0.0
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
