name: rapid_cli
description: Rapid is an architecture and corresponding CLI to develop Flutter apps fast.
version: 0.0.1
publish_to: none
executables:
  rapid:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  args: ^2.4.1
  mason: ^0.1.0-dev.49
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_edit: ^2.1.1
  dart_style: ^2.3.1
  code_builder: ^4.4.0
  collection: ^1.17.2
  analyzer: ^5.13.0
  io: ^1.0.4
  tabular: ^0.6.3+1
  propertylistserialization: ^1.3.0
  xml: ^6.3.0
  cli_launcher: ^0.3.0
  pub_updater: ^0.2.2
  ansi_styles: ^0.3.1
  platform: ^3.1.0
  cli_util: ^0.3.5
  file: ^6.1.0
  process: ^4.2.4

dependency_overrides:
  mason:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason
  mason_api:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason_api
  mason_logger:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason_logger

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
  mocktail: ^0.3.0
