name: rapid_cli
description: Rapid is an architecture and corresponding CLI to develop Flutter apps fast.
version: 0.0.1-dev.1
repository: https://github.com/jtdLab/rapid/tree/main/packages/rapid_cli
issue_tracker: https://github.com/jtdLab/rapid/issues
homepage: https://docs.page/jtdlab/rapid
documentation: https://docs.page/jtdlab/rapid

executables:
  rapid:

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.2.0
  ansi_styles: ^0.3.2+1
  args: ^2.4.2
  cli_launcher: ^0.3.1
  cli_util: ^0.4.0
  code_builder: ^4.5.0
  collection: ^1.18.0
  dart_style: ^2.3.2
  file: ^6.1.4
  io: ^1.0.4
  mason: ^0.1.0-dev.50
  meta: ^1.9.1
  path: ^1.8.3
  platform: ^3.1.1
  process: ^4.2.4
  propertylistserialization: ^1.3.0
  pub_semver: ^2.1.4
  pub_updater: ^0.3.1
  pubspec: ^2.3.0
  tabular: ^0.6.3+1
  xml: ^6.4.2
  yaml: ^3.1.2
  yaml_edit: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.24.6
