name: rapid_cli
description: Rapid is set of best practices, snippets and a cli to develop apps fast.
version: 0.0.1
publish_to: none
executables:
  rapid:

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  meta: ^1.9.0
  args: ^2.3.1
  mason:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_edit: ^2.0.3
  dart_style: ^2.2.4
  code_builder: ^4.4.0
  collection: ^1.17.1
  analyzer: ^5.4.0
  io: ^1.0.4
  tabular: ^0.6.3+1
  propertylistserialization: ^1.2.0
  xml: ^5.4.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
  mocktail: ^0.3.0
