name: rapid_cli
description: Rapid is an architecture and corresponding CLI to develop Flutter apps fast.
version: 0.0.1
publish_to: none
executables:
  rapid:

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  meta: ^1.9.1
  args: ^2.4.0
  mason: ^0.1.0-dev.47
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_edit: ^2.1.0
  dart_style: ^2.3.0
  code_builder: ^4.4.0
  collection: ^1.17.1
  analyzer: ^5.10.0
  io: ^1.0.4
  tabular: ^0.6.3+1
  propertylistserialization: ^1.3.0
  xml: ^6.2.2

dependency_overrides:
  mason:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason
  mason_api:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason_api
  mason_logger:
    git:
      url: https://github.com/jtdLab/mason.git
      path: packages/mason_logger

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  mocktail: ^0.3.0
