name: rapid_cli
description: Rapid is set of best practices, snippets and a cli to develop apps fast.
version: 0.0.1
homepage: https://github.com/CarstenV/rapid
executables:
  rapid:

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  meta: ^1.8.0
  args: ^2.3.1
  mason: 0.1.0-dev.39
  universal_io: ^2.0.4
  path: ^1.8.3
  yaml: ^3.1.1
  yaml_edit: ^2.0.3
  recase: ^4.1.0
  dart_style: ^2.2.4
  code_builder: ^4.4.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
  mocktail: ^0.3.0
