// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final uiPackageBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": ".gitignore",
      "data":
          "IyBNaXNjZWxsYW5lb3VzCiouY2xhc3MKKi5sb2cKKi5weWMKKi5zd3AKLkRTX1N0b3JlCi5hdG9tLwouYnVpbGRsb2cvCi5oaXN0b3J5Ci5zdm4vCm1pZ3JhdGVfd29ya2luZ19kaXIvCgojIEludGVsbGlKIHJlbGF0ZWQKKi5pbWwKKi5pcHIKKi5pd3MKLmlkZWEvCgojIFRoZSAudnNjb2RlIGZvbGRlciBjb250YWlucyBsYXVuY2ggY29uZmlndXJhdGlvbiBhbmQgdGFza3MgeW91IGNvbmZpZ3VyZSBpbgojIFZTIENvZGUgd2hpY2ggeW91IG1heSB3aXNoIHRvIGJlIGluY2x1ZGVkIGluIHZlcnNpb24gY29udHJvbCwgc28gdGhpcyBsaW5lCiMgaXMgY29tbWVudGVkIG91dCBieSBkZWZhdWx0LgojLnZzY29kZS8KCiMgRmx1dHRlci9EYXJ0L1B1YiByZWxhdGVkCioqL2RvYy9hcGkvCioqL2lvcy9GbHV0dGVyLy5sYXN0X2J1aWxkX2lkCi5kYXJ0X3Rvb2wvCi5mbHV0dGVyLXBsdWdpbnMKLmZsdXR0ZXItcGx1Z2lucy1kZXBlbmRlbmNpZXMKLnBhY2thZ2VzCi5wdWItY2FjaGUvCi5wdWIvCi9idWlsZC8KL2NvdmVyYWdlCg==",
      "type": "text"
    },
    {
      "path": "analysis_options.yaml",
      "data":
          "aW5jbHVkZTogcGFja2FnZTpmbHV0dGVyX2xpbnRzL2ZsdXR0ZXIueWFtbAoKIyBBZGRpdGlvbmFsIGluZm9ybWF0aW9uIGFib3V0IHRoaXMgZmlsZSBjYW4gYmUgZm91bmQgYXQKIyBodHRwczovL2RhcnQuZGV2L2d1aWRlcy9sYW5ndWFnZS9hbmFseXNpcy1vcHRpb25zCg==",
      "type": "text"
    },
    {
      "path": "CHANGELOG.md",
      "data": "IyMgMC4wLjEKCiogVE9ETzogRGVzY3JpYmUgaW5pdGlhbCByZWxlYXNlLgo=",
      "type": "text"
    },
    {
      "path": "lib/src/color_theme.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvZm91bmRhdGlvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCcgc2hvdyBUaGVtZUV4dGVuc2lvbjsKaW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvd2lkZ2V0cy5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnRoZW1lX3RhaWxvcl9hbm5vdGF0aW9uL3RoZW1lX3RhaWxvcl9hbm5vdGF0aW9uLmRhcnQnOwoKcGFydCAnY29sb3JfdGhlbWUudGFpbG9yLmRhcnQnOwoKQFRhaWxvcih0aGVtZUdldHRlcjogVGhlbWVHZXR0ZXIubm9uZSkKY2xhc3MgXyR7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUgewogIHN0YXRpYyBMaXN0PENvbG9yPiBwcmltYXJ5ID0gWwogICAgY29uc3QgQ29sb3IoMHhGRkZGRkZGRiksCiAgICBjb25zdCBDb2xvcigweEZGMjIyMjIyKQogIF07CgogIHN0YXRpYyBMaXN0PENvbG9yPiBzZWNvbmRhcnkgPSBbCiAgICBjb25zdCBDb2xvcigweEZGMzI3N0I0KSwKICAgIGNvbnN0IENvbG9yKDB4RkYyODRENzIpCiAgXTsKfQo=",
      "type": "text"
    },
    {
      "path": "lib/src/color_theme.tailor.dart",
      "data":
          "Ly8gY292ZXJhZ2U6aWdub3JlLWZpbGUKLy8gR0VORVJBVEVEIENPREUgLSBETyBOT1QgTU9ESUZZIEJZIEhBTkQKLy8gaWdub3JlX2Zvcl9maWxlOiB0eXBlPWxpbnQsIHVudXNlZF9lbGVtZW50LCB1bm5lY2Vzc2FyeV9jYXN0CgpwYXJ0IG9mICdjb2xvcl90aGVtZS5kYXJ0JzsKCi8vICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqCi8vIFRhaWxvckFubm90YXRpb25zR2VuZXJhdG9yCi8vICoqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqCgpjbGFzcyB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUgZXh0ZW5kcyBUaGVtZUV4dGVuc2lvbjx7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWU+CiAgICB3aXRoIERpYWdub3N0aWNhYmxlVHJlZU1peGluIHsKICBjb25zdCB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUoewogICAgcmVxdWlyZWQgdGhpcy5wcmltYXJ5LAogICAgcmVxdWlyZWQgdGhpcy5zZWNvbmRhcnksCiAgfSk7CgogIGZpbmFsIENvbG9yIHByaW1hcnk7CiAgZmluYWwgQ29sb3Igc2Vjb25kYXJ5OwoKICBzdGF0aWMgZmluYWwge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lIGxpZ2h0ID0ge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lKAogICAgcHJpbWFyeTogXyR7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUucHJpbWFyeVswXSwKICAgIHNlY29uZGFyeTogXyR7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUuc2Vjb25kYXJ5WzBdLAogICk7CgogIHN0YXRpYyBmaW5hbCB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUgZGFyayA9IHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZSgKICAgIHByaW1hcnk6IF8ke3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lLnByaW1hcnlbMV0sCiAgICBzZWNvbmRhcnk6IF8ke3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lLnNlY29uZGFyeVsxXSwKICApOwoKICBzdGF0aWMgZmluYWwgdGhlbWVzID0gWwogICAgbGlnaHQsCiAgICBkYXJrLAogIF07CgogIEBvdmVycmlkZQogIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZSBjb3B5V2l0aCh7CiAgICBDb2xvcj8gcHJpbWFyeSwKICAgIENvbG9yPyBzZWNvbmRhcnksCiAgfSkgewogICAgcmV0dXJuIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZSgKICAgICAgcHJpbWFyeTogcHJpbWFyeSA/PyB0aGlzLnByaW1hcnksCiAgICAgIHNlY29uZGFyeTogc2Vjb25kYXJ5ID8/IHRoaXMuc2Vjb25kYXJ5LAogICAgKTsKICB9CgogIEBvdmVycmlkZQogIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZSBsZXJwKAogICAgICBjb3ZhcmlhbnQgVGhlbWVFeHRlbnNpb248e3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lPj8gb3RoZXIsIGRvdWJsZSB0KSB7CiAgICBpZiAob3RoZXIgaXMhIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZSkgcmV0dXJuIHRoaXMgYXMge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lOwogICAgcmV0dXJuIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZSgKICAgICAgcHJpbWFyeTogQ29sb3IubGVycChwcmltYXJ5LCBvdGhlci5wcmltYXJ5LCB0KSEsCiAgICAgIHNlY29uZGFyeTogQ29sb3IubGVycChzZWNvbmRhcnksIG90aGVyLnNlY29uZGFyeSwgdCkhLAogICAgKTsKICB9CgogIEBvdmVycmlkZQogIHZvaWQgZGVidWdGaWxsUHJvcGVydGllcyhEaWFnbm9zdGljUHJvcGVydGllc0J1aWxkZXIgcHJvcGVydGllcykgewogICAgc3VwZXIuZGVidWdGaWxsUHJvcGVydGllcyhwcm9wZXJ0aWVzKTsKICAgIHByb3BlcnRpZXMKICAgICAgLi5hZGQoRGlhZ25vc3RpY3NQcm9wZXJ0eSgndHlwZScsICd7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUnKSkKICAgICAgLi5hZGQoRGlhZ25vc3RpY3NQcm9wZXJ0eSgncHJpbWFyeScsIHByaW1hcnkpKQogICAgICAuLmFkZChEaWFnbm9zdGljc1Byb3BlcnR5KCdzZWNvbmRhcnknLCBzZWNvbmRhcnkpKTsKICB9CgogIEBvdmVycmlkZQogIGJvb2wgb3BlcmF0b3IgPT0oT2JqZWN0IG90aGVyKSB7CiAgICByZXR1cm4gaWRlbnRpY2FsKHRoaXMsIG90aGVyKSB8fAogICAgICAgIChvdGhlci5ydW50aW1lVHlwZSA9PSBydW50aW1lVHlwZSAmJgogICAgICAgICAgICBvdGhlciBpcyB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUgJiYKICAgICAgICAgICAgY29uc3QgRGVlcENvbGxlY3Rpb25FcXVhbGl0eSgpLmVxdWFscyhwcmltYXJ5LCBvdGhlci5wcmltYXJ5KSAmJgogICAgICAgICAgICBjb25zdCBEZWVwQ29sbGVjdGlvbkVxdWFsaXR5KCkuZXF1YWxzKHNlY29uZGFyeSwgb3RoZXIuc2Vjb25kYXJ5KSk7CiAgfQoKICBAb3ZlcnJpZGUKICBpbnQgZ2V0IGhhc2hDb2RlIHsKICAgIHJldHVybiBPYmplY3QuaGFzaCgKICAgICAgcnVudGltZVR5cGUuaGFzaENvZGUsCiAgICAgIGNvbnN0IERlZXBDb2xsZWN0aW9uRXF1YWxpdHkoKS5oYXNoKHByaW1hcnkpLAogICAgICBjb25zdCBEZWVwQ29sbGVjdGlvbkVxdWFsaXR5KCkuaGFzaChzZWNvbmRhcnkpLAogICAgKTsKICB9Cn0K",
      "type": "text"
    },
    {
      "path": "lib/src/theme_extensions.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCcgc2hvdyBUaGVtZUV4dGVuc2lvbjsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fdWkve3twcm9qZWN0X25hbWV9fV91aS5kYXJ0JzsKCmZpbmFsIGxpZ2h0RXh0ZW5zaW9ucyA9IDxUaGVtZUV4dGVuc2lvbj5bCiAge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lLmxpZ2h0LApdOwoKZmluYWwgZGFya0V4dGVuc2lvbnMgPSA8VGhlbWVFeHRlbnNpb24+WwogIHt7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZS5kYXJrLApdOwo=",
      "type": "text"
    },
    {
      "path": "lib/{{project_name}}_ui.dart",
      "data":
          "Ly8vIFdpZGdldHMgYW5kIHRoZW1lcyBpbXBsZW1lbnRpbmcgcGxhdGZvcm0gaW5kZXBlbmRlbnQge3twcm9qZWN0X25hbWUudGl0bGVDYXNlKCl9fSBkZXNpZ24gbGFuZ3VhZ2UuCi8vLwovLy8gVG8gdXNlLCBpbXBvcnQgYHBhY2thZ2U6e3twcm9qZWN0X25hbWV9fV91aS97e3Byb2plY3RfbmFtZX19X3VpLmRhcnRgLgpsaWJyYXJ5IHt7cHJvamVjdF9uYW1lfX1fdWk7CgpleHBvcnQgJ3NyYy9jb2xvcl90aGVtZS5kYXJ0JzsKZXhwb3J0ICdzcmMvdGhlbWVfZXh0ZW5zaW9ucy5kYXJ0JzsK",
      "type": "text"
    },
    {
      "path": "LICENSE",
      "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
      "type": "text"
    },
    {
      "path": "pubspec.yaml",
      "data":
          "bmFtZToge3twcm9qZWN0X25hbWV9fV91aQpkZXNjcmlwdGlvbjogV2lkZ2V0cyBhbmQgdGhlbWVzIGltcGxlbWVudGluZyBwbGF0Zm9ybSBpbmRlcGVuZGVudCB7e3Byb2plY3RfbmFtZS50aXRsZUNhc2UoKX19IGRlc2lnbiBsYW5ndWFnZS4KdmVyc2lvbjogMC4wLjEKcHVibGlzaF90bzogbm9uZQoKZW52aXJvbm1lbnQ6CiAgc2RrOiAiPj0zLjAuMCA8NC4wLjAiCiAgZmx1dHRlcjogIj49My4xMC4wIgoKZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXI6CiAgICBzZGs6IGZsdXR0ZXIKICB0aGVtZV90YWlsb3JfYW5ub3RhdGlvbjogXjIuMC4wCgpkZXZfZGVwZW5kZW5jaWVzOgogIGZsdXR0ZXJfdGVzdDoKICAgIHNkazogZmx1dHRlcgogIGFsY2hlbWlzdDogXjAuNi4xCiAgYnVpbGRfcnVubmVyOiBeMi40LjUKICB0aGVtZV90YWlsb3I6IF4yLjAuMAogIGZsdXR0ZXJfZ2VuX3J1bm5lcjogXjUuMy4xCiAgZmx1dHRlcl9saW50czogXjIuMC4xCgojIFRoZSBmb2xsb3dpbmcgc2VjdGlvbiBpcyBzcGVjaWZpYyB0byB0aGUgRmx1dHRlckdlbiBwYWNrYWdlLgojIFNlZTogaHR0cHM6Ly9wdWIuZGV2L3BhY2thZ2VzL2ZsdXR0ZXJfZ2VuI2NvbmZpZ3VyYXRpb24tZmlsZQpmbHV0dGVyX2dlbjoKICBvdXRwdXQ6IGxpYi9zcmMvCiAgIyBUbyBhZGQgc3VwcG9ydCBmb3Igc3ZnIHZpYSBmbHV0dGVyX3N2ZyBwYWNrYWdlCiAgIyBpbnRlZ3JhdGlvbnM6CiAgIyAgIGZsdXR0ZXJfc3ZnOiB0cnVlCgogIGFzc2V0czoKICAgIG91dHB1dHM6CiAgICAgIHBhY2thZ2VfcGFyYW1ldGVyX2VuYWJsZWQ6IHRydWUKCiMgVGhlIGZvbGxvd2luZyBzZWN0aW9uIGlzIHNwZWNpZmljIHRvIEZsdXR0ZXIgcGFja2FnZXMuCmZsdXR0ZXI6CgogICMgVG8gYWRkIGFzc2V0cyB0byB5b3VyIHBhY2thZ2UsIGFkZCBhbiBhc3NldHMgc2VjdGlvbiwgbGlrZSB0aGlzOgogICMgYXNzZXRzOgogICMgICAtIGltYWdlcy9hX2RvdF9idXJyLmpwZWcKICAjICAgLSBpbWFnZXMvYV9kb3RfaGFtLmpwZWcKICAjCiAgIyBGb3IgZGV0YWlscyByZWdhcmRpbmcgYXNzZXRzIGluIHBhY2thZ2VzLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvYXNzZXRzLWFuZC1pbWFnZXMvI2Zyb20tcGFja2FnZXMKICAjCiAgIyBBbiBpbWFnZSBhc3NldCBjYW4gcmVmZXIgdG8gb25lIG9yIG1vcmUgcmVzb2x1dGlvbi1zcGVjaWZpYyAidmFyaWFudHMiLCBzZWUKICAjIGh0dHBzOi8vZmx1dHRlci5kZXYvYXNzZXRzLWFuZC1pbWFnZXMvI3Jlc29sdXRpb24tYXdhcmUKCiAgIyBUbyBhZGQgY3VzdG9tIGZvbnRzIHRvIHlvdXIgcGFja2FnZSwgYWRkIGEgZm9udHMgc2VjdGlvbiBoZXJlLAogICMgaW4gdGhpcyAiZmx1dHRlciIgc2VjdGlvbi4gRWFjaCBlbnRyeSBpbiB0aGlzIGxpc3Qgc2hvdWxkIGhhdmUgYQogICMgImZhbWlseSIga2V5IHdpdGggdGhlIGZvbnQgZmFtaWx5IG5hbWUsIGFuZCBhICJmb250cyIga2V5IHdpdGggYQogICMgbGlzdCBnaXZpbmcgdGhlIGFzc2V0IGFuZCBvdGhlciBkZXNjcmlwdG9ycyBmb3IgdGhlIGZvbnQuIEZvcgogICMgZXhhbXBsZToKICAjIGZvbnRzOgogICMgICAtIGZhbWlseTogU2NoeWxlcgogICMgICAgIGZvbnRzOgogICMgICAgICAgLSBhc3NldDogZm9udHMvU2NoeWxlci1SZWd1bGFyLnR0ZgogICMgICAgICAgLSBhc3NldDogZm9udHMvU2NoeWxlci1JdGFsaWMudHRmCiAgIyAgICAgICAgIHN0eWxlOiBpdGFsaWMKICAjICAgLSBmYW1pbHk6IFRyYWphbiBQcm8KICAjICAgICBmb250czoKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1RyYWphblByby50dGYKICAjICAgICAgIC0gYXNzZXQ6IGZvbnRzL1RyYWphblByb19Cb2xkLnR0ZgogICMgICAgICAgICB3ZWlnaHQ6IDcwMAogICMKICAjIEZvciBkZXRhaWxzIHJlZ2FyZGluZyBmb250cyBpbiBwYWNrYWdlcywgc2VlCiAgIyBodHRwczovL2ZsdXR0ZXIuZGV2L2N1c3RvbS1mb250cy8jZnJvbS1wYWNrYWdlcwo=",
      "type": "text"
    },
    {
      "path": "README.md",
      "data":
          "PCEtLQpUaGlzIFJFQURNRSBkZXNjcmliZXMgdGhlIHBhY2thZ2UuIElmIHlvdSBwdWJsaXNoIHRoaXMgcGFja2FnZSB0byBwdWIuZGV2LAp0aGlzIFJFQURNRSdzIGNvbnRlbnRzIGFwcGVhciBvbiB0aGUgbGFuZGluZyBwYWdlIGZvciB5b3VyIHBhY2thZ2UuCgpGb3IgaW5mb3JtYXRpb24gYWJvdXQgaG93IHRvIHdyaXRlIGEgZ29vZCBwYWNrYWdlIFJFQURNRSwgc2VlIHRoZSBndWlkZSBmb3IKW3dyaXRpbmcgcGFja2FnZSBwYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL3dyaXRpbmctcGFja2FnZS1wYWdlcykuCgpGb3IgZ2VuZXJhbCBpbmZvcm1hdGlvbiBhYm91dCBkZXZlbG9waW5nIHBhY2thZ2VzLCBzZWUgdGhlIERhcnQgZ3VpZGUgZm9yCltjcmVhdGluZyBwYWNrYWdlc10oaHR0cHM6Ly9kYXJ0LmRldi9ndWlkZXMvbGlicmFyaWVzL2NyZWF0ZS1saWJyYXJ5LXBhY2thZ2VzKQphbmQgdGhlIEZsdXR0ZXIgZ3VpZGUgZm9yCltkZXZlbG9waW5nIHBhY2thZ2VzIGFuZCBwbHVnaW5zXShodHRwczovL2ZsdXR0ZXIuZGV2L2RldmVsb3BpbmctcGFja2FnZXMpLgotLT4KClRPRE86IFB1dCBhIHNob3J0IGRlc2NyaXB0aW9uIG9mIHRoZSBwYWNrYWdlIGhlcmUgdGhhdCBoZWxwcyBwb3RlbnRpYWwgdXNlcnMKa25vdyB3aGV0aGVyIHRoaXMgcGFja2FnZSBtaWdodCBiZSB1c2VmdWwgZm9yIHRoZW0uCgojIyBGZWF0dXJlcwoKVE9ETzogTGlzdCB3aGF0IHlvdXIgcGFja2FnZSBjYW4gZG8uIE1heWJlIGluY2x1ZGUgaW1hZ2VzLCBnaWZzLCBvciB2aWRlb3MuCgojIyBHZXR0aW5nIHN0YXJ0ZWQKClRPRE86IExpc3QgcHJlcmVxdWlzaXRlcyBhbmQgcHJvdmlkZSBvciBwb2ludCB0byBpbmZvcm1hdGlvbiBvbiBob3cgdG8Kc3RhcnQgdXNpbmcgdGhlIHBhY2thZ2UuCgojIyBVc2FnZQoKVE9ETzogSW5jbHVkZSBzaG9ydCBhbmQgdXNlZnVsIGV4YW1wbGVzIGZvciBwYWNrYWdlIHVzZXJzLiBBZGQgbG9uZ2VyIGV4YW1wbGVzCnRvIGAvZXhhbXBsZWAgZm9sZGVyLgoKYGBgZGFydApjb25zdCBsaWtlID0gJ3NhbXBsZSc7CmBgYAoKIyMgQWRkaXRpb25hbCBpbmZvcm1hdGlvbgoKVE9ETzogVGVsbCB1c2VycyBtb3JlIGFib3V0IHRoZSBwYWNrYWdlOiB3aGVyZSB0byBmaW5kIG1vcmUgaW5mb3JtYXRpb24sIGhvdyB0bwpjb250cmlidXRlIHRvIHRoZSBwYWNrYWdlLCBob3cgdG8gZmlsZSBpc3N1ZXMsIHdoYXQgcmVzcG9uc2UgdGhleSBjYW4gZXhwZWN0CmZyb20gdGhlIHBhY2thZ2UgYXV0aG9ycywgYW5kIG1vcmUuCg==",
      "type": "text"
    },
    {
      "path": "test/mocks.dart",
      "data": "Ly8gVE9ETzogYWRkIG1vY2tzIGFuZCBmYWtlcyBoZXJlCg==",
      "type": "text"
    },
    {
      "path": "test/src/color_theme_test.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OnVpJzsKCmltcG9ydCAncGFja2FnZTpmbHV0dGVyX3Rlc3QvZmx1dHRlcl90ZXN0LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6e3twcm9qZWN0X25hbWV9fV91aS9zcmMvY29sb3JfdGhlbWUuZGFydCc7Cgp2b2lkIG1haW4oKSB7CiAgZ3JvdXAoJ3t7cHJvamVjdF9uYW1lLnBhc2NhbENhc2UoKX19Q29sb3JUaGVtZScsICgpIHsKICAgIGdyb3VwKCcubGlnaHQnLCAoKSB7CiAgICAgIGZpbmFsIGxpZ2h0ID0ge3twcm9qZWN0X25hbWUucGFzY2FsQ2FzZSgpfX1Db2xvclRoZW1lLmxpZ2h0OwoKICAgICAgdGVzdCgnLnByaW1hcnknLCAoKSB7CiAgICAgICAgZXhwZWN0KGxpZ2h0LnByaW1hcnksIGNvbnN0IENvbG9yKDB4RkZGRkZGRkYpKTsKICAgICAgfSk7CgogICAgICB0ZXN0KCcuc2Vjb25kYXJ5JywgKCkgewogICAgICAgIGV4cGVjdChsaWdodC5zZWNvbmRhcnksIGNvbnN0IENvbG9yKDB4RkYzMjc3QjQpKTsKICAgICAgfSk7CiAgICB9KTsKCiAgICBncm91cCgnLmRhcmsnLCAoKSB7CiAgICAgIGZpbmFsIGRhcmsgPSB7e3Byb2plY3RfbmFtZS5wYXNjYWxDYXNlKCl9fUNvbG9yVGhlbWUuZGFyazsKCiAgICAgIHRlc3QoJy5wcmltYXJ5JywgKCkgewogICAgICAgIGV4cGVjdChkYXJrLnByaW1hcnksIGNvbnN0IENvbG9yKDB4RkYyMjIyMjIpKTsKICAgICAgfSk7CgogICAgICB0ZXN0KCcuc2Vjb25kYXJ5JywgKCkgewogICAgICAgIGV4cGVjdChkYXJrLnNlY29uZGFyeSwgY29uc3QgQ29sb3IoMHhGRjI4NEQ3MikpOwogICAgICB9KTsKICAgIH0pOwogIH0pOwp9Cg==",
      "type": "text"
    },
    {
      "path": "test/src/helpers/helpers.dart",
      "data": "ZXhwb3J0ICdwdW1wX2FwcC5kYXJ0JzsK",
      "type": "text"
    },
    {
      "path": "test/src/helpers/pump_app.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZsdXR0ZXIvbWF0ZXJpYWwuZGFydCc7CmltcG9ydCAncGFja2FnZTpmbHV0dGVyX3Rlc3QvZmx1dHRlcl90ZXN0LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6e3twcm9qZWN0X25hbWV9fV91aS9zcmMvdGhlbWVfZXh0ZW5zaW9ucy5kYXJ0JzsKCi8vLyBXcmFwcyBbd2lkZ2V0XSB3aXRoIGEgZnVsbHkgZnVuY3Rpb25hbCBbTWF0ZXJpYWxBcHBdLgovLy8KLy8vIFVzZSB0aGUgW2xvY2FsZV0gcGFyYW1ldGVyIHRvIHNldCB0aGUgbGFuZ3VhZ2Ugb2YgdGhlIGFwcC4KLy8vCi8vLyBVc2UgdGhlIFt0aGVtZU1vZGVdIHBhcmFtZXRlciB0byBjdXN0b21pemUgdGhlIGFwcCdzIGFwcGVhcmFuY2UuCldpZGdldCBhcHBXcmFwcGVyKHsKICBMb2NhbGU/IGxvY2FsZSwKICBUaGVtZU1vZGU/IHRoZW1lTW9kZSwKICByZXF1aXJlZCBXaWRnZXQgd2lkZ2V0LAp9KSB7CiAgcmV0dXJuIE1hdGVyaWFsQXBwKAogICAgbG9jYWxlOiBsb2NhbGUgPz8gY29uc3QgTG9jYWxlKCdlbicpLAogICAgdGhlbWVNb2RlOiB0aGVtZU1vZGUsCiAgICB0aGVtZTogVGhlbWVEYXRhKGV4dGVuc2lvbnM6IGxpZ2h0RXh0ZW5zaW9ucyksCiAgICBkYXJrVGhlbWU6IFRoZW1lRGF0YShleHRlbnNpb25zOiBkYXJrRXh0ZW5zaW9ucyksCiAgICBob21lOiB3aWRnZXQsCiAgKTsKfQoKZXh0ZW5zaW9uIFdpZGdldFRlc3Rlclggb24gV2lkZ2V0VGVzdGVyIHsKICAvLy8gUHVtcCBbd2lkZ2V0XSB3cmFwcGVkIHdpdGggYSBbTWF0ZXJpYWxBcHBdLgogIC8vLwogIC8vLyBTcGVjaWZ5IFtsb2NhbGVdIHRvIHRlc3QgbG9jYWxpemF0aW9uLgogIC8vLwogIC8vLyBTcGVjaWZ5IFticmlnaHRuZXNzXSB0byB0ZXN0IGRpZmZlcmVudCBhcHBlYXJhbmNlcy4KICBGdXR1cmU8dm9pZD4gcHVtcEFwcCgKICAgIFdpZGdldCB3aWRnZXQsIHsKICAgIExvY2FsZT8gbG9jYWxlLAogICAgVGhlbWVNb2RlPyB0aGVtZU1vZGUsCiAgfSkgPT4KICAgICAgcHVtcFdpZGdldCgKICAgICAgICBhcHBXcmFwcGVyKAogICAgICAgICAgbG9jYWxlOiBsb2NhbGUsCiAgICAgICAgICB0aGVtZU1vZGU6IHRoZW1lTW9kZSwKICAgICAgICAgIHdpZGdldDogd2lkZ2V0LAogICAgICAgICksCiAgICAgICk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "ui_package",
  "description": "A brick generating the ui package of a Rapid project.",
  "version": "0.1.0",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "readme": {
    "path": "README.md",
    "data": "IyB1aV9wYWNrYWdlCgpUT0RPCg==",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMAoKLSBUT0RPOiBEZXNjcmliZSBpbml0aWFsIHJlbGVhc2UuCg==",
    "type": "text"
  },
  "vars": {
    "project_name": {"type": "string", "description": "The project name"}
  }
});
