// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final valueObjectBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/src/{{{output_dir}}}/{{name.snakeCase()}}.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZha2VyL2Zha2VyLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6ZnJlZXplZF9hbm5vdGF0aW9uL2ZyZWV6ZWRfYW5ub3RhdGlvbi5kYXJ0JzsKCnBhcnQgJ3t7bmFtZS5zbmFrZUNhc2UoKX19LmZyZWV6ZWQuZGFydCc7CgovLy8ge0B0ZW1wbGF0ZSB7e25hbWUuc25ha2VDYXNlKCl9fX0KLy8vICoqKlZhbGlkKioqOgovLy8KLy8vIFRPRE86IHZhbGlkIGNhc2VzCi8vLwovLy8gLS0tCi8vLwovLy8gKioqSW52YWxpZCoqKjoKLy8vCi8vLyBUT0RPOiBpbnZhbGlkIGNhc2VzCi8vLyB7QGVuZHRlbXBsYXRlfQpjbGFzcyB7e25hbWUucGFzY2FsQ2FzZSgpfX17e3tnZW5lcmljc319fSBleHRlbmRzIFZhbHVlT2JqZWN0PHt7e3R5cGV9fX0+IHsKICBAb3ZlcnJpZGUKICBmaW5hbCBFaXRoZXI8e3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZSwge3t7dHlwZX19fT4gdmFsdWU7CgogIC8vLyB7QG1hY3JvIHt7bmFtZS5zbmFrZUNhc2UoKX19fQogIGZhY3Rvcnkge3tuYW1lLnBhc2NhbENhc2UoKX19KHt7e3R5cGV9fX0gcmF3KSB7CiAgICByZXR1cm4ge3tuYW1lLnBhc2NhbENhc2UoKX19Ll8oX3ZhbGlkYXRlKHJhdykpOwogIH0KCiAgLy8vIFJldHVybnMgYSByYW5kb20gaW5zdGFuY2UuCiAgLy8vCiAgLy8vIElmIFtpc1ZhbGlkXSBob2xkcyB2YWx1ZSBlbHNlIGhvbGRzIGZhaWx1cmUuCiAgZmFjdG9yeSB7e25hbWUucGFzY2FsQ2FzZSgpfX0ucmFuZG9tKHtib29sIGlzVmFsaWQgPSB0cnVlfSkgewogICAgZmluYWwgZmFrZXIgPSBGYWtlcigpOwoKICAgIGlmIChpc1ZhbGlkKSB7CiAgICAgIC8vIFRPRE86IGltcGxlbWVudDogcmV0dXJuIGluc3RhbmNlIGhvbGRpbmcgcmFuZG9tIHZhbHVlCiAgICAgIHRocm93IFVuaW1wbGVtZW50ZWRFcnJvcigpOwogICAgfSBlbHNlIHsKICAgICAgLy8gVE9ETzogaW1wbGVtZW50OiByZXR1cm4gaW5zdGFuY2UgaG9sZGluZyByYW5kb20gZmFpbHVyZQogICAgICB0aHJvdyBVbmltcGxlbWVudGVkRXJyb3IoKTsKICAgIH0KICB9CgogIGNvbnN0IHt7bmFtZS5wYXNjYWxDYXNlKCl9fS5fKHRoaXMudmFsdWUpOwoKICAvLy8gKioqUmV0dXJucyBbcmF3XSoqKjoKICAvLy8KICAvLy8gVE9ETzogdmFsaWQgY2FzZXMKICAvLy8KICAvLy8gLS0tCiAgLy8vCiAgLy8vICoqKlJldHVybnMgW3t7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmVdKioqOgogIC8vLwogIC8vLyBUT0RPOiBpbnZhbGlkIGNhc2VzCiAgc3RhdGljIEVpdGhlcjx7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlLCB7e3t0eXBlfX19PiBfdmFsaWRhdGV7e3tnZW5lcmljc319fSh7e3t0eXBlfX19IHJhdykgewogICAgLy8gVE9ETzogaW1wbGVtZW50IHZhbGlkYXRpb24KICAgIHRocm93IFVuaW1wbGVtZW50ZWRFcnJvcigpOwogIH0KCiAgQG92ZXJyaWRlCiAgU3RyaW5nIHRvU3RyaW5nKCkgPT4gdmFsdWUuZm9sZCgKICAgICAgICAoZmFpbHVyZSkgPT4gJ3t7bmFtZS5wYXNjYWxDYXNlKCl9fShmYWlsdXJlOiAkZmFpbHVyZSknLAogICAgICAgICh2YWx1ZSkgPT4gJ3t7bmFtZS5wYXNjYWxDYXNlKCl9fSh2YWx1ZTogJHZhbHVlKScsCiAgICAgICk7Cn0KCi8vLyBbVmFsdWVGYWlsdXJlXSB1bmlvbiB0aGF0IGJlbG9uZ3MgdG8gW3t7bmFtZS5wYXNjYWxDYXNlKCl9fV0uCkBmcmVlemVkCnNlYWxlZCBjbGFzcyB7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJle3t7Z2VuZXJpY3N9fX0gZXh0ZW5kcyBWYWx1ZUZhaWx1cmU8e3t7dHlwZX19fT4KICAgIHdpdGggXyR7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJle3t7Z2VuZXJpY3N9fX0gewogIGNvbnN0IGZhY3Rvcnkge3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZS5mYWlsdXJlQSh7CiAgICByZXF1aXJlZCB7e3t0eXBlfX19IGZhaWxlZFZhbHVlLAogIH0pID0ge3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZUE7CiAgLy8gVE9ETzogYWRkIG1vcmUgZmFpbHVyZSBjYXNlcwp9Cg==",
      "type": "text"
    },
    {
      "path": "test/src/{{{output_dir}}}/{{name.snakeCase()}}_test.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnRlc3QvdGVzdC5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fZG9tYWlue3sjaGFzX3N1Yl9kb21haW5fbmFtZX19X3t7c3ViX2RvbWFpbl9uYW1lfX17ey9oYXNfc3ViX2RvbWFpbl9uYW1lfX0vc3Jje3teb3V0cHV0X2Rpcl9pc19jd2R9fS97e3tvdXRwdXRfZGlyfX19e3svb3V0cHV0X2Rpcl9pc19jd2R9fS97e25hbWUuc25ha2VDYXNlKCl9fS5kYXJ0JzsKCnZvaWQgbWFpbigpIHsKICBncm91cCgne3tuYW1lLnBhc2NhbENhc2UoKX19JywgKCkgewogICAgZ3JvdXAoJy4oKScsICgpIHsKICAgICAgZ3JvdXAoJyh2YWxpZCknLCAoKSB7CiAgICAgICAgdGVzdCgnJywgKCkgewogICAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgICAgLy8gZmluYWwge3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUucGFzY2FsQ2FzZSgpfX0oLyogVE9ETyB2YWxpZCAqLyk7CgogICAgICAgICAgLy8gQXNzZXJ0CiAgICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udmFsdWUsIHJpZ2h0KC8qIFRPRE8gdmFsaWQgKi8pKTsKICAgICAgICB9KTsKCiAgICAgICAgLy8gVE9ETzogbW9yZSB2YWxpZCBjYXNlcwogICAgICB9KTsKCiAgICAgIGdyb3VwKCcoaW52YWxpZCknLCAoKSB7CiAgICAgICAgdGVzdCgnJywgKCkgewogICAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgICAgLy8gZmluYWwge3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUucGFzY2FsQ2FzZSgpfX0oLyogVE9ETyBpbnZhbGlkICovKTsKCiAgICAgICAgICAvLyBBc3NlcnQKICAgICAgICAgIC8vIGV4cGVjdCh7e25hbWUuY2FtZWxDYXNlKCl9fS52YWx1ZSwgbGVmdCgvKiBUT0RPIHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmUgKi8pKTsKICAgICAgICB9KTsKCiAgICAgICAgLy8gVE9ETzogbW9yZSBpbnZhbGlkIGNhc2VzCiAgICAgIH0pOwogICAgfSk7CgogICAgZ3JvdXAoJy5yYW5kb20oKScsICgpIHsKICAgICAgdGVzdCgnKHZhbGlkKScsICgpIHsKICAgICAgICAvLyBBcnJhbmdlICsgQWN0CiAgICAgICAgLy8gZmluYWwge3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUucGFzY2FsQ2FzZSgpfX0ucmFuZG9tKGlzVmFsaWQ6IHRydWUpOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udmFsdWUsIHJpZ2h0KC8qIFRPRE8gdmFsaWQgKi8pKTsKICAgICAgfSk7CgogICAgICB0ZXN0KCcoaW52YWxpZCknLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgIC8vIGZpbmFsIHt7bmFtZS5jYW1lbENhc2UoKX19ID0ge3tuYW1lLnBhc2NhbENhc2UoKX19LnJhbmRvbShpc1ZhbGlkOiBmYWxzZSk7CgogICAgICAgIC8vIEFzc2VydAogICAgICAgIC8vIGV4cGVjdCh7e25hbWUuY2FtZWxDYXNlKCl9fS52YWx1ZSwgbGVmdCgvKiBUT0RPIHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmUgKi8pKTsKICAgICAgfSk7CiAgICB9KTsKCiAgICBncm91cCgnLnRvU3RyaW5nKCknLCAoKSB7CiAgICAgIHRlc3QoJyh2YWxpZCknLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgIC8vIGZpbmFsIHt7bmFtZS5jYW1lbENhc2UoKX19ID0ge3tuYW1lLnBhc2NhbENhc2UoKX19KC8qIFRPRE8gdmFsaWQgKi8pOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udG9TdHJpbmcoKSwgLyogVE9ETyAqLyk7CiAgICAgIH0pOwoKICAgICAgdGVzdCgnKGludmFsaWQpJywgKCkgewogICAgICAgIC8vIEFycmFuZ2UgKyBBY3QKICAgICAgICAvLyBmaW5hbCB7e25hbWUuY2FtZWxDYXNlKCl9fSA9IHt7bmFtZS5wYXNjYWxDYXNlKCl9fSgvKiBUT0RPIGludmFsaWQgKi8pOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udG9TdHJpbmcoKSwgLyogVE9ETyAqLyk7CiAgICAgIH0pOwogICAgfSk7CiAgfSk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [
    {
      "path": "pre_gen.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOm1hc29uL21hc29uLmRhcnQnOwoKdm9pZCBydW4oSG9va0NvbnRleHQgY29udGV4dCkgewogIGZpbmFsIG91dHB1dERpciA9IGNvbnRleHQudmFyc1snb3V0cHV0X2RpciddOwogIGZpbmFsIHN1YkRvbWFpbk5hbWUgPSBjb250ZXh0LnZhcnNbJ3N1Yl9kb21haW5fbmFtZSddOwogIGNvbnRleHQudmFycyA9IHsKICAgIC4uLmNvbnRleHQudmFycywKICAgICdvdXRwdXRfZGlyX2lzX2N3ZCc6IG91dHB1dERpciA9PSAnLicsCiAgICAnaGFzX3N1Yl9kb21haW5fbmFtZSc6IHN1YkRvbWFpbk5hbWUgIT0gbnVsbCwKICB9Owp9Cg==",
      "type": "text"
    },
    {
      "path": "pubspec.yaml",
      "data":
          "bmFtZTogdmFsdWVfb2JqZWN0X2hvb2tzCgplbnZpcm9ubWVudDoKICBzZGs6ICI+PTMuMC4wIDw0LjAuMCIKCmRlcGVuZGVuY2llczoKICBtYXNvbjogYW55Cg==",
      "type": "text"
    }
  ],
  "name": "value_object",
  "description":
      "A brick generating a value object of a domain package of a Rapid project.",
  "version": "0.1.0",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "readme": {
    "path": "README.md",
    "data": "IyB2YWx1ZV9vYmplY3QKClRPRE8=",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMAoKLSBUT0RPOiBEZXNjcmliZSBpbml0aWFsIHJlbGVhc2UuCg==",
    "type": "text"
  },
  "vars": {
    "project_name": {"type": "string"},
    "name": {"type": "string"},
    "output_dir": {"type": "string"},
    "output_dir_is_cwd": {"type": "boolean"},
    "type": {"type": "string"},
    "generics": {"type": "string"},
    "has_sub_domain_name": {"type": "boolean"},
    "sub_domain_name": {"type": "string"}
  }
});
