// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final valueObjectBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/src/{{{output_dir}}}/{{name.snakeCase()}}.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmZha2VyL2Zha2VyLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6ZnJlZXplZF9hbm5vdGF0aW9uL2ZyZWV6ZWRfYW5ub3RhdGlvbi5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnJhcGlkX2RvbWFpbi9yYXBpZF9kb21haW4uZGFydCc7CgpwYXJ0ICd7e25hbWUuc25ha2VDYXNlKCl9fS5mcmVlemVkLmRhcnQnOwoKLy8vIHtAdGVtcGxhdGUge3tuYW1lLnNuYWtlQ2FzZSgpfX19Ci8vLyAqKipWYWxpZCoqKjoKLy8vCi8vLyBUT0RPOiB2YWxpZCBjYXNlcwovLy8KLy8vIC0tLQovLy8KLy8vICoqKkludmFsaWQqKio6Ci8vLwovLy8gVE9ETzogaW52YWxpZCBjYXNlcwovLy8ge0BlbmR0ZW1wbGF0ZX0KY2xhc3Mge3tuYW1lLnBhc2NhbENhc2UoKX19e3t7Z2VuZXJpY3N9fX0gZXh0ZW5kcyBWYWx1ZU9iamVjdDx7e3t0eXBlfX19PiB7CiAgQG92ZXJyaWRlCiAgZmluYWwgRWl0aGVyPHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmUsIHt7e3R5cGV9fX0+IHZhbHVlOwoKICAvLy8ge0BtYWNybyB7e25hbWUuc25ha2VDYXNlKCl9fX0KICBmYWN0b3J5IHt7bmFtZS5wYXNjYWxDYXNlKCl9fSh7e3t0eXBlfX19IHJhdykgewogICAgcmV0dXJuIHt7bmFtZS5wYXNjYWxDYXNlKCl9fS5fKF92YWxpZGF0ZShyYXcpKTsKICB9CgogIC8vLyBSZXR1cm5zIGEgcmFuZG9tIGluc3RhbmNlLgogIC8vLwogIC8vLyBJZiBbaXNWYWxpZF0gaG9sZHMgdmFsdWUgZWxzZSBob2xkcyBmYWlsdXJlLgogIGZhY3Rvcnkge3tuYW1lLnBhc2NhbENhc2UoKX19LnJhbmRvbSh7Ym9vbCBpc1ZhbGlkID0gdHJ1ZX0pIHsKICAgIGZpbmFsIGZha2VyID0gRmFrZXIoKTsKCiAgICBpZiAoaXNWYWxpZCkgewogICAgICAvLyBUT0RPOiBpbXBsZW1lbnQ6IHJldHVybiBpbnN0YW5jZSBob2xkaW5nIHJhbmRvbSB2YWx1ZQogICAgICB0aHJvdyBVbmltcGxlbWVudGVkRXJyb3IoKTsKICAgIH0gZWxzZSB7CiAgICAgIC8vIFRPRE86IGltcGxlbWVudDogcmV0dXJuIGluc3RhbmNlIGhvbGRpbmcgcmFuZG9tIGZhaWx1cmUKICAgICAgdGhyb3cgVW5pbXBsZW1lbnRlZEVycm9yKCk7CiAgICB9CiAgfQoKICBjb25zdCB7e25hbWUucGFzY2FsQ2FzZSgpfX0uXyh0aGlzLnZhbHVlKTsKCiAgLy8vICoqKlJldHVybnMgW3Jhd10qKio6CiAgLy8vCiAgLy8vIFRPRE86IHZhbGlkIGNhc2VzCiAgLy8vCiAgLy8vIC0tLQogIC8vLwogIC8vLyAqKipSZXR1cm5zIFt7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlXSoqKjoKICAvLy8KICAvLy8gVE9ETzogaW52YWxpZCBjYXNlcwogIHN0YXRpYyBFaXRoZXI8e3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZSwge3t7dHlwZX19fT4gX3ZhbGlkYXRle3t7Z2VuZXJpY3N9fX0oe3t7dHlwZX19fSByYXcpIHsKICAgIC8vIFRPRE86IGltcGxlbWVudCB2YWxpZGF0aW9uCiAgICB0aHJvdyBVbmltcGxlbWVudGVkRXJyb3IoKTsKICB9CgogIEBvdmVycmlkZQogIFN0cmluZyB0b1N0cmluZygpID0+IHZhbHVlLmZvbGQoCiAgICAgICAgKGZhaWx1cmUpID0+ICd7e25hbWUucGFzY2FsQ2FzZSgpfX0oZmFpbHVyZTogJGZhaWx1cmUpJywKICAgICAgICAodmFsdWUpID0+ICd7e25hbWUucGFzY2FsQ2FzZSgpfX0odmFsdWU6ICR2YWx1ZSknLAogICAgICApOwp9CgovLy8gW1ZhbHVlRmFpbHVyZV0gdW5pb24gdGhhdCBiZWxvbmdzIHRvIFt7e25hbWUucGFzY2FsQ2FzZSgpfX1dLgpAZnJlZXplZApzZWFsZWQgY2xhc3Mge3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZXt7e2dlbmVyaWNzfX19IGV4dGVuZHMgVmFsdWVGYWlsdXJlPHt7e3R5cGV9fX0+CiAgICB3aXRoIF8ke3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZXt7e2dlbmVyaWNzfX19IHsKICBjb25zdCBmYWN0b3J5IHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmUuZmFpbHVyZUEoewogICAgcmVxdWlyZWQge3t7dHlwZX19fSBmYWlsZWRWYWx1ZSwKICB9KSA9IHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmVBOwogIC8vIFRPRE86IGFkZCBtb3JlIGZhaWx1cmUgY2FzZXMKfQo=",
      "type": "text"
    },
    {
      "path": "test/src/{{{output_dir}}}/{{name.snakeCase()}}_test.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnRlc3QvdGVzdC5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX1fZG9tYWlue3sjaGFzX3N1Yl9kb21haW5fbmFtZX19X3t7c3ViX2RvbWFpbl9uYW1lfX17ey9oYXNfc3ViX2RvbWFpbl9uYW1lfX0vc3Jje3teb3V0cHV0X2Rpcl9pc19jd2R9fS97e3tvdXRwdXRfZGlyfX19e3svb3V0cHV0X2Rpcl9pc19jd2R9fS97e25hbWUuc25ha2VDYXNlKCl9fS5kYXJ0JzsKCnZvaWQgbWFpbigpIHsKICBncm91cCgne3tuYW1lLnBhc2NhbENhc2UoKX19JywgKCkgewogICAgZ3JvdXAoJy4oKScsICgpIHsKICAgICAgZ3JvdXAoJyh2YWxpZCknLCAoKSB7CiAgICAgICAgdGVzdCgnJywgKCkgewogICAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgICAgLy8gZmluYWwge3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUucGFzY2FsQ2FzZSgpfX0oLyogVE9ETyB2YWxpZCAqLyk7CgogICAgICAgICAgLy8gQXNzZXJ0CiAgICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udmFsdWUsIHJpZ2h0KC8qIFRPRE8gdmFsaWQgKi8pKTsKICAgICAgICB9KTsKCiAgICAgICAgLy8gVE9ETzogbW9yZSB2YWxpZCBjYXNlcwogICAgICB9KTsKCiAgICAgIGdyb3VwKCcoaW52YWxpZCknLCAoKSB7CiAgICAgICAgdGVzdCgnJywgKCkgewogICAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgICAgLy8gZmluYWwge3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUucGFzY2FsQ2FzZSgpfX0oLyogVE9ETyBpbnZhbGlkICovKTsKCiAgICAgICAgICAvLyBBc3NlcnQKICAgICAgICAgIC8vIGV4cGVjdCh7e25hbWUuY2FtZWxDYXNlKCl9fS52YWx1ZSwgbGVmdCgvKiBUT0RPIHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmUgKi8pKTsKICAgICAgICB9KTsKCiAgICAgICAgLy8gVE9ETzogbW9yZSBpbnZhbGlkIGNhc2VzCiAgICAgIH0pOwogICAgfSk7CgogICAgZ3JvdXAoJy5yYW5kb20oKScsICgpIHsKICAgICAgdGVzdCgnKHZhbGlkKScsICgpIHsKICAgICAgICAvLyBBcnJhbmdlICsgQWN0CiAgICAgICAgLy8gZmluYWwge3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUucGFzY2FsQ2FzZSgpfX0ucmFuZG9tKGlzVmFsaWQ6IHRydWUpOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udmFsdWUsIHJpZ2h0KC8qIFRPRE8gdmFsaWQgKi8pKTsKICAgICAgfSk7CgogICAgICB0ZXN0KCcoaW52YWxpZCknLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgIC8vIGZpbmFsIHt7bmFtZS5jYW1lbENhc2UoKX19ID0ge3tuYW1lLnBhc2NhbENhc2UoKX19LnJhbmRvbShpc1ZhbGlkOiBmYWxzZSk7CgogICAgICAgIC8vIEFzc2VydAogICAgICAgIC8vIGV4cGVjdCh7e25hbWUuY2FtZWxDYXNlKCl9fS52YWx1ZSwgbGVmdCgvKiBUT0RPIHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmUgKi8pKTsKICAgICAgfSk7CiAgICB9KTsKCiAgICBncm91cCgnLnRvU3RyaW5nKCknLCAoKSB7CiAgICAgIHRlc3QoJyh2YWxpZCknLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZSArIEFjdAogICAgICAgIC8vIGZpbmFsIHt7bmFtZS5jYW1lbENhc2UoKX19ID0ge3tuYW1lLnBhc2NhbENhc2UoKX19KC8qIFRPRE8gdmFsaWQgKi8pOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udG9TdHJpbmcoKSwgLyogVE9ETyAqLyk7CiAgICAgIH0pOwoKICAgICAgdGVzdCgnKGludmFsaWQpJywgKCkgewogICAgICAgIC8vIEFycmFuZ2UgKyBBY3QKICAgICAgICAvLyBmaW5hbCB7e25hbWUuY2FtZWxDYXNlKCl9fSA9IHt7bmFtZS5wYXNjYWxDYXNlKCl9fSgvKiBUT0RPIGludmFsaWQgKi8pOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3Qoe3tuYW1lLmNhbWVsQ2FzZSgpfX0udG9TdHJpbmcoKSwgLyogVE9ETyAqLyk7CiAgICAgIH0pOwogICAgfSk7CiAgfSk7Cn0K",
      "type": "text"
    }
  ],
  "hooks": [
    {
      "path": "pre_gen.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOm1hc29uL21hc29uLmRhcnQnOwoKdm9pZCBydW4oSG9va0NvbnRleHQgY29udGV4dCkgewogIGZpbmFsIG91dHB1dERpciA9IGNvbnRleHQudmFyc1snb3V0cHV0X2RpciddOwogIGZpbmFsIHN1YkRvbWFpbk5hbWUgPSBjb250ZXh0LnZhcnNbJ3N1Yl9kb21haW5fbmFtZSddOwogIGNvbnRleHQudmFycyA9IHsKICAgIC4uLmNvbnRleHQudmFycywKICAgICdvdXRwdXRfZGlyX2lzX2N3ZCc6IG91dHB1dERpciA9PSAnLicsCiAgICAnaGFzX3N1Yl9kb21haW5fbmFtZSc6IHN1YkRvbWFpbk5hbWUgIT0gbnVsbCwKICB9Owp9Cg==",
      "type": "text"
    },
    {
      "path": "pubspec.yaml",
      "data":
          "bmFtZTogdmFsdWVfb2JqZWN0X2hvb2tzCgplbnZpcm9ubWVudDoKICBzZGs6ICI+PTMuMC4wIDw0LjAuMCIKCmRlcGVuZGVuY2llczoKICBtYXNvbjogYW55Cg==",
      "type": "text"
    }
  ],
  "name": "value_object",
  "description":
      "A brick generating a value object of a domain package of a Rapid project.",
  "version": "0.1.0",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "readme": {
    "path": "README.md",
    "data": "IyB2YWx1ZV9vYmplY3QKClRPRE8=",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMAoKLSBUT0RPOiBEZXNjcmliZSBpbml0aWFsIHJlbGVhc2UuCg==",
    "type": "text"
  },
  "vars": {
    "project_name": {"type": "string"},
    "name": {"type": "string"},
    "output_dir": {"type": "string"},
    "output_dir_is_cwd": {"type": "boolean"},
    "type": {"type": "string"},
    "generics": {"type": "string"},
    "has_sub_domain_name": {"type": "boolean"},
    "sub_domain_name": {"type": "string"}
  }
});
