{{#android}}name: {{project_name}}_ui_android
description: Widgets and themes implementing {{project_name.titleCase()}} design language for Android.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_tailor_annotation: ^1.1.1
  {{project_name}}_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  theme_tailor: ^1.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/android}}{{#ios}}name: {{project_name}}_ui_ios
description: Widgets and themes implementing {{project_name.titleCase()}} design language for iOS.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_tailor_annotation: ^1.1.1
  cupertino_icons: ^1.0.5
  {{project_name}}_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  theme_tailor: ^1.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/ios}}{{#linux}}name: {{project_name}}_ui_linux
description: Widgets and themes implementing {{project_name.titleCase()}} design language for Linux.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_tailor_annotation: ^1.1.1
  yaru: ^0.6.0
  yaru_icons: ^1.0.4
  {{project_name}}_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  theme_tailor: ^1.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/linux}}{{#macos}}name: {{project_name}}_ui_macos
description: Widgets and themes implementing {{project_name.titleCase()}} design language for macOS.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_tailor_annotation: ^1.1.1
  cupertino_icons: ^1.0.5
  macos_ui: ^1.12.2
  {{project_name}}_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  theme_tailor: ^1.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/macos}}{{#web}}name: {{project_name}}_ui_web
description: Widgets and themes implementing {{project_name.titleCase()}} design language for Web.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_tailor_annotation: ^1.1.1
  {{project_name}}_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  theme_tailor: ^1.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/web}}{{#windows}}name: {{project_name}}_ui_windows
description: Widgets and themes implementing {{project_name.titleCase()}} design language for Windows.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme_tailor_annotation: ^1.1.1
  fluent_ui: ^4.4.1
  {{project_name}}_ui:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  theme_tailor: ^1.1.1
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/windows}}