name: {{project_name}}_{{platform}}_navigation
description: Navigation of {{project_name.titleCase()}}.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  auto_route: ^7.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.6
