name: { { project_name } }

packages:
  - packages/**

command:
  bootstrap:
    # https://github.com/dart-lang/pub/issues/3404)
    runPubGetInParallel: false

  clean:
    hooks:
      post: melos exec -c 3 -- "flutter clean"

ide:
  intellij: false

scripts:
  analyze:
    run: flutter analyze
    description: Analyze all packages.

  format:
    run: dart format . --fix
    description: Format all packages.

  gen-code:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Run code generation in a package.
    packageFilters:
      dependsOn:
        - build_runner

  gen-l10n:
    exec: flutter gen-l10n --format
    description: (Re)-generate localizations in a package.
    packageFilters:
      dependsOn:
        - flutter_localizations
        - intl

  test:
    exec: flutter test
    description: Run `flutter test` in a package.
    packageFilters:
      dirExists:
        - test

  test:coverage:
    exec: flutter test --coverage
    description: Run `flutter test --coverage` in a package.
    packageFilters:
      dirExists:
        - test

  test:e2e:
    exec: flutter test
    description: Run `flutter test` in a package.
    packageFilters:
      dirExists:
        - integration_test
      dependsOn:
        - integration_test

  coverage:
    exec: test_cov_console -t
    description: |
      Run `test_cov_console -t` in a package.
       - Requires `test_cov_console` (can be installed via `dart pub global activate test_cov_console`).
    packageFilters:
      fileExists:
        - coverage/lcov.info

  coverage:html:
    exec: genhtml coverage/lcov.info -o coverage/html
    description: |
      Run `genhtml coverage/lcov.info -o coverage/html` in a package.
       - Requires `lcov` (can be installed via `brew install lcov` on macOS).
    packageFilters:
      fileExists:
        - coverage/lcov.info
