{{#android}}name: {{project_name}}_android
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_android_app:
  {{project_name}}_android_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
{{/android}}{{#ios}}name: {{project_name}}_ios
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_ios_app:
  {{project_name}}_ios_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
{{/ios}}{{#linux}}name: {{project_name}}_linux
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_linux_app:
  {{project_name}}_linux_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
{{/linux}}{{#macos}}name: {{project_name}}_macos
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_macos_app:
  {{project_name}}_macos_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
{{/macos}}{{#web}}name: {{project_name}}_web
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_web_app:
  {{project_name}}_web_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
{{/web}}{{#windows}}name: {{project_name}}_windows
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_windows_app:
  {{project_name}}_windows_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
{{/windows}}{{#mobile}}name: {{project_name}}_mobile
description: {{ description }}

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.3.0
  {{project_name}}_di:
  {{project_name}}_logging:
  {{project_name}}_infrastructure:
  {{project_name}}_mobile_app:
  {{project_name}}_mobile_home_page:

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
{{/mobile}}