arb-dir: lib/src/presentation/l10n/arb
output-class: ExampleIosPublicRouterLocalizations
output-dir: lib/src/presentation/l10n
template-arb-file: public_router_en.arb
output-localization-file: example_ios_public_router_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
