name: {{project_name}}_logging
description: Logging of {{project_name.titleCase()}}.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  injectable: ^2.1.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  mocktail: ^0.3.0
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5
