name: rapid_domain
description: Domain utils for Rapid apps.
version: 0.0.1-dev.1
repository: https://github.com/jtdLab/rapid/tree/main/packages/rapid/rapid_domain
issue_tracker: https://github.com/jtdLab/rapid/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.24.4
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  build_version: ^2.1.1
