{{#android}}name: {{project_name}}_android_app
description: The App feature.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.8.0
  bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  auto_route: ^6.2.0
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_android:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/android}}{{#ios}}name: {{project_name}}_ios_app
description: The App feature.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.8.0
  bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  auto_route: ^6.2.0
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_ios:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/ios}}{{#linux}}name: {{project_name}}_linux_app
description: The App feature.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.8.0
  bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  auto_route: ^6.2.0
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_linux:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/linux}}{{#macos}}name: {{project_name}}_macos_app
description: The App feature.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.8.0
  bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  auto_route: ^6.2.0
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_macos:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/macos}}{{#web}}name: {{project_name}}_web_app
description: The App feature.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.8.0
  bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  auto_route: ^6.2.0
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/web}}{{#windows}}name: {{project_name}}_windows_app
description: The App feature.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.8.0
  bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.1
  auto_route: ^6.2.0
  {{project_name}}_di:
  {{project_name}}_domain:
  {{project_name}}_ui_windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.3
  injectable_generator: ^2.1.5
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.1

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
{{/windows}}