name: platform_tab_flow_feature_package_hooks

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: any
  # TODO: https://github.com/felangel/mason/issues/996
  hooks:
    git:
      url: https://github.com/jtdLab/rapid.git
      path: packages/rapid_cli/templates/hooks
      ref: dev
