name: example_domain
description: TODO
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  rapid_domain:
    git:
      url: https://github.com/jtdLab/rapid.git
      path: packages/rapid/rapid_domain
  dartz: ^0.10.1
  faker: ^2.1.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
  build_runner: ^2.4.2
  freezed: ^2.3.3
