arb-dir: lib/src/presentation/l10n/arb
output-class: ExampleIosProtectedRouterLocalizations
output-dir: lib/src/presentation/l10n
template-arb-file: protected_router_en.arb
output-localization-file: example_ios_protected_router_localizations.dart
nullable-getter: false
synthetic-package: false
header: // coverage:ignore-file
