// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final serviceImplementationBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_infrastructure/lib/{{{output_dir}}}/{{service_name.snakeCase()}}/{{name.snakeCase()}}_{{service_name.snakeCase()}}_service.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmRhcnR6L2RhcnR6LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6aW5qZWN0YWJsZS9pbmplY3RhYmxlLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6e3twcm9qZWN0X25hbWUuc25ha2VDYXNlKCl9fV9kb21haW4ve3tzZXJ2aWNlX25hbWUuc25ha2VDYXNlKCl9fS9pX3t7c2VydmljZV9uYW1lLnNuYWtlQ2FzZSgpfX1fc2VydmljZS5kYXJ0JzsKCi8vIFRPRE86IGRlc2NyaXB0aW9uCkBkZXYKQExhenlTaW5nbGV0b24oYXM6IEl7e3NlcnZpY2VfbmFtZS5wYXNjYWxDYXNlKCl9fVNlcnZpY2UpCmNsYXNzIHt7bmFtZS5wYXNjYWxDYXNlKCl9fXt7c2VydmljZV9uYW1lLnBhc2NhbENhc2UoKX19U2VydmljZSBpbXBsZW1lbnRzIEl7e3NlcnZpY2VfbmFtZS5wYXNjYWxDYXNlKCl9fVNlcnZpY2UgewogQG92ZXJyaWRlCiAgRWl0aGVyPHt7c2VydmljZV9uYW1lLnBhc2NhbENhc2UoKX19U2VydmljZU1ldGhvZDFGYWlsdXJlLCBkeW5hbWljPiBtZXRob2QxKCkgewogICAgLy8gVE9ETzogaW1wbGVtZW50CiAgICB0aHJvdyBVbmltcGxlbWVudGVkRXJyb3IoKTsKICB9CgogIEBvdmVycmlkZQogIEZ1dHVyZTxFaXRoZXI8e3tzZXJ2aWNlX25hbWUucGFzY2FsQ2FzZSgpfX1TZXJ2aWNlTWV0aG9kMkZhaWx1cmUsIGR5bmFtaWM+PiBtZXRob2QyKCkgYXN5bmMgewogICAgLy8gVE9ETzogaW1wbGVtZW50CiAgICB0aHJvdyBVbmltcGxlbWVudGVkRXJyb3IoKTsKICB9Cn0=",
      "type": "text"
    },
    {
      "path":
          "packages/{{project_name}}/{{project_name}}_infrastructure/test/{{{output_dir}}}/{{service_name.snakeCase()}}/{{name.snakeCase()}}_{{service_name.snakeCase()}}_service_test.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOmRhcnR6L2RhcnR6LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6dGVzdC90ZXN0LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6e3twcm9qZWN0X25hbWUuc25ha2VDYXNlKCl9fV9kb21haW4ve3tzZXJ2aWNlX25hbWUuc25ha2VDYXNlKCl9fS9pX3t7c2VydmljZV9uYW1lLnNuYWtlQ2FzZSgpfX1fc2VydmljZS5kYXJ0JzsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lLnNuYWtlQ2FzZSgpfX1faW5mcmFzdHJ1Y3R1cmUve3tzZXJ2aWNlX25hbWUuc25ha2VDYXNlKCl9fS97e25hbWUuc25ha2VDYXNlKCl9fV97e3NlcnZpY2VfbmFtZS5zbmFrZUNhc2UoKX19X3NlcnZpY2UuZGFydCc7CgovLyBjbGFzcyBfTW9ja015RGVwZW5kZW5jeSBleHRlbmRzIE1vY2sgaW1wbGVtZW50cyBJTXlEZXBlbmRlbmN5Ci8vIC4uLgoKdm9pZCBtYWluKCkgewogIGdyb3VwKCd7e25hbWUucGFzY2FsQ2FzZSgpfX17e3NlcnZpY2VfbmFtZS5wYXNjYWxDYXNlKCl9fVNlcnZpY2UnLCAoKSB7CiAgICAvLyBsYXRlIElNeURlcGVuZGVuY3kgbXlEZXBlbmRlbmN5CiAgICAvLyAuLi4KCiAgICBzZXRVcCgoKSB7CiAgICAgIC8vIEluaXQgbW9ja3MKICAgICAgLy8gbXlEZXBlbmRlbmN5ID0KICAgICAgLy8gLi4uCiAgICB9KTsKCiAgICAvLyBSZXR1cm5zIHt7bmFtZS5wYXNjYWxDYXNlKCl9fXt7c2VydmljZV9uYW1lLnBhc2NhbENhc2UoKX19U2VydmljZSBjcmVhdGVkIHVzaW5nIHRoZSAuIGNvbnN0cnVjdG9yCiAgICAvLyBhbmQgaW5qZWN0aW5nIGFsbCBtb2NrZWQgZGVwZW5kZW5jaWVzLgogICAge3tuYW1lLnBhc2NhbENhc2UoKX19e3tzZXJ2aWNlX25hbWUucGFzY2FsQ2FzZSgpfX1TZXJ2aWNlIGdldEluc3RhbmNlKCkgewogICAgICByZXR1cm4ge3tuYW1lLnBhc2NhbENhc2UoKX19e3tzZXJ2aWNlX25hbWUucGFzY2FsQ2FzZSgpfX1TZXJ2aWNlKC8qIG15RGVwZW5kZW5jeSwgLi4uKi8pOwogICAgfQoKICAgIGdyb3VwKCcuJywgKCkgewogICAgICBsYXRlIHt7bmFtZS5wYXNjYWxDYXNlKCl9fXt7c2VydmljZV9uYW1lLnBhc2NhbENhc2UoKX19U2VydmljZSB1bmRlclRlc3Q7CgogICAgICB0ZXN0KCdBc3NpZ25zIGFsbCBwYXJhbXMgY29ycmVjdGx5LicsICgpIHsKICAgICAgICAvLyBBcnJhbmdlICsgQWN0CiAgICAgICAgdW5kZXJUZXN0ID0gZ2V0SW5zdGFuY2UoKTsKCiAgICAgICAgLy8gQXNzZXJ0CiAgICAgICAgLy8gZXhwZWN0KHVuZGVyVGVzdC5teURlcGVuZGVuY3ksIG15RGVwZW5kZW5jeSk7CiAgICAgICAgLy8gLi4uCiAgICAgIH0pOwoKICAgICAgLy8vIC4uIG1vcmUgdGVzdHMgZS5nIGNvbmZpZwogICAgfSk7CgogICAgZ3JvdXAoJ21ldGhvZDEnLCAoKSB7CiAgICAgIGxhdGUgRWl0aGVyPHt7c2VydmljZV9uYW1lLnBhc2NhbENhc2UoKX19U2VydmljZU1ldGhvZDFGYWlsdXJlLCBkeW5hbWljPiB1bmRlclRlc3Q7CgogICAgICBzZXRVcCgoKSB7CiAgICAgICAgLy8gTW9jayBkZWZhdWx0IGJlaGF2aW91ciBvZiBkZXBlbmRlbmNpZXMgdXNlZCBpbiB0aGlzIG1ldGhvZAogICAgICAgIC8vIHdoZW4oKCkgPT4gbXlEZXBlbmRlbmN5Lm15TWV0aG9kKCkpLnRoZW5BbnN3ZXIoKF8pIGFzeW5jID0+IG15VmFsdWUpOwogICAgICB9KTsKCiAgICAgIHRlc3QoCiAgICAgICAgICAnR0lWRU4gc29tZSBjb250ZXh0ICcKICAgICAgICAgICdUSEVOIHJldHVybi9jYWxsIHNvbWUgdmFsdWUsZmFpbHVyZS9tZXRob2QuJywgKCkgewogICAgICAgIC8vIEFycmFuZ2UKICAgICAgICAvLyBUT0RPOgoKICAgICAgICAvLyBBY3QKICAgICAgICB1bmRlclRlc3QgPSBnZXRJbnN0YW5jZSgpLm1ldGhvZDEoKTsKCiAgICAgICAgLy8gQXNzZXJ0CiAgICAgICAgLy8gVE9ETzoKICAgICAgfSk7CgogICAgICAvLyAuLi4KICAgIH0pOwoKICAgIGdyb3VwKCdtZXRob2QyJywgKCkgewogICAgICBsYXRlIEZ1dHVyZTxFaXRoZXI8e3tzZXJ2aWNlX25hbWUucGFzY2FsQ2FzZSgpfX1TZXJ2aWNlTWV0aG9kMkZhaWx1cmUsIGR5bmFtaWM+PiB1bmRlclRlc3Q7CgogICAgICBzZXRVcCgoKSB7CiAgICAgICAgLy8gTW9jayBkZWZhdWx0IGJlaGF2aW91ciBvZiBkZXBlbmRlbmNpZXMgdXNlZCBpbiB0aGlzIG1ldGhvZAogICAgICAgIC8vIHdoZW4oKCkgPT4gbXlEZXBlbmRlbmN5Lm15TWV0aG9kKCkpLnRoZW5BbnN3ZXIoKF8pIGFzeW5jID0+IG15VmFsdWUpOwogICAgICB9KTsKCiAgICAgIHRlc3QoCiAgICAgICAgICAnR0lWRU4gc29tZSBjb250ZXh0ICcKICAgICAgICAgICdUSEVOIHJldHVybi9jYWxsIHNvbWUgdmFsdWUsZmFpbHVyZS9tZXRob2QuJywgKCkgewogICAgICAgIC8vIEFycmFuZ2UKICAgICAgICAvLyBUT0RPOgoKICAgICAgICAvLyBBY3QKICAgICAgICB1bmRlclRlc3QgPSBnZXRJbnN0YW5jZSgpLm1ldGhvZDIoKTsKCiAgICAgICAgLy8gQXNzZXJ0CiAgICAgICAgLy8gVE9ETzoKICAgICAgfSk7CgogICAgICAvLyAuLi4KICAgIH0pOwoKICAgIC8vIC4uLgogIH0pOwp9Cg==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "service_implementation",
  "description": "A new brick created with the Mason CLI.",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "readme": {
    "path": "README.md",
    "data":
        "IyBzZXJ2aWNlX2ltcGxlbWVudGF0aW9uCgpBIG5ldyBicmljayBjcmVhdGVkIHdpdGggdGhlIE1hc29uIENMSS4KCl9HZW5lcmF0ZWQgYnkgW21hc29uXVsxXSDwn6exXwoKIyMgR2V0dGluZyBTdGFydGVkIPCfmoAKClRoaXMgaXMgYSBzdGFydGluZyBwb2ludCBmb3IgYSBuZXcgYnJpY2suCkEgZmV3IHJlc291cmNlcyB0byBnZXQgeW91IHN0YXJ0ZWQgaWYgdGhpcyBpcyB5b3VyIGZpcnN0IGJyaWNrIHRlbXBsYXRlOgoKLSBbT2ZmaWNpYWwgTWFzb24gRG9jdW1lbnRhdGlvbl1bMl0KLSBbQ29kZSBnZW5lcmF0aW9uIHdpdGggTWFzb24gQmxvZ11bM10KLSBbVmVyeSBHb29kIExpdmVzdHJlYW06IEZlbGl4IEFuZ2Vsb3YgRGVtb3MgTWFzb25dWzRdCgpbMV06IGh0dHBzOi8vZ2l0aHViLmNvbS9mZWxhbmdlbC9tYXNvbgpbMl06IGh0dHBzOi8vZ2l0aHViLmNvbS9mZWxhbmdlbC9tYXNvbi90cmVlL21hc3Rlci9wYWNrYWdlcy9tYXNvbl9jbGkjcmVhZG1lClszXTogaHR0cHM6Ly92ZXJ5Z29vZC52ZW50dXJlcy9ibG9nL2NvZGUtZ2VuZXJhdGlvbi13aXRoLW1hc29uCls0XTogaHR0cHM6Ly95b3V0dS5iZS9HNFBUakE2dHBUVQo=",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMCsxCgotIFRPRE86IERlc2NyaWJlIGluaXRpYWwgcmVsZWFzZS4K",
    "type": "text"
  },
  "license": {
    "path": "LICENSE",
    "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
    "type": "text"
  },
  "vars": {
    "project_name": {"type": "string"},
    "name": {"type": "string"},
    "service_name": {"type": "string"},
    "output_dir": {"type": "string"}
  }
});
