name: example_infrastructure
description: TODO
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  injectable: ^2.1.1
  example_logging:
  example_domain:

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
