name: bundles

on:
  workflow_dispatch:
    branches:
      - dev

jobs:
  bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.0
          channel: stable
          cache: true

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Mason CLI
        run: dart pub global activate mason_cli

      - name: Install Bundles Package
        run: |
          cd tool/bundles
          flutter pub get

      - name: Rebundle Templates
        run: dart run tool/bundles/bin/bundles.dart

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore(rapid_cli): Update bundled templates"
          title: "chore(rapid_cli): Update bundled templates"
          body: "This pull request updates the bundled templates."
          branch: bundles
