name: e2e_tweaker

on:
  workflow_dispatch:

jobs:
  e2e-linux:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          flutter test -j 1 --run-skipped -t e2e,linux,tweak
