name: example

on:
  push:
    branches:
      - main
      - dev # TODO rm
    paths:
      - example/**
  pull_request:
    paths:
      - example/**

env:
  DI_PATH: example/packages/example/example_di
  DOMAIN_PATH: example/packages/example/example_domain
  INFRASTRUCTURE_PATH: example/packages/example/example_infrastructure
  LOGGING_PATH: example/packages/example/example_logging
  UI_PATH: example/packages/example_ui/example_ui

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_PATH: example/packages/example/example_android
      ANDROID_UI_PATH: example/packages/example_ui/example_ui_android

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            android:
              - '${{ env.DI_PATH }}/**'
              - '${{ env.DOMAIN_PATH }}/**'
              - '${{ env.INFRASTRUCTURE_PATH }}/**'
              - '${{ env.LOGGING_PATH }}/**'
              - '${{ env.UI_PATH }}/**'
              - '${{ env.ANDROID_PATH }}/**'
              - '${{ env.ANDROID_UI_PATH }}/**'
      - name: Check File Existence
        id: check_files
        run: |
          if [ -e ${{ env.ANDROID_PATH }} ] && [ -e ${{ env.ANDROID_UI_PATH }} ]; then
            echo "files_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exist=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/setup-java@v2
        if: ${{ steps.changes.outputs.android == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          distribution: zulu
          java-version: 11
      - uses: subosito/flutter-action@v2
        if: ${{ steps.changes.outputs.android == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          cache: true
      - run: flutter pub get
        if: ${{ steps.changes.outputs.android == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build apk -t ${{ env.ANDROID_PATH }}/example_android/lib/main_development.dart --release --verbose
        if: ${{ steps.changes.outputs.android == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build appbundle -t ${{ env.ANDROID_PATH }}/example_android/lib/main_development.dart --release --verbose
        if: ${{ steps.changes.outputs.android == 'true' && steps.check_files.outputs.files_exist == 'true' }}

  build-ios:
    runs-on: macos-latest

    env:
      IOS_PATH: example/packages/example/example_ios
      IOS_UI_PATH: example/packages/example_ui/example_ui_ios

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            ios:
              - '${{ env.DI_PATH }}/**'
              - '${{ env.DOMAIN_PATH }}/**'
              - '${{ env.INFRASTRUCTURE_PATH }}/**'
              - '${{ env.LOGGING_PATH }}/**'
              - '${{ env.UI_PATH }}/**'
              - '${{ env.IOS_PATH }}/**'
              - '${{ env.IOS_UI_PATH }}/**'
      - name: Check File Existence
        id: check_files
        run: |
          if [ -e ${{ env.IOS_PATH }} ] && [ -e ${{ env.IOS_UI_PATH }} ]; then
            echo "files_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exist=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: subosito/flutter-action@v2
        if: ${{ steps.changes.outputs.ios == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          cache: true
          architecture: x64
      - run: flutter pub get
        if: ${{ steps.changes.outputs.ios == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build ios -t ${{ env.IOS_PATH }}/example_ios/lib/main_development.dart --release --no-codesign --verbose
        if: ${{ steps.changes.outputs.ios == 'true' && steps.check_files.outputs.files_exist == 'true' }}

  build-linux:
    runs-on: ubuntu-latest

    env:
      LINUX_PATH: example/packages/example/example_linux
      LINUX_UI_PATH: example/packages/example_ui/example_ui_linux

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            linux:
              - '${{ env.DI_PATH }}/**'
              - '${{ env.DOMAIN_PATH }}/**'
              - '${{ env.INFRASTRUCTURE_PATH }}/**'
              - '${{ env.LOGGING_PATH }}/**'
              - '${{ env.UI_PATH }}/**'
              - '${{ env.LINUX_PATH }}/**'
              - '${{ env.LINUX_UI_PATH }}/**'
      - name: Check File Existence
        id: check_files
        run: |
          if [ -e ${{ env.LINUX_PATH }} ] && [ -e ${{ env.LINUX_UI_PATH }} ]; then
            echo "files_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exist=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: subosito/flutter-action@v2
        if: ${{ steps.changes.outputs.linux == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
        if: ${{ steps.changes.outputs.linux == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter config --enable-linux-desktop
        if: ${{ steps.changes.outputs.linux == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build linux -t ${{ env.LINUX_PATH }}/example_linux/lib/main_development.dart --release --verbose
        if: ${{ steps.changes.outputs.linux == 'true' && steps.check_files.outputs.files_exist == 'true' }}

  build-macos:
    runs-on: macos-latest

    env:
      MACOS_PATH: example/packages/example/example_macos
      MACOS_UI_PATH: example/packages/example_ui/example_ui_macos

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            macos:
              - '${{ env.DI_PATH }}/**'
              - '${{ env.DOMAIN_PATH }}/**'
              - '${{ env.INFRASTRUCTURE_PATH }}/**'
              - '${{ env.LOGGING_PATH }}/**'
              - '${{ env.UI_PATH }}/**'
              - '${{ env.MACOS_PATH }}/**'
              - '${{ env.MACOS_UI_PATH }}/**'
      - name: Check File Existence
        id: check_files
        run: |
          if [ -e ${{ env.MACOS_PATH }} ] && [ -e ${{ env.MACOS_UI_PATH }} ]; then
            echo "files_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exist=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: subosito/flutter-action@v2
        if: ${{ steps.changes.outputs.macos == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          cache: true
          architecture: x64
      - run: flutter config --enable-macos-desktop
        if: ${{ steps.changes.outputs.macos == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build macos -t ${{ env.MACOS_PATH }}/example_macos/lib/main_development.dart --release --verbose
        if: ${{ steps.changes.outputs.macos == 'true' && steps.check_files.outputs.files_exist == 'true' }}

  build-web:
    runs-on: ubuntu-latest

    env:
      WEB_PATH: example/packages/example/example_web
      WEB_UI_PATH: example/packages/example_ui/example_ui_web

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            web:
              - '${{ env.DI_PATH }}/**'
              - '${{ env.DOMAIN_PATH }}/**'
              - '${{ env.INFRASTRUCTURE_PATH }}/**'
              - '${{ env.LOGGING_PATH }}/**'
              - '${{ env.UI_PATH }}/**'
              - '${{ env.WEB_PATH }}/**'
              - '${{ env.WEB_UI_PATH }}/**'
      - name: Check File Existence
        id: check_files
        run: |
          if [ -e ${{ env.WEB_PATH }} ] && [ -e ${{ env.WEB_UI_PATH }} ]; then
            echo "files_exist=true" >> "$GITHUB_OUTPUT"
          else
            echo "files_exist=false" >> "$GITHUB_OUTPUT"
          fi
      - uses: subosito/flutter-action@v2
        if: ${{ steps.changes.outputs.web == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          cache: true
      - run: flutter pub get
        if: ${{ steps.changes.outputs.web == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build web -t ${{ env.WEB_PATH }}/example_web/lib/main_development.dart --verbose
        if: ${{ steps.changes.outputs.web == 'true' && steps.check_files.outputs.files_exist == 'true' }}

  build-windows:
    runs-on: windows-latest

    env:
      WINDOWS_PATH: example/packages/example/example_windows
      WINDOWS_UI_PATH: example/packages/example_ui/example_ui_windows

    steps:
      - run: git config --global core.longpaths true
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            windows:
              - '${{ env.DI_PATH }}/**'
              - '${{ env.DOMAIN_PATH }}/**'
              - '${{ env.INFRASTRUCTURE_PATH }}/**'
              - '${{ env.LOGGING_PATH }}/**'
              - '${{ env.UI_PATH }}/**'
              - '${{ env.WINDOWS_PATH }}/**'
              - '${{ env.WINDOWS_UI_PATH }}/**'
      - name: Check File Existence
        id: check_files
        run: |
          if (Test-Path -Path "${{ env.WINDOWS_PATH }}") {
           if (Test-Path -Path "${{ env.WINDOWS_UI_PATH }}") {
            echo "files_exist=true" >> "$GITHUB_OUTPUT"
           }
          } else {
            echo "files_exist=false" >> "$GITHUB_OUTPUT"
          }
      - uses: subosito/flutter-action@v2
        if: ${{ steps.changes.outputs.windows == 'true' && steps.check_files.outputs.files_exist == 'true' }}
        with:
          cache: true
      - run: flutter config --enable-windows-desktop
        if: ${{ steps.changes.outputs.windows == 'true' && steps.check_files.outputs.files_exist == 'true' }}
      - run: flutter build windows -t ${{ env.WINDOWS_PATH }}/example_windows/lib/main_development.dart --release --verbose
        if: ${{ steps.changes.outputs.windows == 'true' && steps.check_files.outputs.files_exist == 'true' }}
