name: example_web

on:
  push:
    branches:
      - main
    paths:
      - example/packages/example/example_web
      - example/packages/example_ui/example_ui
      - example/packages/example_ui/example_ui_web
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/packages/example/example_web/example_web

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter pub get
      - run: flutter build web -t lib/main_development.dart --verbose
