name: example

on:
  push:
    branches:
      - main
    paths:
      - example/**
  pull_request:
    paths:
      - example/**
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example/packages/example/example_android/example_android

    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2.2.1
        with:
          filters: |
            android:
              - 'example/packages/example/example_di/**'
              - 'example/packages/example/example_domain/**'
              - 'example/packages/example/example_infrastructure/**'
              - 'example/packages/example/example_logging/**'
              - 'example/packages/example/example_android/**'
              - 'example/packages/example_ui/example_ui/**'
              - 'example/packages/example_ui/example_ui_android/**'
      - uses: actions/setup-java@v2
        if: ${{ steps.filter.outputs.android == 'true' }}
        with:
          distribution: zulu
          java-version: 11
      - uses: subosito/flutter-action@v2
        if: ${{ steps.filter.outputs.android == 'true' }}
        with:
          cache: true
      - run: flutter pub get
        if: ${{ steps.filter.outputs.android == 'true' }}
      - run: flutter build apk -t lib/main_development.dart --release --verbose
        if: ${{ steps.filter.outputs.android == 'true' }}
      - run: flutter build appbundle -t lib/main_development.dart --release --verbose
        if: ${{ steps.filter.outputs.android == 'true' }}
