name: example

on:
  workflow_dispatch:
    branches:
      - "dev"

jobs:
  build_android:
    defaults:
      run:
        working-directory: example/packages/example/example_android/example_android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter pub get
      - run: flutter build apk -t lib/main_development.dart --release --verbose
      - run: flutter build appbundle -t lib/main_development.dart --release --verbose

  build_ios:
    defaults:
      run:
        working-directory: example/packages/example/example_ios/example_ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          architecture: x64
      - run: flutter pub get
      - run: flutter build ios -t lib/main_development.dart --release --no-codesign --verbose

  build_linux:
    defaults:
      run:
        working-directory: example/packages/example/example_linux/example_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux -t lib/main_development.dart --release --verbose

  build_macos:
    defaults:
      run:
        working-directory: example/packages/example/example_macos/example_macos
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          architecture: x64
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos -t lib/main_development.dart --release --verbose

  build_web:
    defaults:
      run:
        working-directory: example/packages/example/example_web/example_web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter pub get
      - run: flutter build web -t lib/main_development.dart --verbose

  build_windows:
    defaults:
      run:
        working-directory: example/packages/example/example_windows/example_windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows -t lib/main_development.dart --release --verbose
