name: rapid_cli

on:
  push:

env:
  FLUTTER_VERSION: 3.10.0

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Format
        run: dart format lib test tool --set-exit-if-changed

      # TODO uncomment if project is clean
      # - name: Analyze
      #   run: flutter analyze .

      - name: Run Unit Tests
        run: flutter test test/src -j 1 --no-pub --test-randomize-ordering-seed random --coverage

      - name: Ensure 100% Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 80 # TODO set to 100 if unit test are complete
          path: packages/rapid_cli/coverage/lcov.info

  pana:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"

      - name: Install Dependencies
        run: flutter pub get

      - name: Setup Pana
        run: flutter pub global activate pana

      - name: Verify Pub Score
        run: sh tool/verify_pub_score.sh 100
