name: rapid_cli_e2e

on:
  workflow_dispatch:

jobs:
  e2e:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_android_test.dart
          - test/e2e/activate_ios_test.dart
          - test/e2e/activate_linux_test.dart
          - test/e2e/activate_macos_test.dart
          - test/e2e/activate_web_test.dart
          - test/e2e/activate_windows_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

          # E2E tests for deactivate command
          - test/e2e/deactivate_android_test.dart
          - test/e2e/deactivate_ios_test.dart
          - test/e2e/deactivate_linux_test.dart
          - test/e2e/deactivate_macos_test.dart
          - test/e2e/deactivate_web_test.dart
          - test/e2e/deactivate_windows_test.dart

          # E2E tests for domain command
          - test/e2e/domain_add_entity_test.dart
          - test/e2e/domain_add_service_interface_test.dart
          - test/e2e/domain_add_value_object_test.dart
          - test/e2e/domain_remove_entity_test.dart
          - test/e2e/domain_remove_service_interface_test.dart
          - test/e2e/domain_remove_value_object_test.dart

          # E2E tests for infrastructure command
          - test/e2e/infrastructure_add_data_transfer_object_test.dart
          - test/e2e/infrastructure_add_service_implementation_test.dart
          - test/e2e/infrastructure_remove_data_transfer_object_test.dart
          - test/e2e/infrastructure_remove_service_implementation_test.dart

          # E2E tests for ui command
          - test/e2e/ui_android_add_widget_test.dart
          - test/e2e/ui_android_remove_widget_test.dart
          - test/e2e/ui_ios_add_widget_test.dart
          - test/e2e/ui_ios_remove_widget_test.dart
          - test/e2e/ui_linux_add_widget_test.dart
          - test/e2e/ui_linux_remove_widget_test.dart
          - test/e2e/ui_macos_add_widget_test.dart
          - test/e2e/ui_macos_remove_widget_test.dart
          - test/e2e/ui_web_add_widget_test.dart
          - test/e2e/ui_web_remove_widget_test.dart
          - test/e2e/ui_windows_add_widget_test.dart
          - test/e2e/ui_windows_remove_widget_test.dart

          # E2E tests for platform command
          - test/e2e/android_add_feature_test.dart
          - test/e2e/android_add_language_test.dart
          - test/e2e/android_feature_add_bloc_test.dart
          - test/e2e/android_feature_add_cubit_test.dart
          - test/e2e/android_remove_feature_test.dart
          - test/e2e/android_remove_language_test.dart

          - test/e2e/ios_add_feature_test.dart
          - test/e2e/ios_add_language_test.dart
          - test/e2e/ios_feature_add_bloc_test.dart
          - test/e2e/ios_feature_add_cubit_test.dart
          - test/e2e/ios_remove_feature_test.dart
          - test/e2e/ios_remove_language_test.dart

          - test/e2e/linux_add_feature_test.dart
          - test/e2e/linux_add_language_test.dart
          - test/e2e/linux_feature_add_bloc_test.dart
          - test/e2e/linux_feature_add_cubit_test.dart
          - test/e2e/linux_remove_feature_test.dart
          - test/e2e/linux_remove_language_test.dart

          - test/e2e/macos_add_feature_test.dart
          - test/e2e/macos_add_language_test.dart
          - test/e2e/macos_feature_add_bloc_test.dart
          - test/e2e/macos_feature_add_cubit_test.dart
          - test/e2e/macos_remove_feature_test.dart
          - test/e2e/macos_remove_language_test.dart

          - test/e2e/web_add_feature_test.dart
          - test/e2e/web_add_language_test.dart
          - test/e2e/web_feature_add_bloc_test.dart
          - test/e2e/web_feature_add_cubit_test.dart
          - test/e2e/web_remove_feature_test.dart
          - test/e2e/web_remove_language_test.dart

          - test/e2e/windows_add_feature_test.dart
          - test/e2e/windows_add_language_test.dart
          - test/e2e/windows_feature_add_bloc_test.dart
          - test/e2e/windows_feature_add_cubit_test.dart
          - test/e2e/windows_remove_feature_test.dart
          - test/e2e/windows_remove_language_test.dart

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e -x android,ios,linux,macos,web,windows
