name: rapid_cli_e2e_fast

on:
  workflow_dispatch:

jobs:
  e2e:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/src/commands/activate/android/e2e_test.dart
          - test/src/commands/activate/ios/e2e_test.dart
          - test/src/commands/activate/linux/e2e_test.dart
          - test/src/commands/activate/macos/e2e_test.dart
          - test/src/commands/activate/web/e2e_test.dart
          - test/src/commands/activate/windows/e2e_test.dart

          # E2E tests for create command
          - test/src/commands/create/e2e_test.dart

          # E2E tests for deactivate command
          - test/src/commands/deactivate/android/e2e_test.dart
          - test/src/commands/deactivate/ios/e2e_test.dart
          - test/src/commands/deactivate/linux/e2e_test.dart
          - test/src/commands/deactivate/macos/e2e_test.dart
          - test/src/commands/deactivate/web/e2e_test.dart
          - test/src/commands/deactivate/windows/e2e_test.dart

          # E2E tests for domain command
          - test/src/commands/domain/add/entity/e2e_test.dart
          - test/src/commands/domain/add/service_interface/e2e_test.dart
          - test/src/commands/domain/add/value_object/e2e_test.dart
          - test/src/commands/domain/remove/entity/e2e_test.dart
          - test/src/commands/domain/remove/service_interface/e2e_test.dart
          - test/src/commands/domain/remove/value_object/e2e_test.dart

          # E2E tests for infrastructure command
          - test/src/commands/infrastructure/add/data_transfer_object/e2e_test.dart
          - test/src/commands/infrastructure/add/service_implementation/e2e_test.dart
          - test/src/commands/infrastructure/remove/data_transfer_object/e2e_test.dart
          - test/src/commands/infrastructure/remove/service_implementation/e2e_test.dart

          # E2E tests for ui command
          - test/src/commands/ui/android/add/widget/e2e_test.dart
          - test/src/commands/ui/android/remove/widget/e2e_test.dart
          - test/src/commands/ui/ios/add/widget/e2e_test.dart
          - test/src/commands/ui/ios/remove/widget/e2e_test.dart
          - test/src/commands/ui/linux/add/widget/e2e_test.dart
          - test/src/commands/ui/linux/remove/widget/e2e_test.dart
          - test/src/commands/ui/macos/add/widget/e2e_test.dart
          - test/src/commands/ui/macos/remove/widget/e2e_test.dart
          - test/src/commands/ui/web/add/widget/e2e_test.dart
          - test/src/commands/ui/web/remove/widget/e2e_test.dart
          - test/src/commands/ui/windows/add/widget/e2e_test.dart
          - test/src/commands/ui/windows/remove/widget/e2e_test.dart

          # E2E tests for platform command
          - test/src/commands/android/add/feature/e2e_test.dart
          - test/src/commands/android/add/language/e2e_test.dart
          - test/src/commands/android/feature/add/bloc/e2e_test.dart
          - test/src/commands/android/feature/add/cubit/e2e_test.dart
          - test/src/commands/android/remove/feature/e2e_test.dart
          - test/src/commands/android/remove/language/e2e_test.dart

          - test/src/commands/ios/add/feature/e2e_test.dart
          - test/src/commands/ios/add/language/e2e_test.dart
          - test/src/commands/ios/feature/add/bloc/e2e_test.dart
          - test/src/commands/ios/feature/add/cubit/e2e_test.dart
          - test/src/commands/ios/remove/feature/e2e_test.dart
          - test/src/commands/ios/remove/language/e2e_test.dart

          - test/src/commands/linux/add/feature/e2e_test.dart
          - test/src/commands/linux/add/language/e2e_test.dart
          - test/src/commands/linux/feature/add/bloc/e2e_test.dart
          - test/src/commands/linux/feature/add/cubit/e2e_test.dart
          - test/src/commands/linux/remove/feature/e2e_test.dart
          - test/src/commands/linux/remove/language/e2e_test.dart

          - test/src/commands/macos/add/feature/e2e_test.dart
          - test/src/commands/macos/add/language/e2e_test.dart
          - test/src/commands/macos/feature/add/bloc/e2e_test.dart
          - test/src/commands/macos/feature/add/cubit/e2e_test.dart
          - test/src/commands/macos/remove/feature/e2e_test.dart
          - test/src/commands/macos/remove/language/e2e_test.dart

          - test/src/commands/web/add/feature/e2e_test.dart
          - test/src/commands/web/add/language/e2e_test.dart
          - test/src/commands/web/feature/add/bloc/e2e_test.dart
          - test/src/commands/web/feature/add/cubit/e2e_test.dart
          - test/src/commands/web/remove/feature/e2e_test.dart
          - test/src/commands/web/remove/language/e2e_test.dart

          - test/src/commands/windows/add/feature/e2e_test.dart
          - test/src/commands/windows/add/language/e2e_test.dart
          - test/src/commands/windows/feature/add/bloc/e2e_test.dart
          - test/src/commands/windows/feature/add/cubit/e2e_test.dart
          - test/src/commands/windows/remove/feature/e2e_test.dart
          - test/src/commands/windows/remove/language/e2e_test.dart

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,fast -x android,ios,linux,macos,web,windows
