name: rapid_cli

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # TODO needed?

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format lib test tool --set-exit-if-changed

      - name: Analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test test/src -j 1 --no-pub --test-randomize-ordering-seed random --coverage
        # run: |
        #   flutter pub global activate coverage 1.2.0
        #   flutter pub run test -j 1 --coverage=coverage --test-randomize-ordering-seed random && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib

      # - name: Ensure 100% Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v2
      #   with:
      #     min_coverage: 100
      #     path: packages/rapid_cli/coverage/lcov.info

  pana:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana

      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          echo "score: $PANA_SCORE"
          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
          if (( $SCORE < $TOTAL )); then echo "minimum score not met!"; exit 1; fi
