name: rapid_cli

on:
  push:
    paths:
      - "packages/rapid_cli/**"
      - ".github/workflows/rapid_cli.yaml"

  pull_request:
    paths:
      - "packages/rapid_cli/**"
      - ".github/workflows/rapid_cli.yaml"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format . --set-exit-if-changed

      - name: Analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test --coverage

      - name: Ensure 95% Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          min_coverage: 95
          path: packages/rapid_cli/coverage/lcov.info
