name: rapid_di

on:
  push:
    paths:
      - "packages/rapid/rapid/rapid_di/**"
      - ".github/workflows/rapid_di.yaml"
      - "!packages/rapid/rapid/rapid_di/README.md"

  pull_request:
    paths:
      - "packages/rapid/rapid/rapid_di/**"
      - ".github/workflows/rapid_di.yaml"
      - "!packages/rapid/rapid/rapid_di/README.md"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/rapid/rapid/rapid_di

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5

      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format . --set-exit-if-changed

      - name: Analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test -j 1 --no-pub --test-randomize-ordering-seed random
