name: rapid_cli_e2e

on:
  workflow_dispatch:

jobs:
  e2e:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for create command
          - test/e2e/create_test.dart

          # E2E tests for deactivate command
          - test/e2e/deactivate_android_test.dart
          - test/e2e/deactivate_ios_test.dart
          - test/e2e/deactivate_linux_test.dart
          - test/e2e/deactivate_macos_test.dart
          - test/e2e/deactivate_web_test.dart
          - test/e2e/deactivate_windows_test.dart

          # E2E tests for domain command
          - test/e2e/domain_add_entity_test.dart
          - test/e2e/domain_add_service_interface_test.dart
          - test/e2e/domain_remove_entity_test.dart
          - test/e2e/domain_remove_service_interface_test.dart
          - test/e2e/domain_remove_value_object_test.dart

          # E2E tests for infrastructure command
          - test/e2e/infrastructure_add_data_transfer_object_test.dart
          - test/e2e/infrastructure_add_service_implementation_test.dart
          - test/e2e/infrastructure_remove_data_transfer_object_test.dart
          - test/e2e/infrastructure_remove_service_implementation_test.dart

          # E2E tests for ui command
          - test/e2e/ui_android_add_widget_test.dart
          - test/e2e/ui_android_remove_widget_test.dart
          - test/e2e/ui_ios_add_widget_test.dart
          - test/e2e/ui_ios_remove_widget_test.dart
          - test/e2e/ui_linux_add_widget_test.dart
          - test/e2e/ui_linux_remove_widget_test.dart
          - test/e2e/ui_macos_add_widget_test.dart
          - test/e2e/ui_macos_remove_widget_test.dart
          - test/e2e/ui_web_add_widget_test.dart
          - test/e2e/ui_web_remove_widget_test.dart
          - test/e2e/ui_windows_add_widget_test.dart
          - test/e2e/ui_windows_remove_widget_test.dart

          # E2E tests for platform command
          - test/e2e/android_add_feature_test.dart
          - test/e2e/android_add_language_test.dart
          - test/e2e/android_feature_add_bloc_test.dart
          - test/e2e/android_feature_add_cubit_test.dart
          - test/e2e/android_remove_feature_test.dart
          - test/e2e/android_remove_language_test.dart

          - test/e2e/ios_add_feature_test.dart
          - test/e2e/ios_add_language_test.dart
          - test/e2e/ios_feature_add_bloc_test.dart
          - test/e2e/ios_feature_add_cubit_test.dart
          - test/e2e/ios_remove_feature_test.dart
          - test/e2e/ios_remove_language_test.dart

          - test/e2e/linux_add_feature_test.dart
          - test/e2e/linux_add_language_test.dart
          - test/e2e/linux_feature_add_bloc_test.dart
          - test/e2e/linux_feature_add_cubit_test.dart
          - test/e2e/linux_remove_feature_test.dart
          - test/e2e/linux_remove_language_test.dart

          - test/e2e/macos_add_feature_test.dart
          - test/e2e/macos_add_language_test.dart
          - test/e2e/macos_feature_add_bloc_test.dart
          - test/e2e/macos_feature_add_cubit_test.dart
          - test/e2e/macos_remove_feature_test.dart
          - test/e2e/macos_remove_language_test.dart

          - test/e2e/web_add_feature_test.dart
          - test/e2e/web_add_language_test.dart
          - test/e2e/web_feature_add_bloc_test.dart
          - test/e2e/web_feature_add_cubit_test.dart
          - test/e2e/web_remove_feature_test.dart
          - test/e2e/web_remove_language_test.dart

          - test/e2e/windows_add_feature_test.dart
          - test/e2e/windows_add_language_test.dart
          - test/e2e/windows_feature_add_bloc_test.dart
          - test/e2e/windows_feature_add_cubit_test.dart
          - test/e2e/windows_remove_feature_test.dart
          - test/e2e/windows_remove_language_test.dart

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e -x android,ios,linux,macos,web,windows,fast

  e2e-android:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: macos-latest

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     api-level:
    #       - 29

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_android_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      # - uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # TODO remove and disable gradle caching

      # - name: AVD Cache
      #   uses: actions/cache@v3
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/adb*
      #     key: avd-29

      # - name: Create AVD And Generate Snapshot For Caching
      #   if: steps.avd-cache.outputs.cache-hit != 'true'
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     force-avd-creation: false
      #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: false
      #     script: echo "Generated AVD snapshot for caching."

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29 #${{ matrix.api-level }}
          #force-avd-creation: false
          #emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          #disable-animations: true
          #arch: x86_64
          #profile: Nexus 6
          script: cd packages/rapid_cli && flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,android

  e2e-ios:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_ios_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: "List All Simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^iPhone 11 Simulator (16.2)" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,ios

  e2e-linux:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_linux_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,linux

  e2e-macos:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_macos_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,macos

  e2e-web:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_web_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices
      - run: chromedriver --version

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,web

  e2e-windows:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_windows_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,windows
