name: rapid_cli_e2e_fast

on:
  workflow_dispatch:

jobs:
  e2e:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test -j 1 --run-skipped -t e2e -x android,ios,linux,macos,web,windows
