# TODO This is a dart package maybe just use dart sdk only instead of flutter
name: rapid

on:
  push:
    paths:
      - "packages/rapid/rapid/rapid/**"
      - ".github/workflows/rapid.yaml"
      - "!packages/rapid/rapid/rapid/README.md"

  pull_request:
    paths:
      - "packages/rapid/rapid/rapid/**"
      - ".github/workflows/rapid.yaml"
      - "!packages/rapid/rapid/rapid/README.md"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/rapid/rapid/rapid

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5

      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format . --set-exit-if-changed

      - name: Analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test -j 1 --no-pub --test-randomize-ordering-seed random
