# TODO clean up and use fixtures.sh to gen fixtures in the workflow
name: rapid_cli_e2e_slow

on:
  workflow_dispatch:

jobs:
  e2e-android:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     api-level:
    #       - 29

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_android_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      # - uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # TODO remove and disable gradle caching

      # - name: AVD Cache
      #   uses: actions/cache@v3
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/adb*
      #     key: avd-29

      # - name: Create AVD And Generate Snapshot For Caching
      #   if: steps.avd-cache.outputs.cache-hit != 'true'
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     force-avd-creation: false
      #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: false
      #     script: echo "Generated AVD snapshot for caching."

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Coverage Utils
        run: flutter pub global activate coverage && flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29 #${{ matrix.api-level }}
          #force-avd-creation: false
          #emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          #disable-animations: true
          #arch: x86_64
          #profile: Nexus 6
          script: cd packages/rapid_cli && flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,android

  e2e-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_ios_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: "List All Simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^iPhone 11 Simulator (16.2)" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,ios

  e2e-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_linux_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update -y

      - run: sudo apt-get install -y ninja-build libgtk-3-dev libblkid-dev
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,linux

  e2e-macos:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_macos_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,macos

  e2e-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_web_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices
      - run: chromedriver --version

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,web

  e2e-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_windows_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - run: git config --global core.longpaths true

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,windows
  e2e-mobile-android:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     api-level:
    #       - 29

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_mobile_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      # - uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # TODO remove and disable gradle caching

      # - name: AVD Cache
      #   uses: actions/cache@v3
      #   id: avd-cache
      #   with:
      #     path: |
      #       ~/.android/avd/*
      #       ~/.android/adb*
      #     key: avd-29

      # - name: Create AVD And Generate Snapshot For Caching
      #   if: steps.avd-cache.outputs.cache-hit != 'true'
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     force-avd-creation: false
      #     emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #     disable-animations: false
      #     script: echo "Generated AVD snapshot for caching."

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Coverage Utils
        run: flutter pub global activate coverage && flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29 #${{ matrix.api-level }}
          #force-avd-creation: false
          #emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          #disable-animations: true
          #arch: x86_64
          #profile: Nexus 6
          script: cd packages/rapid_cli && flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,mobile

  e2e-mobile-ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_mobile_test.dart

          # E2E tests for create command
          - test/e2e/create_test.dart

    steps:
      - uses: actions/checkout@v3
      # Setup Git to clone private Repos (this step should not be needed when rapid is public)
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/

      - name: "List All Simulators"
        run: "xcrun xctrace list devices"
      - name: "Start Simulator"
        run: |
          UDID=$(xcrun xctrace list devices | grep "^iPhone 11 Simulator (16.2)" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          xcrun simctl boot "${UDID:?No Simulator with this name found}"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: flutter --version
      - run: flutter devices

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Lcov Utils
        run: flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: flutter test ${{ matrix.test }} -j 1 --run-skipped -t e2e,mobile
