name: rapid_cli

on:
  push:
    paths:
      - "packages/rapid_cli/**"
      - ".github/workflows/rapid_cli.yaml"
      - "!packages/rapid_cli/README.md"
      - "!packages/rapid_cli/assets/**"
      - "!packages/rapid_cli/fixtures/**"
      - "!packages/rapid_cli/tool/**"

  pull_request:
    paths:
      - "packages/rapid_cli/**"
      - ".github/workflows/rapid_cli.yaml"
      - "!packages/rapid_cli/README.md"
      - "!packages/rapid_cli/assets/**"
      - "!packages/rapid_cli/fixtures/**"
      - "!packages/rapid_cli/tool/**"

jobs:
  test:
    defaults:
      run:
        working-directory: packages/rapid_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v5

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format . --set-exit-if-changed

      - name: Analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test test/unit -j 1 --no-pub --test-randomize-ordering-seed random --coverage
        # run: |
        #   flutter pub global activate coverage 1.2.0
        #   flutter pub run test -j 1 --coverage=coverage --test-randomize-ordering-seed random && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib

      # - name: Ensure 100% Code Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v2
      #   with:
      #     min_coverage: 100
      #     path: packages/rapid_cli/coverage/lcov.info
