name: tinker

on:
  push:
    branches:
      - dev

env:
  FLUTTER_VERSION: 3.10.0
  FIXTURES_PATH: packages/rapid_cli/test/e2e/fixtures

jobs:
  generate-fixtures:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/rapid_cli

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Mason CLI
        run: dart pub global activate mason_cli

      - name: Setup Rapid CLI
        run: melos dev:activate

      - name: Cache fixtures
        uses: actions/cache@v3
        with:
          path: ${{ env.FIXTURES_PATH }}
          key: fixtures-${{ github.run_id }}

      - name: Generate fixtures
        run: cd test/e2e/fixtures && rapid create project_none -o project_none

  e2e:
    runs-on: ubuntu-latest
    needs: generate-fixtures
    defaults:
      run:
        working-directory: packages/rapid_cli

    strategy:
      fail-fast: false
      matrix:
        test:
          # E2E tests for activate command
          - test/e2e/activate_macos_test.dart

    steps:
      - uses: actions/checkout@v3

      - name: Get cached fixtures
        uses: actions/cache/restore@v3
        with:
          path: ${{ env.FIXTURES_PATH }}
          key: fixtures-${{ github.run_id }}

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Setup Melos
        run: flutter pub global activate melos

      - name: Setup Coverage Utils
        run: flutter pub global activate coverage && flutter pub global activate test_cov_console && flutter pub global activate remove_from_coverage

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run E2E Tests
        run: dart test ${{ matrix.test }} -j 1 --run-skipped -t e2e
