name: {{project_name}}_ui
description: Widgets and themes implementing platform independent
  {{project_name.titleCase()}} design language.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^2.0.0

dev_dependencies:
  alchemist: ^0.6.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  theme_tailor: ^2.0.0

# The following section is specific to the FlutterGen package.
# See: https://pub.dev/packages/flutter_gen#configuration-file
flutter_gen:
  output: lib/src/
  # To add support for svg via flutter_svg package
  # integrations:
  #   flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
